ftp:
  user: test
  password: test
  host: localhost
  port: 21
quarkus:
  hibernate-orm:
    database:
      generation: create
  datasource:
    db-kind: mysql
    username: wordpress
    password: wordpress
    jdbc:
      url: jdbc:mysql://localhost/wordpress
