//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.28 at 12:19:02 PM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}LevelSequenceNumber" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}TextItem"/&gt;
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}AVItem"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}ComponentTypeName"/&gt;
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}ComponentNumber" minOccurs="0"/&gt;
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}TitleDetail" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}ComponentNumber" minOccurs="0"/&gt;
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/reference}TitleDetail" maxOccurs="unbounded"/&gt;
 *           &lt;/sequence&gt;
 *         &lt;/choice&gt;
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.authorship"/&gt;
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.languages"/&gt;
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.subjects"/&gt;
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.descriptions"/&gt;
 *         &lt;group ref="{http://ns.editeur.org/onix/3.0/reference}gp.related_materials"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://ns.editeur.org/onix/3.0/reference}generalAttributes"/&gt;
 *       &lt;attribute name="refname"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="ContentItem"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="shortname"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="contentitem"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "ContentItem")
public class ContentItem {

    @XmlElementRefs({
        @XmlElementRef(name = "LevelSequenceNumber", namespace = "http://ns.editeur.org/onix/3.0/reference", type = LevelSequenceNumber.class, required = false),
        @XmlElementRef(name = "TextItem", namespace = "http://ns.editeur.org/onix/3.0/reference", type = TextItem.class, required = false),
        @XmlElementRef(name = "AVItem", namespace = "http://ns.editeur.org/onix/3.0/reference", type = AVItem.class, required = false),
        @XmlElementRef(name = "ComponentTypeName", namespace = "http://ns.editeur.org/onix/3.0/reference", type = ComponentTypeName.class, required = false),
        @XmlElementRef(name = "ComponentNumber", namespace = "http://ns.editeur.org/onix/3.0/reference", type = ComponentNumber.class, required = false),
        @XmlElementRef(name = "TitleDetail", namespace = "http://ns.editeur.org/onix/3.0/reference", type = TitleDetail.class, required = false),
        @XmlElementRef(name = "Contributor", namespace = "http://ns.editeur.org/onix/3.0/reference", type = Contributor.class, required = false),
        @XmlElementRef(name = "ContributorStatement", namespace = "http://ns.editeur.org/onix/3.0/reference", type = ContributorStatement.class, required = false),
        @XmlElementRef(name = "NoContributor", namespace = "http://ns.editeur.org/onix/3.0/reference", type = NoContributor.class, required = false),
        @XmlElementRef(name = "Language", namespace = "http://ns.editeur.org/onix/3.0/reference", type = Language.class, required = false),
        @XmlElementRef(name = "Subject", namespace = "http://ns.editeur.org/onix/3.0/reference", type = Subject.class, required = false),
        @XmlElementRef(name = "NameAsSubject", namespace = "http://ns.editeur.org/onix/3.0/reference", type = NameAsSubject.class, required = false),
        @XmlElementRef(name = "TextContent", namespace = "http://ns.editeur.org/onix/3.0/reference", type = TextContent.class, required = false),
        @XmlElementRef(name = "CitedContent", namespace = "http://ns.editeur.org/onix/3.0/reference", type = CitedContent.class, required = false),
        @XmlElementRef(name = "SupportingResource", namespace = "http://ns.editeur.org/onix/3.0/reference", type = SupportingResource.class, required = false),
        @XmlElementRef(name = "RelatedWork", namespace = "http://ns.editeur.org/onix/3.0/reference", type = RelatedWork.class, required = false),
        @XmlElementRef(name = "RelatedProduct", namespace = "http://ns.editeur.org/onix/3.0/reference", type = RelatedProduct.class, required = false)
    })
    protected List<Object> content;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcename")
    protected String sourcename;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "ComponentNumber" is used by two different parts of a schema. See: 
     * line 2578 of file:/home/dkroesen/Projects/syncer/src/main/resources/xsd/ONIX_BookProduct_3.0_reference.xsd
     * line 2574 of file:/home/dkroesen/Projects/syncer/src/main/resources/xsd/ONIX_BookProduct_3.0_reference.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LevelSequenceNumber }
     * {@link TextItem }
     * {@link AVItem }
     * {@link ComponentTypeName }
     * {@link ComponentNumber }
     * {@link TitleDetail }
     * {@link Contributor }
     * {@link ContributorStatement }
     * {@link NoContributor }
     * {@link Language }
     * {@link Subject }
     * {@link NameAsSubject }
     * {@link TextContent }
     * {@link CitedContent }
     * {@link SupportingResource }
     * {@link RelatedWork }
     * {@link RelatedProduct }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

}
