//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.28 at 12:19:02 PM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List139.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List139"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SYM"/&gt;
 *     &lt;enumeration value="ACM"/&gt;
 *     &lt;enumeration value="AAP"/&gt;
 *     &lt;enumeration value="ADL"/&gt;
 *     &lt;enumeration value="ACB"/&gt;
 *     &lt;enumeration value="AKA"/&gt;
 *     &lt;enumeration value="AKK"/&gt;
 *     &lt;enumeration value="ALB"/&gt;
 *     &lt;enumeration value="ALV"/&gt;
 *     &lt;enumeration value="ALT"/&gt;
 *     &lt;enumeration value="AMZ"/&gt;
 *     &lt;enumeration value="ANR"/&gt;
 *     &lt;enumeration value="ANB"/&gt;
 *     &lt;enumeration value="APA"/&gt;
 *     &lt;enumeration value="APC"/&gt;
 *     &lt;enumeration value="ARK"/&gt;
 *     &lt;enumeration value="ASD"/&gt;
 *     &lt;enumeration value="ASB"/&gt;
 *     &lt;enumeration value="AUD"/&gt;
 *     &lt;enumeration value="AUC"/&gt;
 *     &lt;enumeration value="ATK"/&gt;
 *     &lt;enumeration value="ELU"/&gt;
 *     &lt;enumeration value="BDL"/&gt;
 *     &lt;enumeration value="BNO"/&gt;
 *     &lt;enumeration value="BDZ"/&gt;
 *     &lt;enumeration value="BBB"/&gt;
 *     &lt;enumeration value="BST"/&gt;
 *     &lt;enumeration value="BOD"/&gt;
 *     &lt;enumeration value="MMM"/&gt;
 *     &lt;enumeration value="BIL"/&gt;
 *     &lt;enumeration value="BLG"/&gt;
 *     &lt;enumeration value="BJW"/&gt;
 *     &lt;enumeration value="BLA"/&gt;
 *     &lt;enumeration value="BLK"/&gt;
 *     &lt;enumeration value="GOS"/&gt;
 *     &lt;enumeration value="BGI"/&gt;
 *     &lt;enumeration value="BSK"/&gt;
 *     &lt;enumeration value="BSY"/&gt;
 *     &lt;enumeration value="BKU"/&gt;
 *     &lt;enumeration value="BLD"/&gt;
 *     &lt;enumeration value="BCA"/&gt;
 *     &lt;enumeration value="BDO"/&gt;
 *     &lt;enumeration value="BSL"/&gt;
 *     &lt;enumeration value="BOO"/&gt;
 *     &lt;enumeration value="BBI"/&gt;
 *     &lt;enumeration value="BSH"/&gt;
 *     &lt;enumeration value="BMA"/&gt;
 *     &lt;enumeration value="BKP"/&gt;
 *     &lt;enumeration value="BRB"/&gt;
 *     &lt;enumeration value="BKM"/&gt;
 *     &lt;enumeration value="BKS"/&gt;
 *     &lt;enumeration value="BTP"/&gt;
 *     &lt;enumeration value="BKY"/&gt;
 *     &lt;enumeration value="BRD"/&gt;
 *     &lt;enumeration value="BRT"/&gt;
 *     &lt;enumeration value="BSU"/&gt;
 *     &lt;enumeration value="CAI"/&gt;
 *     &lt;enumeration value="CDL"/&gt;
 *     &lt;enumeration value="CDN"/&gt;
 *     &lt;enumeration value="CEB"/&gt;
 *     &lt;enumeration value="CFU"/&gt;
 *     &lt;enumeration value="CHP"/&gt;
 *     &lt;enumeration value="CHD"/&gt;
 *     &lt;enumeration value="CYM"/&gt;
 *     &lt;enumeration value="CMX"/&gt;
 *     &lt;enumeration value="COP"/&gt;
 *     &lt;enumeration value="CST"/&gt;
 *     &lt;enumeration value="CRB"/&gt;
 *     &lt;enumeration value="CVS"/&gt;
 *     &lt;enumeration value="CVM"/&gt;
 *     &lt;enumeration value="CYB"/&gt;
 *     &lt;enumeration value="DAU"/&gt;
 *     &lt;enumeration value="DEM"/&gt;
 *     &lt;enumeration value="DSG"/&gt;
 *     &lt;enumeration value="DIL"/&gt;
 *     &lt;enumeration value="DYM"/&gt;
 *     &lt;enumeration value="EKJ"/&gt;
 *     &lt;enumeration value="EPA"/&gt;
 *     &lt;enumeration value="ERD"/&gt;
 *     &lt;enumeration value="ELC"/&gt;
 *     &lt;enumeration value="ESN"/&gt;
 *     &lt;enumeration value="EBK"/&gt;
 *     &lt;enumeration value="EBC"/&gt;
 *     &lt;enumeration value="ECH"/&gt;
 *     &lt;enumeration value="ECI"/&gt;
 *     &lt;enumeration value="ELE"/&gt;
 *     &lt;enumeration value="ELI"/&gt;
 *     &lt;enumeration value="ELS"/&gt;
 *     &lt;enumeration value="ELK"/&gt;
 *     &lt;enumeration value="ELL"/&gt;
 *     &lt;enumeration value="EMP"/&gt;
 *     &lt;enumeration value="ENH"/&gt;
 *     &lt;enumeration value="EPC"/&gt;
 *     &lt;enumeration value="ELN"/&gt;
 *     &lt;enumeration value="EVB"/&gt;
 *     &lt;enumeration value="FAB"/&gt;
 *     &lt;enumeration value="FAI"/&gt;
 *     &lt;enumeration value="FDB"/&gt;
 *     &lt;enumeration value="FIN"/&gt;
 *     &lt;enumeration value="FSP"/&gt;
 *     &lt;enumeration value="FLP"/&gt;
 *     &lt;enumeration value="FNC"/&gt;
 *     &lt;enumeration value="FOL"/&gt;
 *     &lt;enumeration value="FRY"/&gt;
 *     &lt;enumeration value="GMS"/&gt;
 *     &lt;enumeration value="GAR"/&gt;
 *     &lt;enumeration value="GLO"/&gt;
 *     &lt;enumeration value="GOO"/&gt;
 *     &lt;enumeration value="HST"/&gt;
 *     &lt;enumeration value="HMV"/&gt;
 *     &lt;enumeration value="HMD"/&gt;
 *     &lt;enumeration value="ILU"/&gt;
 *     &lt;enumeration value="IMM"/&gt;
 *     &lt;enumeration value="IND"/&gt;
 *     &lt;enumeration value="INF"/&gt;
 *     &lt;enumeration value="ILT"/&gt;
 *     &lt;enumeration value="IBS"/&gt;
 *     &lt;enumeration value="IZN"/&gt;
 *     &lt;enumeration value="JAM"/&gt;
 *     &lt;enumeration value="JBH"/&gt;
 *     &lt;enumeration value="JSM"/&gt;
 *     &lt;enumeration value="KMT"/&gt;
 *     &lt;enumeration value="KIP"/&gt;
 *     &lt;enumeration value="KRJ"/&gt;
 *     &lt;enumeration value="KID"/&gt;
 *     &lt;enumeration value="KPV"/&gt;
 *     &lt;enumeration value="KNB"/&gt;
 *     &lt;enumeration value="KNO"/&gt;
 *     &lt;enumeration value="KBO"/&gt;
 *     &lt;enumeration value="KOO"/&gt;
 *     &lt;enumeration value="KOR"/&gt;
 *     &lt;enumeration value="KRG"/&gt;
 *     &lt;enumeration value="LEG"/&gt;
 *     &lt;enumeration value="LTP"/&gt;
 *     &lt;enumeration value="LEX"/&gt;
 *     &lt;enumeration value="LDL"/&gt;
 *     &lt;enumeration value="LMB"/&gt;
 *     &lt;enumeration value="LWE"/&gt;
 *     &lt;enumeration value="MAC"/&gt;
 *     &lt;enumeration value="MAG"/&gt;
 *     &lt;enumeration value="MNO"/&gt;
 *     &lt;enumeration value="MKS"/&gt;
 *     &lt;enumeration value="MAT"/&gt;
 *     &lt;enumeration value="MMS"/&gt;
 *     &lt;enumeration value="ADP"/&gt;
 *     &lt;enumeration value="MCR"/&gt;
 *     &lt;enumeration value="MSF"/&gt;
 *     &lt;enumeration value="MOF"/&gt;
 *     &lt;enumeration value="MRR"/&gt;
 *     &lt;enumeration value="MTC"/&gt;
 *     &lt;enumeration value="MYB"/&gt;
 *     &lt;enumeration value="MYI"/&gt;
 *     &lt;enumeration value="NTR"/&gt;
 *     &lt;enumeration value="NEX"/&gt;
 *     &lt;enumeration value="NXT"/&gt;
 *     &lt;enumeration value="NOL"/&gt;
 *     &lt;enumeration value="NUM"/&gt;
 *     &lt;enumeration value="ODL"/&gt;
 *     &lt;enumeration value="OFD"/&gt;
 *     &lt;enumeration value="OFM"/&gt;
 *     &lt;enumeration value="OLF"/&gt;
 *     &lt;enumeration value="OSS"/&gt;
 *     &lt;enumeration value="OVD"/&gt;
 *     &lt;enumeration value="OYS"/&gt;
 *     &lt;enumeration value="PST"/&gt;
 *     &lt;enumeration value="PER"/&gt;
 *     &lt;enumeration value="PTS"/&gt;
 *     &lt;enumeration value="PTC"/&gt;
 *     &lt;enumeration value="PIC"/&gt;
 *     &lt;enumeration value="PLY"/&gt;
 *     &lt;enumeration value="POD"/&gt;
 *     &lt;enumeration value="POY"/&gt;
 *     &lt;enumeration value="PDM"/&gt;
 *     &lt;enumeration value="POK"/&gt;
 *     &lt;enumeration value="PTB"/&gt;
 *     &lt;enumeration value="PLO"/&gt;
 *     &lt;enumeration value="ELB"/&gt;
 *     &lt;enumeration value="RDB"/&gt;
 *     &lt;enumeration value="RCL"/&gt;
 *     &lt;enumeration value="RST"/&gt;
 *     &lt;enumeration value="RET"/&gt;
 *     &lt;enumeration value="RTZ"/&gt;
 *     &lt;enumeration value="RMB"/&gt;
 *     &lt;enumeration value="RBD"/&gt;
 *     &lt;enumeration value="SGR"/&gt;
 *     &lt;enumeration value="SAC"/&gt;
 *     &lt;enumeration value="SAF"/&gt;
 *     &lt;enumeration value="SFW"/&gt;
 *     &lt;enumeration value="SNS"/&gt;
 *     &lt;enumeration value="SAX"/&gt;
 *     &lt;enumeration value="SCR"/&gt;
 *     &lt;enumeration value="SLF"/&gt;
 *     &lt;enumeration value="SEQ"/&gt;
 *     &lt;enumeration value="SES"/&gt;
 *     &lt;enumeration value="SBT"/&gt;
 *     &lt;enumeration value="SKL"/&gt;
 *     &lt;enumeration value="SKB"/&gt;
 *     &lt;enumeration value="SMW"/&gt;
 *     &lt;enumeration value="SNY"/&gt;
 *     &lt;enumeration value="SPO"/&gt;
 *     &lt;enumeration value="STP"/&gt;
 *     &lt;enumeration value="STH"/&gt;
 *     &lt;enumeration value="STT"/&gt;
 *     &lt;enumeration value="SKK"/&gt;
 *     &lt;enumeration value="SPL"/&gt;
 *     &lt;enumeration value="SUP"/&gt;
 *     &lt;enumeration value="SSK"/&gt;
 *     &lt;enumeration value="TRG"/&gt;
 *     &lt;enumeration value="TES"/&gt;
 *     &lt;enumeration value="TIK"/&gt;
 *     &lt;enumeration value="TOK"/&gt;
 *     &lt;enumeration value="TOL"/&gt;
 *     &lt;enumeration value="TSR"/&gt;
 *     &lt;enumeration value="TSO"/&gt;
 *     &lt;enumeration value="TKK"/&gt;
 *     &lt;enumeration value="TXR"/&gt;
 *     &lt;enumeration value="UBH"/&gt;
 *     &lt;enumeration value="VRG"/&gt;
 *     &lt;enumeration value="TEA"/&gt;
 *     &lt;enumeration value="WHS"/&gt;
 *     &lt;enumeration value="WTR"/&gt;
 *     &lt;enumeration value="WLM"/&gt;
 *     &lt;enumeration value="WST"/&gt;
 *     &lt;enumeration value="WHT"/&gt;
 *     &lt;enumeration value="WLS"/&gt;
 *     &lt;enumeration value="WLW"/&gt;
 *     &lt;enumeration value="YOU"/&gt;
 *     &lt;enumeration value="YSC"/&gt;
 *     &lt;enumeration value="ZVV"/&gt;
 *     &lt;enumeration value="PUB"/&gt;
 *     &lt;enumeration value="ZZZ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List139")
@XmlEnum
public enum List139 {

    SYM,
    ACM,

    /**
     * Academic and Professional Book Center (HK)
     * 
     */
    AAP,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ADL,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ACB,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    AKA,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    AKK,
    ALB,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ALV,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ALT,
    AMZ,
    ANR,
    ANB,
    APA,
    APC,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ARK,
    ASD,
    ASB,
    AUD,
    AUC,
    ATK,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ELU,

    /**
     * Deprecated
     * 
     */
    BDL,
    BNO,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BDZ,
    BBB,
    BST,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BOD,

    /**
     * Formerly 3M Cloud Library
     * 
     */
    MMM,

    /**
     * Deprecated
     * 
     */
    BIL,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BLG,
    BJW,
    BLA,
    BLK,

    /**
     * Formerly GoSpoken/Mobcast. Deprecated
     * 
     */
    GOS,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BGI,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BSK,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BSY,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BKU,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BLD,
    BCA,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BDO,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BSL,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BOO,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BBI,
    BSH,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BMA,
    BKP,

    /**
     * Deprecated
     * 
     */
    BRB,
    BKM,
    BKS,
    BTP,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BKY,

    /**
     * Deprecated
     * 
     */
    BRD,

    /**
     * Deprecated
     * 
     */
    BRT,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    BSU,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    CAI,
    CDL,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    CDN,
    CEB,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    CFU,

    /**
     * Danish e-book retailer. Only for use in ONIX 3.0 or later
     * 
     */
    CHP,
    CHD,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    CYM,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    CMX,

    /**
     * Deprecated
     * 
     */
    COP,
    CST,
    CRB,
    CVS,

    /**
     * www.cvs-mediatheques.com
     * 
     */
    CVM,
    CYB,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    DAU,
    DEM,
    DSG,
    DIL,
    DYM,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    EKJ,
    EPA,
    ERD,
    ELC,
    ESN,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    EBK,

    /**
     * www.ebooks.com
     * 
     */
    EBC,

    /**
     * Deprecated
     * 
     */
    ECH,
    ECI,
    ELE,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ELI,

    /**
     * Only for use in ONIX 3.0 or later. Deprecated
     * 
     */
    ELS,

    /**
     * Only for use in ONIX 3.0 or later. Deprecated
     * 
     */
    ELK,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ELL,
    EMP,
    ENH,

    /**
     * www.getepic.com
     * 
     */
    EPC,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ELN,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    EVB,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    FAB,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    FAI,
    FDB,
    FIN,
    FSP,
    FLP,
    FNC,
    FOL,
    FRY,
    GMS,

    /**
     * (as a retail platform). Only for use in ONIX 3.0 or later
     * 
     */
    GAR,
    GLO,
    GOO,

    /**
     * Deprecated
     * 
     */
    HST,
    HMV,
    HMD,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ILU,
    IMM,
    IND,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    INF,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ILT,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    IBS,
    IZN,

    /**
     * Only for use in ONIX 3.0 or later. Deprecated
     * 
     */
    JAM,
    JBH,
    JSM,
    KMT,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    KIP,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    KRJ,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    KID,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    KPV,
    KNB,

    /**
     * Deprecated
     * 
     */
    KNO,
    KBO,
    KOO,
    KOR,
    KRG,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    LEG,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    LTP,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    LEX,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    LDL,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    LMB,
    LWE,
    MAC,
    MAG,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    MNO,
    MKS,
    MAT,

    /**
     * Also known as Media World
     * 
     */
    MMS,
    ADP,
    MCR,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    MSF,
    MOF,
    MRR,
    MTC,

    /**
     * Deprecated
     * 
     */
    MYB,
    MYI,
    NTR,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    NEX,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    NXT,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    NOL,
    NUM,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    ODL,
    OFD,
    OFM,
    OLF,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    OSS,
    OVD,

    /**
     * Deprecated
     * 
     */
    OYS,

    /**
     * Deprecated
     * 
     */
    PST,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    PER,
    PTS,
    PTC,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    PIC,
    PLY,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    POD,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    POY,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    PDM,

    /**
     * Only for use in ONIX 3.0 or later. Deprecated
     * 
     */
    POK,
    PTB,

    /**
     * Publio.pl. Only for use in ONIX 3.0 or later
     * 
     */
    PLO,

    /**
     * Formerly Axiell Elib.se
     * 
     */
    ELB,

    /**
     * Deprecated
     * 
     */
    RDB,
    RCL,
    RST,
    RET,
    RTZ,

    /**
     * Deprecated
     * 
     */
    RMB,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    RBD,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    SGR,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    SAC,
    SAF,
    SFW,
    SNS,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    SAX,
    SCR,
    SLF,
    SEQ,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    SES,
    SBT,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    SKL,
    SKB,
    SMW,
    SNY,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    SPO,
    STP,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    STH,
    STT,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    SKK,

    /**
     * Only for use in ONIX 3.0 or later. Deprecated
     * 
     */
    SPL,

    /**
     * Only for use in ONIX 3.0 or later. Deprecated
     * 
     */
    SUP,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    SSK,
    TRG,
    TES,

    /**
     * TikTok’s in-app store. Only for use in ONIX 3.0 or later
     * 
     */
    TIK,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    TOK,
    TOL,
    TSR,
    TSO,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    TKK,

    /**
     * Deprecated
     * 
     */
    TXR,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    UBH,

    /**
     * Deprecated
     * 
     */
    VRG,

    /**
     * Formerly The Ebook Alternative
     * 
     */
    TEA,
    WHS,
    WTR,
    WLM,
    WST,
    WHT,
    WLS,
    WLW,
    YOU,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    YSC,

    /**
     * Formerly Virgin Megastores (UK)
     * 
     */
    ZVV,

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    PUB,

    /**
     * Include retailer name in <SalesOutletName>
     * 
     */
    ZZZ;

    public String value() {
        return name();
    }

    public static List139 fromValue(String v) {
        return valueOf(v);
    }

}
