//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.28 at 12:19:02 PM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List219.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List219"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="D"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List219")
@XmlEnum
public enum List219 {


    /**
     * Text or image copyright (normally indicated by the © symbol). The default if no <CopyrightType> is specified
     * 
     */
    C,

    /**
     * Phonogram copyright or neighbouring right (normally indicated by the ℗ symbol)
     * 
     */
    P,

    /**
     * Sui generis database right
     * 
     */
    D;

    public String value() {
        return name();
    }

    public static List219 fromValue(String v) {
        return valueOf(v);
    }

}
