//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.27 at 10:08:36 AM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List255.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List255"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ALP"/&gt;
 *     &lt;enumeration value="APP"/&gt;
 *     &lt;enumeration value="ATC"/&gt;
 *     &lt;enumeration value="AHL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List255")
@XmlEnum
public enum List255 {


    /**
     * Insert appears after an even numbered or before an odd numbered logical page. <InsertPointValue> is an integer page number
     * 
     */
    ALP,

    /**
     * Insert appears after an even numbered or before an odd numbered printed page number. <InsertPointValue> is an integer page number
     * 
     */
    APP,

    /**
     * Insert appears in the body at a specific timecode (hours, minutes, seconds, counted from the beginning of the product before any inserts are added). <InsertPointValue> is in the format HHHMMSS. Fill with leading zeroes if any elements are missing. If centisecond precision is required, use HHHMMSScc
     * 
     */
    ATC,

    /**
     * Insert appears before the block-level HTML element – &lt;InsertPointValue> is the value of the id or name attribute of the block-level element (which must be unique within the body of the product)
     * 
     */
    AHL;

    public String value() {
        return name();
    }

    public static List255 fromValue(String v) {
        return valueOf(v);
    }

}
