//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.27 at 11:32:06 AM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List50.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List50"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="cm"/&gt;
 *     &lt;enumeration value="gr"/&gt;
 *     &lt;enumeration value="in"/&gt;
 *     &lt;enumeration value="kg"/&gt;
 *     &lt;enumeration value="lb"/&gt;
 *     &lt;enumeration value="mm"/&gt;
 *     &lt;enumeration value="oz"/&gt;
 *     &lt;enumeration value="px"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List50")
@XmlEnum
public enum List50 {


    /**
     * Millimeters are the preferred metric unit of length
     * 
     */
    @XmlEnumValue("cm")
    CM("cm"),
    @XmlEnumValue("gr")
    GR("gr"),
    @XmlEnumValue("in")
    IN("in"),

    /**
     * Grams are the preferred metric unit of weight
     * 
     */
    @XmlEnumValue("kg")
    KG("kg"),

    /**
     * Ounces are the preferred US customary unit of weight
     * 
     */
    @XmlEnumValue("lb")
    LB("lb"),
    @XmlEnumValue("mm")
    MM("mm"),
    @XmlEnumValue("oz")
    OZ("oz"),
    @XmlEnumValue("px")
    PX("px");
    private final String value;

    List50(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List50 fromValue(String v) {
        for (List50 c: List50 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
