//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.28 at 12:19:02 PM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List229.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List229"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="u"/&gt;
 *     &lt;enumeration value="f"/&gt;
 *     &lt;enumeration value="m"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List229")
@XmlEnum
public enum List229 {


    /**
     * Provides positive indication that the gender is not known or is not specified by the sender for any reason
     * 
     */
    @XmlEnumValue("u")
    U("u"),
    @XmlEnumValue("f")
    F("f"),
    @XmlEnumValue("m")
    M("m");
    private final String value;

    List229(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List229 fromValue(String v) {
        for (List229 c: List229 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
