//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.27 at 11:32:06 AM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List261.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List261"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="u"/&gt;
 *     &lt;enumeration value="i"/&gt;
 *     &lt;enumeration value="q"/&gt;
 *     &lt;enumeration value="w"/&gt;
 *     &lt;enumeration value="e"/&gt;
 *     &lt;enumeration value="f"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List261")
@XmlEnum
public enum List261 {


    /**
     * Use ONLY if the error message severity cannot be determined (eg with a legacy system unable to provide detailed error codes)
     * 
     */
    @XmlEnumValue("u")
    U("u"),

    /**
     * For information only, provided to encourage the master file supplier to improve the quality of their files (eg to make rendering of the product more reliable/interoperable, or to improve accessibility, etc)
     * 
     */
    @XmlEnumValue("i")
    I("i"),

    /**
     * Request for clarification or further detail of the meaning of some part of the master file data provided
     * 
     */
    @XmlEnumValue("q")
    Q("q"),

    /**
     * The master files have been accepted as provided, but there may be issues in the way they were supplied
     * 
     */
    @XmlEnumValue("w")
    W("w"),

    /**
     * Some data in the content or structure of a master file caused an error due to not meeting the requirements of the relevant standard. The master file in question has been rejected, but processing of the remaining master files comprising tthe product has continued
     * 
     */
    @XmlEnumValue("e")
    E("e"),

    /**
     * Some data in the content or struture of a master file caused an unrecoverable error due to not meeting the requirements of the relevant standard. The entire set of master files for the product has been rejected
     * 
     */
    @XmlEnumValue("f")
    F("f");
    private final String value;

    List261(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List261 fromValue(String v) {
        for (List261 c: List261 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
