//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.27 at 11:32:06 AM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List49.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List49"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AU-CT"/&gt;
 *     &lt;enumeration value="AU-NS"/&gt;
 *     &lt;enumeration value="AU-NT"/&gt;
 *     &lt;enumeration value="AU-QL"/&gt;
 *     &lt;enumeration value="AU-SA"/&gt;
 *     &lt;enumeration value="AU-TS"/&gt;
 *     &lt;enumeration value="AU-VI"/&gt;
 *     &lt;enumeration value="AU-WA"/&gt;
 *     &lt;enumeration value="BE-BRU"/&gt;
 *     &lt;enumeration value="BE-VLG"/&gt;
 *     &lt;enumeration value="BE-WAL"/&gt;
 *     &lt;enumeration value="CA-AB"/&gt;
 *     &lt;enumeration value="CA-BC"/&gt;
 *     &lt;enumeration value="CA-MB"/&gt;
 *     &lt;enumeration value="CA-NB"/&gt;
 *     &lt;enumeration value="CA-NL"/&gt;
 *     &lt;enumeration value="CA-NS"/&gt;
 *     &lt;enumeration value="CA-NT"/&gt;
 *     &lt;enumeration value="CA-NU"/&gt;
 *     &lt;enumeration value="CA-ON"/&gt;
 *     &lt;enumeration value="CA-PE"/&gt;
 *     &lt;enumeration value="CA-QC"/&gt;
 *     &lt;enumeration value="CA-SK"/&gt;
 *     &lt;enumeration value="CA-YT"/&gt;
 *     &lt;enumeration value="CN-BJ"/&gt;
 *     &lt;enumeration value="CN-TJ"/&gt;
 *     &lt;enumeration value="CN-HE"/&gt;
 *     &lt;enumeration value="CN-SX"/&gt;
 *     &lt;enumeration value="CN-NM"/&gt;
 *     &lt;enumeration value="CN-LN"/&gt;
 *     &lt;enumeration value="CN-JL"/&gt;
 *     &lt;enumeration value="CN-HL"/&gt;
 *     &lt;enumeration value="CN-SH"/&gt;
 *     &lt;enumeration value="CN-JS"/&gt;
 *     &lt;enumeration value="CN-ZJ"/&gt;
 *     &lt;enumeration value="CN-AH"/&gt;
 *     &lt;enumeration value="CN-FJ"/&gt;
 *     &lt;enumeration value="CN-JX"/&gt;
 *     &lt;enumeration value="CN-SD"/&gt;
 *     &lt;enumeration value="CN-HA"/&gt;
 *     &lt;enumeration value="CN-HB"/&gt;
 *     &lt;enumeration value="CN-HN"/&gt;
 *     &lt;enumeration value="CN-GD"/&gt;
 *     &lt;enumeration value="CN-GX"/&gt;
 *     &lt;enumeration value="CN-HI"/&gt;
 *     &lt;enumeration value="CN-CQ"/&gt;
 *     &lt;enumeration value="CN-SC"/&gt;
 *     &lt;enumeration value="CN-GZ"/&gt;
 *     &lt;enumeration value="CN-YN"/&gt;
 *     &lt;enumeration value="CN-XZ"/&gt;
 *     &lt;enumeration value="CN-SN"/&gt;
 *     &lt;enumeration value="CN-GS"/&gt;
 *     &lt;enumeration value="CN-QH"/&gt;
 *     &lt;enumeration value="CN-NX"/&gt;
 *     &lt;enumeration value="CN-XJ"/&gt;
 *     &lt;enumeration value="CN-TW"/&gt;
 *     &lt;enumeration value="CN-HK"/&gt;
 *     &lt;enumeration value="CN-MO"/&gt;
 *     &lt;enumeration value="CN-11"/&gt;
 *     &lt;enumeration value="CN-12"/&gt;
 *     &lt;enumeration value="CN-13"/&gt;
 *     &lt;enumeration value="CN-14"/&gt;
 *     &lt;enumeration value="CN-15"/&gt;
 *     &lt;enumeration value="CN-21"/&gt;
 *     &lt;enumeration value="CN-22"/&gt;
 *     &lt;enumeration value="CN-23"/&gt;
 *     &lt;enumeration value="CN-31"/&gt;
 *     &lt;enumeration value="CN-32"/&gt;
 *     &lt;enumeration value="CN-33"/&gt;
 *     &lt;enumeration value="CN-34"/&gt;
 *     &lt;enumeration value="CN-35"/&gt;
 *     &lt;enumeration value="CN-36"/&gt;
 *     &lt;enumeration value="CN-37"/&gt;
 *     &lt;enumeration value="CN-41"/&gt;
 *     &lt;enumeration value="CN-42"/&gt;
 *     &lt;enumeration value="CN-43"/&gt;
 *     &lt;enumeration value="CN-44"/&gt;
 *     &lt;enumeration value="CN-45"/&gt;
 *     &lt;enumeration value="CN-46"/&gt;
 *     &lt;enumeration value="CN-50"/&gt;
 *     &lt;enumeration value="CN-51"/&gt;
 *     &lt;enumeration value="CN-52"/&gt;
 *     &lt;enumeration value="CN-53"/&gt;
 *     &lt;enumeration value="CN-54"/&gt;
 *     &lt;enumeration value="CN-61"/&gt;
 *     &lt;enumeration value="CN-62"/&gt;
 *     &lt;enumeration value="CN-63"/&gt;
 *     &lt;enumeration value="CN-64"/&gt;
 *     &lt;enumeration value="CN-65"/&gt;
 *     &lt;enumeration value="CN-71"/&gt;
 *     &lt;enumeration value="CN-91"/&gt;
 *     &lt;enumeration value="CN-92"/&gt;
 *     &lt;enumeration value="ES-CN"/&gt;
 *     &lt;enumeration value="FR-H"/&gt;
 *     &lt;enumeration value="GB-AIR"/&gt;
 *     &lt;enumeration value="GB-APS"/&gt;
 *     &lt;enumeration value="GB-CHA"/&gt;
 *     &lt;enumeration value="GB-ENG"/&gt;
 *     &lt;enumeration value="GB-EWS"/&gt;
 *     &lt;enumeration value="GB-IOM"/&gt;
 *     &lt;enumeration value="GB-NIR"/&gt;
 *     &lt;enumeration value="GB-SCT"/&gt;
 *     &lt;enumeration value="GB-WLS"/&gt;
 *     &lt;enumeration value="IE-AIR"/&gt;
 *     &lt;enumeration value="IT-AG"/&gt;
 *     &lt;enumeration value="IT-AL"/&gt;
 *     &lt;enumeration value="IT-AN"/&gt;
 *     &lt;enumeration value="IT-AO"/&gt;
 *     &lt;enumeration value="IT-AR"/&gt;
 *     &lt;enumeration value="IT-AP"/&gt;
 *     &lt;enumeration value="IT-AT"/&gt;
 *     &lt;enumeration value="IT-AV"/&gt;
 *     &lt;enumeration value="IT-BA"/&gt;
 *     &lt;enumeration value="IT-BT"/&gt;
 *     &lt;enumeration value="IT-BL"/&gt;
 *     &lt;enumeration value="IT-BN"/&gt;
 *     &lt;enumeration value="IT-BG"/&gt;
 *     &lt;enumeration value="IT-BI"/&gt;
 *     &lt;enumeration value="IT-BO"/&gt;
 *     &lt;enumeration value="IT-BZ"/&gt;
 *     &lt;enumeration value="IT-BS"/&gt;
 *     &lt;enumeration value="IT-BR"/&gt;
 *     &lt;enumeration value="IT-CA"/&gt;
 *     &lt;enumeration value="IT-CL"/&gt;
 *     &lt;enumeration value="IT-CB"/&gt;
 *     &lt;enumeration value="IT-CI"/&gt;
 *     &lt;enumeration value="IT-CE"/&gt;
 *     &lt;enumeration value="IT-CT"/&gt;
 *     &lt;enumeration value="IT-CZ"/&gt;
 *     &lt;enumeration value="IT-CH"/&gt;
 *     &lt;enumeration value="IT-CO"/&gt;
 *     &lt;enumeration value="IT-CS"/&gt;
 *     &lt;enumeration value="IT-CR"/&gt;
 *     &lt;enumeration value="IT-KR"/&gt;
 *     &lt;enumeration value="IT-CN"/&gt;
 *     &lt;enumeration value="IT-EN"/&gt;
 *     &lt;enumeration value="IT-FM"/&gt;
 *     &lt;enumeration value="IT-FE"/&gt;
 *     &lt;enumeration value="IT-FI"/&gt;
 *     &lt;enumeration value="IT-FG"/&gt;
 *     &lt;enumeration value="IT-FC"/&gt;
 *     &lt;enumeration value="IT-FR"/&gt;
 *     &lt;enumeration value="IT-GE"/&gt;
 *     &lt;enumeration value="IT-GO"/&gt;
 *     &lt;enumeration value="IT-GR"/&gt;
 *     &lt;enumeration value="IT-IM"/&gt;
 *     &lt;enumeration value="IT-IS"/&gt;
 *     &lt;enumeration value="IT-SP"/&gt;
 *     &lt;enumeration value="IT-AQ"/&gt;
 *     &lt;enumeration value="IT-LT"/&gt;
 *     &lt;enumeration value="IT-LE"/&gt;
 *     &lt;enumeration value="IT-LC"/&gt;
 *     &lt;enumeration value="IT-LI"/&gt;
 *     &lt;enumeration value="IT-LO"/&gt;
 *     &lt;enumeration value="IT-LU"/&gt;
 *     &lt;enumeration value="IT-MC"/&gt;
 *     &lt;enumeration value="IT-MN"/&gt;
 *     &lt;enumeration value="IT-MS"/&gt;
 *     &lt;enumeration value="IT-MT"/&gt;
 *     &lt;enumeration value="IT-VS"/&gt;
 *     &lt;enumeration value="IT-ME"/&gt;
 *     &lt;enumeration value="IT-MI"/&gt;
 *     &lt;enumeration value="IT-MO"/&gt;
 *     &lt;enumeration value="IT-MB"/&gt;
 *     &lt;enumeration value="IT-NA"/&gt;
 *     &lt;enumeration value="IT-NO"/&gt;
 *     &lt;enumeration value="IT-NU"/&gt;
 *     &lt;enumeration value="IT-OG"/&gt;
 *     &lt;enumeration value="IT-OT"/&gt;
 *     &lt;enumeration value="IT-OR"/&gt;
 *     &lt;enumeration value="IT-PD"/&gt;
 *     &lt;enumeration value="IT-PA"/&gt;
 *     &lt;enumeration value="IT-PR"/&gt;
 *     &lt;enumeration value="IT-PV"/&gt;
 *     &lt;enumeration value="IT-PG"/&gt;
 *     &lt;enumeration value="IT-PU"/&gt;
 *     &lt;enumeration value="IT-PE"/&gt;
 *     &lt;enumeration value="IT-PC"/&gt;
 *     &lt;enumeration value="IT-PI"/&gt;
 *     &lt;enumeration value="IT-PT"/&gt;
 *     &lt;enumeration value="IT-PN"/&gt;
 *     &lt;enumeration value="IT-PZ"/&gt;
 *     &lt;enumeration value="IT-PO"/&gt;
 *     &lt;enumeration value="IT-RG"/&gt;
 *     &lt;enumeration value="IT-RA"/&gt;
 *     &lt;enumeration value="IT-RC"/&gt;
 *     &lt;enumeration value="IT-RE"/&gt;
 *     &lt;enumeration value="IT-RI"/&gt;
 *     &lt;enumeration value="IT-RN"/&gt;
 *     &lt;enumeration value="IT-RM"/&gt;
 *     &lt;enumeration value="IT-RO"/&gt;
 *     &lt;enumeration value="IT-SA"/&gt;
 *     &lt;enumeration value="IT-SS"/&gt;
 *     &lt;enumeration value="IT-SV"/&gt;
 *     &lt;enumeration value="IT-SI"/&gt;
 *     &lt;enumeration value="IT-SR"/&gt;
 *     &lt;enumeration value="IT-SO"/&gt;
 *     &lt;enumeration value="IT-TA"/&gt;
 *     &lt;enumeration value="IT-TE"/&gt;
 *     &lt;enumeration value="IT-TR"/&gt;
 *     &lt;enumeration value="IT-TO"/&gt;
 *     &lt;enumeration value="IT-TP"/&gt;
 *     &lt;enumeration value="IT-TN"/&gt;
 *     &lt;enumeration value="IT-TV"/&gt;
 *     &lt;enumeration value="IT-TS"/&gt;
 *     &lt;enumeration value="IT-UD"/&gt;
 *     &lt;enumeration value="IT-VA"/&gt;
 *     &lt;enumeration value="IT-VE"/&gt;
 *     &lt;enumeration value="IT-VB"/&gt;
 *     &lt;enumeration value="IT-VC"/&gt;
 *     &lt;enumeration value="IT-VR"/&gt;
 *     &lt;enumeration value="IT-VV"/&gt;
 *     &lt;enumeration value="IT-VI"/&gt;
 *     &lt;enumeration value="IT-VT"/&gt;
 *     &lt;enumeration value="RS-KM"/&gt;
 *     &lt;enumeration value="RS-VO"/&gt;
 *     &lt;enumeration value="RU-AD"/&gt;
 *     &lt;enumeration value="RU-AL"/&gt;
 *     &lt;enumeration value="RU-BA"/&gt;
 *     &lt;enumeration value="RU-BU"/&gt;
 *     &lt;enumeration value="RU-CE"/&gt;
 *     &lt;enumeration value="RU-CU"/&gt;
 *     &lt;enumeration value="RU-DA"/&gt;
 *     &lt;enumeration value="RU-IN"/&gt;
 *     &lt;enumeration value="RU-KB"/&gt;
 *     &lt;enumeration value="RU-KL"/&gt;
 *     &lt;enumeration value="RU-KC"/&gt;
 *     &lt;enumeration value="RU-KR"/&gt;
 *     &lt;enumeration value="RU-KK"/&gt;
 *     &lt;enumeration value="RU-KO"/&gt;
 *     &lt;enumeration value="RU-ME"/&gt;
 *     &lt;enumeration value="RU-MO"/&gt;
 *     &lt;enumeration value="RU-SA"/&gt;
 *     &lt;enumeration value="RU-SE"/&gt;
 *     &lt;enumeration value="RU-TA"/&gt;
 *     &lt;enumeration value="RU-TY"/&gt;
 *     &lt;enumeration value="RU-UD"/&gt;
 *     &lt;enumeration value="RU-ALT"/&gt;
 *     &lt;enumeration value="RU-KAM"/&gt;
 *     &lt;enumeration value="RU-KHA"/&gt;
 *     &lt;enumeration value="RU-KDA"/&gt;
 *     &lt;enumeration value="RU-KYA"/&gt;
 *     &lt;enumeration value="RU-PER"/&gt;
 *     &lt;enumeration value="RU-PRI"/&gt;
 *     &lt;enumeration value="RU-STA"/&gt;
 *     &lt;enumeration value="RU-ZAB"/&gt;
 *     &lt;enumeration value="RU-AMU"/&gt;
 *     &lt;enumeration value="RU-ARK"/&gt;
 *     &lt;enumeration value="RU-AST"/&gt;
 *     &lt;enumeration value="RU-BEL"/&gt;
 *     &lt;enumeration value="RU-BRY"/&gt;
 *     &lt;enumeration value="RU-CHE"/&gt;
 *     &lt;enumeration value="RU-IRK"/&gt;
 *     &lt;enumeration value="RU-IVA"/&gt;
 *     &lt;enumeration value="RU-KGD"/&gt;
 *     &lt;enumeration value="RU-KLU"/&gt;
 *     &lt;enumeration value="RU-KEM"/&gt;
 *     &lt;enumeration value="RU-KIR"/&gt;
 *     &lt;enumeration value="RU-KOS"/&gt;
 *     &lt;enumeration value="RU-KGN"/&gt;
 *     &lt;enumeration value="RU-KRS"/&gt;
 *     &lt;enumeration value="RU-LEN"/&gt;
 *     &lt;enumeration value="RU-LIP"/&gt;
 *     &lt;enumeration value="RU-MAG"/&gt;
 *     &lt;enumeration value="RU-MOS"/&gt;
 *     &lt;enumeration value="RU-MUR"/&gt;
 *     &lt;enumeration value="RU-NIZ"/&gt;
 *     &lt;enumeration value="RU-NGR"/&gt;
 *     &lt;enumeration value="RU-NVS"/&gt;
 *     &lt;enumeration value="RU-OMS"/&gt;
 *     &lt;enumeration value="RU-ORE"/&gt;
 *     &lt;enumeration value="RU-ORL"/&gt;
 *     &lt;enumeration value="RU-PNZ"/&gt;
 *     &lt;enumeration value="RU-PSK"/&gt;
 *     &lt;enumeration value="RU-ROS"/&gt;
 *     &lt;enumeration value="RU-RYA"/&gt;
 *     &lt;enumeration value="RU-SAK"/&gt;
 *     &lt;enumeration value="RU-SAM"/&gt;
 *     &lt;enumeration value="RU-SAR"/&gt;
 *     &lt;enumeration value="RU-SMO"/&gt;
 *     &lt;enumeration value="RU-SVE"/&gt;
 *     &lt;enumeration value="RU-TAM"/&gt;
 *     &lt;enumeration value="RU-TOM"/&gt;
 *     &lt;enumeration value="RU-TUL"/&gt;
 *     &lt;enumeration value="RU-TVE"/&gt;
 *     &lt;enumeration value="RU-TYU"/&gt;
 *     &lt;enumeration value="RU-ULY"/&gt;
 *     &lt;enumeration value="RU-VLA"/&gt;
 *     &lt;enumeration value="RU-VGG"/&gt;
 *     &lt;enumeration value="RU-VLG"/&gt;
 *     &lt;enumeration value="RU-VOR"/&gt;
 *     &lt;enumeration value="RU-YAR"/&gt;
 *     &lt;enumeration value="RU-MOW"/&gt;
 *     &lt;enumeration value="RU-SPE"/&gt;
 *     &lt;enumeration value="RU-YEV"/&gt;
 *     &lt;enumeration value="RU-CHU"/&gt;
 *     &lt;enumeration value="RU-KHM"/&gt;
 *     &lt;enumeration value="RU-NEN"/&gt;
 *     &lt;enumeration value="RU-YAN"/&gt;
 *     &lt;enumeration value="US-AK"/&gt;
 *     &lt;enumeration value="US-AL"/&gt;
 *     &lt;enumeration value="US-AR"/&gt;
 *     &lt;enumeration value="US-AZ"/&gt;
 *     &lt;enumeration value="US-CA"/&gt;
 *     &lt;enumeration value="US-CO"/&gt;
 *     &lt;enumeration value="US-CT"/&gt;
 *     &lt;enumeration value="US-DC"/&gt;
 *     &lt;enumeration value="US-DE"/&gt;
 *     &lt;enumeration value="US-FL"/&gt;
 *     &lt;enumeration value="US-GA"/&gt;
 *     &lt;enumeration value="US-HI"/&gt;
 *     &lt;enumeration value="US-IA"/&gt;
 *     &lt;enumeration value="US-ID"/&gt;
 *     &lt;enumeration value="US-IL"/&gt;
 *     &lt;enumeration value="US-IN"/&gt;
 *     &lt;enumeration value="US-KS"/&gt;
 *     &lt;enumeration value="US-KY"/&gt;
 *     &lt;enumeration value="US-LA"/&gt;
 *     &lt;enumeration value="US-MA"/&gt;
 *     &lt;enumeration value="US-MD"/&gt;
 *     &lt;enumeration value="US-ME"/&gt;
 *     &lt;enumeration value="US-MI"/&gt;
 *     &lt;enumeration value="US-MN"/&gt;
 *     &lt;enumeration value="US-MO"/&gt;
 *     &lt;enumeration value="US-MS"/&gt;
 *     &lt;enumeration value="US-MT"/&gt;
 *     &lt;enumeration value="US-NC"/&gt;
 *     &lt;enumeration value="US-ND"/&gt;
 *     &lt;enumeration value="US-NE"/&gt;
 *     &lt;enumeration value="US-NH"/&gt;
 *     &lt;enumeration value="US-NJ"/&gt;
 *     &lt;enumeration value="US-NM"/&gt;
 *     &lt;enumeration value="US-NV"/&gt;
 *     &lt;enumeration value="US-NY"/&gt;
 *     &lt;enumeration value="US-OH"/&gt;
 *     &lt;enumeration value="US-OK"/&gt;
 *     &lt;enumeration value="US-OR"/&gt;
 *     &lt;enumeration value="US-PA"/&gt;
 *     &lt;enumeration value="US-RI"/&gt;
 *     &lt;enumeration value="US-SC"/&gt;
 *     &lt;enumeration value="US-SD"/&gt;
 *     &lt;enumeration value="US-TN"/&gt;
 *     &lt;enumeration value="US-TX"/&gt;
 *     &lt;enumeration value="US-UT"/&gt;
 *     &lt;enumeration value="US-VA"/&gt;
 *     &lt;enumeration value="US-VT"/&gt;
 *     &lt;enumeration value="US-WA"/&gt;
 *     &lt;enumeration value="US-WI"/&gt;
 *     &lt;enumeration value="US-WV"/&gt;
 *     &lt;enumeration value="US-WY"/&gt;
 *     &lt;enumeration value="ECZ"/&gt;
 *     &lt;enumeration value="WORLD"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List49")
@XmlEnum
public enum List49 {

    @XmlEnumValue("AU-CT")
    AU_CT("AU-CT"),
    @XmlEnumValue("AU-NS")
    AU_NS("AU-NS"),
    @XmlEnumValue("AU-NT")
    AU_NT("AU-NT"),
    @XmlEnumValue("AU-QL")
    AU_QL("AU-QL"),
    @XmlEnumValue("AU-SA")
    AU_SA("AU-SA"),
    @XmlEnumValue("AU-TS")
    AU_TS("AU-TS"),
    @XmlEnumValue("AU-VI")
    AU_VI("AU-VI"),
    @XmlEnumValue("AU-WA")
    AU_WA("AU-WA"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("BE-BRU")
    BE_BRU("BE-BRU"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("BE-VLG")
    BE_VLG("BE-VLG"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("BE-WAL")
    BE_WAL("BE-WAL"),
    @XmlEnumValue("CA-AB")
    CA_AB("CA-AB"),
    @XmlEnumValue("CA-BC")
    CA_BC("CA-BC"),
    @XmlEnumValue("CA-MB")
    CA_MB("CA-MB"),
    @XmlEnumValue("CA-NB")
    CA_NB("CA-NB"),
    @XmlEnumValue("CA-NL")
    CA_NL("CA-NL"),
    @XmlEnumValue("CA-NS")
    CA_NS("CA-NS"),
    @XmlEnumValue("CA-NT")
    CA_NT("CA-NT"),
    @XmlEnumValue("CA-NU")
    CA_NU("CA-NU"),
    @XmlEnumValue("CA-ON")
    CA_ON("CA-ON"),
    @XmlEnumValue("CA-PE")
    CA_PE("CA-PE"),
    @XmlEnumValue("CA-QC")
    CA_QC("CA-QC"),
    @XmlEnumValue("CA-SK")
    CA_SK("CA-SK"),
    @XmlEnumValue("CA-YT")
    CA_YT("CA-YT"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-BJ")
    CN_BJ("CN-BJ"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-TJ")
    CN_TJ("CN-TJ"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-HE")
    CN_HE("CN-HE"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-SX")
    CN_SX("CN-SX"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-NM")
    CN_NM("CN-NM"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-LN")
    CN_LN("CN-LN"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-JL")
    CN_JL("CN-JL"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-HL")
    CN_HL("CN-HL"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-SH")
    CN_SH("CN-SH"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-JS")
    CN_JS("CN-JS"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-ZJ")
    CN_ZJ("CN-ZJ"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-AH")
    CN_AH("CN-AH"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-FJ")
    CN_FJ("CN-FJ"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-JX")
    CN_JX("CN-JX"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-SD")
    CN_SD("CN-SD"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-HA")
    CN_HA("CN-HA"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-HB")
    CN_HB("CN-HB"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-HN")
    CN_HN("CN-HN"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-GD")
    CN_GD("CN-GD"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-GX")
    CN_GX("CN-GX"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-HI")
    CN_HI("CN-HI"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-CQ")
    CN_CQ("CN-CQ"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-SC")
    CN_SC("CN-SC"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-GZ")
    CN_GZ("CN-GZ"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-YN")
    CN_YN("CN-YN"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-XZ")
    CN_XZ("CN-XZ"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-SN")
    CN_SN("CN-SN"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-GS")
    CN_GS("CN-GS"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-QH")
    CN_QH("CN-QH"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-NX")
    CN_NX("CN-NX"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-XJ")
    CN_XJ("CN-XJ"),

    /**
     * Prefer code TW (Taiwan, Province of China) from List 91. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-TW")
    CN_TW("CN-TW"),

    /**
     * Prefer code HK (Hong Kong) from List 91. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-HK")
    CN_HK("CN-HK"),

    /**
     * Prefer code MO (Macao) from List 91. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("CN-MO")
    CN_MO("CN-MO"),

    /**
     * Deprecated in favor of CN-BJ
     * 
     */
    @XmlEnumValue("CN-11")
    CN_11("CN-11"),

    /**
     * Deprecated in favor of CN-TJ
     * 
     */
    @XmlEnumValue("CN-12")
    CN_12("CN-12"),

    /**
     * Deprecated in favor of CN-HE
     * 
     */
    @XmlEnumValue("CN-13")
    CN_13("CN-13"),

    /**
     * Deprecated in favor of CN-SX
     * 
     */
    @XmlEnumValue("CN-14")
    CN_14("CN-14"),

    /**
     * Deprecated in favor of CN-NM
     * 
     */
    @XmlEnumValue("CN-15")
    CN_15("CN-15"),

    /**
     * Deprecated in favor of CN-LN
     * 
     */
    @XmlEnumValue("CN-21")
    CN_21("CN-21"),

    /**
     * Deprecated in favor of CN-JL
     * 
     */
    @XmlEnumValue("CN-22")
    CN_22("CN-22"),

    /**
     * Deprecated in favor of CN-HL
     * 
     */
    @XmlEnumValue("CN-23")
    CN_23("CN-23"),

    /**
     * Deprecated in favor of CN-SH
     * 
     */
    @XmlEnumValue("CN-31")
    CN_31("CN-31"),

    /**
     * Deprecated in favor of CN-JS
     * 
     */
    @XmlEnumValue("CN-32")
    CN_32("CN-32"),

    /**
     * Deprecated in favor of CN-ZJ
     * 
     */
    @XmlEnumValue("CN-33")
    CN_33("CN-33"),

    /**
     * Deprecated in favor of CN-AH
     * 
     */
    @XmlEnumValue("CN-34")
    CN_34("CN-34"),

    /**
     * Deprecated in favor of CN-FJ
     * 
     */
    @XmlEnumValue("CN-35")
    CN_35("CN-35"),

    /**
     * Deprecated in favor of CN-JX
     * 
     */
    @XmlEnumValue("CN-36")
    CN_36("CN-36"),

    /**
     * Deprecated in favor of CN-SD
     * 
     */
    @XmlEnumValue("CN-37")
    CN_37("CN-37"),

    /**
     * Deprecated in favor of CN-HA
     * 
     */
    @XmlEnumValue("CN-41")
    CN_41("CN-41"),

    /**
     * Deprecated in favor of CN-HB
     * 
     */
    @XmlEnumValue("CN-42")
    CN_42("CN-42"),

    /**
     * Deprecated in favor of CN-HN
     * 
     */
    @XmlEnumValue("CN-43")
    CN_43("CN-43"),

    /**
     * Deprecated in favor of CN-GD
     * 
     */
    @XmlEnumValue("CN-44")
    CN_44("CN-44"),

    /**
     * Deprecated in favor of CN-GX
     * 
     */
    @XmlEnumValue("CN-45")
    CN_45("CN-45"),

    /**
     * Deprecated in favor of CN-HI
     * 
     */
    @XmlEnumValue("CN-46")
    CN_46("CN-46"),

    /**
     * Deprecated in favor of CN-CQ
     * 
     */
    @XmlEnumValue("CN-50")
    CN_50("CN-50"),

    /**
     * Deprecated in favor of CN-SC
     * 
     */
    @XmlEnumValue("CN-51")
    CN_51("CN-51"),

    /**
     * Deprecated in favor of CN-GZ
     * 
     */
    @XmlEnumValue("CN-52")
    CN_52("CN-52"),

    /**
     * Deprecated in favor of CN-YN
     * 
     */
    @XmlEnumValue("CN-53")
    CN_53("CN-53"),

    /**
     * Deprecated in favor of CN-XZ
     * 
     */
    @XmlEnumValue("CN-54")
    CN_54("CN-54"),

    /**
     * Deprecated in favor of CN-SN
     * 
     */
    @XmlEnumValue("CN-61")
    CN_61("CN-61"),

    /**
     * Deprecated in favor of CN-GS
     * 
     */
    @XmlEnumValue("CN-62")
    CN_62("CN-62"),

    /**
     * Deprecated in favor of CN-QH
     * 
     */
    @XmlEnumValue("CN-63")
    CN_63("CN-63"),

    /**
     * Deprecated in favor of CN-NX
     * 
     */
    @XmlEnumValue("CN-64")
    CN_64("CN-64"),

    /**
     * Deprecated in favor of CN-XJ
     * 
     */
    @XmlEnumValue("CN-65")
    CN_65("CN-65"),

    /**
     * Deprecated in favor of CN-TW, but prefer code TW (Taiwan, Province of China) from List 91
     * 
     */
    @XmlEnumValue("CN-71")
    CN_71("CN-71"),

    /**
     * Deprecated in favor of CN-HK, but prefer code HK (Hong Kong) from List 91
     * 
     */
    @XmlEnumValue("CN-91")
    CN_91("CN-91"),

    /**
     * Deprecated in favor of CN-MO, but prefer code MO (Macao) from List 91
     * 
     */
    @XmlEnumValue("CN-92")
    CN_92("CN-92"),
    @XmlEnumValue("ES-CN")
    ES_CN("ES-CN"),
    @XmlEnumValue("FR-H")
    FR_H("FR-H"),

    /**
     * Airside outlets at UK international airports only
     * 
     */
    @XmlEnumValue("GB-AIR")
    GB_AIR("GB-AIR"),

    /**
     * All UK airports, including both airside and other outlets
     * 
     */
    @XmlEnumValue("GB-APS")
    GB_APS("GB-APS"),

    /**
     * Deprecated, replaced by country codes GG – Guernsey, and JE – Jersey from List 91
     * 
     */
    @XmlEnumValue("GB-CHA")
    GB_CHA("GB-CHA"),
    @XmlEnumValue("GB-ENG")
    GB_ENG("GB-ENG"),

    /**
     * UK excluding Northern Ireland. Deprecated – use separate region codes GB-ENG, GB-SCT, GB-WLS instead
     * 
     */
    @XmlEnumValue("GB-EWS")
    GB_EWS("GB-EWS"),

    /**
     * Deprecated, replaced by country code IM – Isle of Man from List 91
     * 
     */
    @XmlEnumValue("GB-IOM")
    GB_IOM("GB-IOM"),
    @XmlEnumValue("GB-NIR")
    GB_NIR("GB-NIR"),
    @XmlEnumValue("GB-SCT")
    GB_SCT("GB-SCT"),
    @XmlEnumValue("GB-WLS")
    GB_WLS("GB-WLS"),

    /**
     * Airside outlets at Irish international airports only
     * 
     */
    @XmlEnumValue("IE-AIR")
    IE_AIR("IE-AIR"),
    @XmlEnumValue("IT-AG")
    IT_AG("IT-AG"),
    @XmlEnumValue("IT-AL")
    IT_AL("IT-AL"),
    @XmlEnumValue("IT-AN")
    IT_AN("IT-AN"),
    @XmlEnumValue("IT-AO")
    IT_AO("IT-AO"),
    @XmlEnumValue("IT-AR")
    IT_AR("IT-AR"),
    @XmlEnumValue("IT-AP")
    IT_AP("IT-AP"),
    @XmlEnumValue("IT-AT")
    IT_AT("IT-AT"),
    @XmlEnumValue("IT-AV")
    IT_AV("IT-AV"),
    @XmlEnumValue("IT-BA")
    IT_BA("IT-BA"),
    @XmlEnumValue("IT-BT")
    IT_BT("IT-BT"),
    @XmlEnumValue("IT-BL")
    IT_BL("IT-BL"),
    @XmlEnumValue("IT-BN")
    IT_BN("IT-BN"),
    @XmlEnumValue("IT-BG")
    IT_BG("IT-BG"),
    @XmlEnumValue("IT-BI")
    IT_BI("IT-BI"),
    @XmlEnumValue("IT-BO")
    IT_BO("IT-BO"),
    @XmlEnumValue("IT-BZ")
    IT_BZ("IT-BZ"),
    @XmlEnumValue("IT-BS")
    IT_BS("IT-BS"),
    @XmlEnumValue("IT-BR")
    IT_BR("IT-BR"),
    @XmlEnumValue("IT-CA")
    IT_CA("IT-CA"),
    @XmlEnumValue("IT-CL")
    IT_CL("IT-CL"),
    @XmlEnumValue("IT-CB")
    IT_CB("IT-CB"),
    @XmlEnumValue("IT-CI")
    IT_CI("IT-CI"),
    @XmlEnumValue("IT-CE")
    IT_CE("IT-CE"),
    @XmlEnumValue("IT-CT")
    IT_CT("IT-CT"),
    @XmlEnumValue("IT-CZ")
    IT_CZ("IT-CZ"),
    @XmlEnumValue("IT-CH")
    IT_CH("IT-CH"),
    @XmlEnumValue("IT-CO")
    IT_CO("IT-CO"),
    @XmlEnumValue("IT-CS")
    IT_CS("IT-CS"),
    @XmlEnumValue("IT-CR")
    IT_CR("IT-CR"),
    @XmlEnumValue("IT-KR")
    IT_KR("IT-KR"),
    @XmlEnumValue("IT-CN")
    IT_CN("IT-CN"),
    @XmlEnumValue("IT-EN")
    IT_EN("IT-EN"),
    @XmlEnumValue("IT-FM")
    IT_FM("IT-FM"),
    @XmlEnumValue("IT-FE")
    IT_FE("IT-FE"),
    @XmlEnumValue("IT-FI")
    IT_FI("IT-FI"),
    @XmlEnumValue("IT-FG")
    IT_FG("IT-FG"),
    @XmlEnumValue("IT-FC")
    IT_FC("IT-FC"),
    @XmlEnumValue("IT-FR")
    IT_FR("IT-FR"),
    @XmlEnumValue("IT-GE")
    IT_GE("IT-GE"),
    @XmlEnumValue("IT-GO")
    IT_GO("IT-GO"),
    @XmlEnumValue("IT-GR")
    IT_GR("IT-GR"),
    @XmlEnumValue("IT-IM")
    IT_IM("IT-IM"),
    @XmlEnumValue("IT-IS")
    IT_IS("IT-IS"),
    @XmlEnumValue("IT-SP")
    IT_SP("IT-SP"),
    @XmlEnumValue("IT-AQ")
    IT_AQ("IT-AQ"),
    @XmlEnumValue("IT-LT")
    IT_LT("IT-LT"),
    @XmlEnumValue("IT-LE")
    IT_LE("IT-LE"),
    @XmlEnumValue("IT-LC")
    IT_LC("IT-LC"),
    @XmlEnumValue("IT-LI")
    IT_LI("IT-LI"),
    @XmlEnumValue("IT-LO")
    IT_LO("IT-LO"),
    @XmlEnumValue("IT-LU")
    IT_LU("IT-LU"),
    @XmlEnumValue("IT-MC")
    IT_MC("IT-MC"),
    @XmlEnumValue("IT-MN")
    IT_MN("IT-MN"),
    @XmlEnumValue("IT-MS")
    IT_MS("IT-MS"),
    @XmlEnumValue("IT-MT")
    IT_MT("IT-MT"),
    @XmlEnumValue("IT-VS")
    IT_VS("IT-VS"),
    @XmlEnumValue("IT-ME")
    IT_ME("IT-ME"),
    @XmlEnumValue("IT-MI")
    IT_MI("IT-MI"),
    @XmlEnumValue("IT-MO")
    IT_MO("IT-MO"),
    @XmlEnumValue("IT-MB")
    IT_MB("IT-MB"),
    @XmlEnumValue("IT-NA")
    IT_NA("IT-NA"),
    @XmlEnumValue("IT-NO")
    IT_NO("IT-NO"),
    @XmlEnumValue("IT-NU")
    IT_NU("IT-NU"),
    @XmlEnumValue("IT-OG")
    IT_OG("IT-OG"),
    @XmlEnumValue("IT-OT")
    IT_OT("IT-OT"),
    @XmlEnumValue("IT-OR")
    IT_OR("IT-OR"),
    @XmlEnumValue("IT-PD")
    IT_PD("IT-PD"),
    @XmlEnumValue("IT-PA")
    IT_PA("IT-PA"),
    @XmlEnumValue("IT-PR")
    IT_PR("IT-PR"),
    @XmlEnumValue("IT-PV")
    IT_PV("IT-PV"),
    @XmlEnumValue("IT-PG")
    IT_PG("IT-PG"),
    @XmlEnumValue("IT-PU")
    IT_PU("IT-PU"),
    @XmlEnumValue("IT-PE")
    IT_PE("IT-PE"),
    @XmlEnumValue("IT-PC")
    IT_PC("IT-PC"),
    @XmlEnumValue("IT-PI")
    IT_PI("IT-PI"),
    @XmlEnumValue("IT-PT")
    IT_PT("IT-PT"),
    @XmlEnumValue("IT-PN")
    IT_PN("IT-PN"),
    @XmlEnumValue("IT-PZ")
    IT_PZ("IT-PZ"),
    @XmlEnumValue("IT-PO")
    IT_PO("IT-PO"),
    @XmlEnumValue("IT-RG")
    IT_RG("IT-RG"),
    @XmlEnumValue("IT-RA")
    IT_RA("IT-RA"),
    @XmlEnumValue("IT-RC")
    IT_RC("IT-RC"),
    @XmlEnumValue("IT-RE")
    IT_RE("IT-RE"),
    @XmlEnumValue("IT-RI")
    IT_RI("IT-RI"),
    @XmlEnumValue("IT-RN")
    IT_RN("IT-RN"),
    @XmlEnumValue("IT-RM")
    IT_RM("IT-RM"),
    @XmlEnumValue("IT-RO")
    IT_RO("IT-RO"),
    @XmlEnumValue("IT-SA")
    IT_SA("IT-SA"),
    @XmlEnumValue("IT-SS")
    IT_SS("IT-SS"),
    @XmlEnumValue("IT-SV")
    IT_SV("IT-SV"),
    @XmlEnumValue("IT-SI")
    IT_SI("IT-SI"),
    @XmlEnumValue("IT-SR")
    IT_SR("IT-SR"),
    @XmlEnumValue("IT-SO")
    IT_SO("IT-SO"),
    @XmlEnumValue("IT-TA")
    IT_TA("IT-TA"),
    @XmlEnumValue("IT-TE")
    IT_TE("IT-TE"),
    @XmlEnumValue("IT-TR")
    IT_TR("IT-TR"),
    @XmlEnumValue("IT-TO")
    IT_TO("IT-TO"),
    @XmlEnumValue("IT-TP")
    IT_TP("IT-TP"),
    @XmlEnumValue("IT-TN")
    IT_TN("IT-TN"),
    @XmlEnumValue("IT-TV")
    IT_TV("IT-TV"),
    @XmlEnumValue("IT-TS")
    IT_TS("IT-TS"),
    @XmlEnumValue("IT-UD")
    IT_UD("IT-UD"),
    @XmlEnumValue("IT-VA")
    IT_VA("IT-VA"),
    @XmlEnumValue("IT-VE")
    IT_VE("IT-VE"),
    @XmlEnumValue("IT-VB")
    IT_VB("IT-VB"),
    @XmlEnumValue("IT-VC")
    IT_VC("IT-VC"),
    @XmlEnumValue("IT-VR")
    IT_VR("IT-VR"),
    @XmlEnumValue("IT-VV")
    IT_VV("IT-VV"),
    @XmlEnumValue("IT-VI")
    IT_VI("IT-VI"),
    @XmlEnumValue("IT-VT")
    IT_VT("IT-VT"),
    @XmlEnumValue("RS-KM")
    RS_KM("RS-KM"),
    @XmlEnumValue("RS-VO")
    RS_VO("RS-VO"),
    @XmlEnumValue("RU-AD")
    RU_AD("RU-AD"),
    @XmlEnumValue("RU-AL")
    RU_AL("RU-AL"),
    @XmlEnumValue("RU-BA")
    RU_BA("RU-BA"),
    @XmlEnumValue("RU-BU")
    RU_BU("RU-BU"),
    @XmlEnumValue("RU-CE")
    RU_CE("RU-CE"),
    @XmlEnumValue("RU-CU")
    RU_CU("RU-CU"),
    @XmlEnumValue("RU-DA")
    RU_DA("RU-DA"),
    @XmlEnumValue("RU-IN")
    RU_IN("RU-IN"),
    @XmlEnumValue("RU-KB")
    RU_KB("RU-KB"),
    @XmlEnumValue("RU-KL")
    RU_KL("RU-KL"),
    @XmlEnumValue("RU-KC")
    RU_KC("RU-KC"),
    @XmlEnumValue("RU-KR")
    RU_KR("RU-KR"),
    @XmlEnumValue("RU-KK")
    RU_KK("RU-KK"),
    @XmlEnumValue("RU-KO")
    RU_KO("RU-KO"),
    @XmlEnumValue("RU-ME")
    RU_ME("RU-ME"),
    @XmlEnumValue("RU-MO")
    RU_MO("RU-MO"),
    @XmlEnumValue("RU-SA")
    RU_SA("RU-SA"),
    @XmlEnumValue("RU-SE")
    RU_SE("RU-SE"),
    @XmlEnumValue("RU-TA")
    RU_TA("RU-TA"),
    @XmlEnumValue("RU-TY")
    RU_TY("RU-TY"),
    @XmlEnumValue("RU-UD")
    RU_UD("RU-UD"),
    @XmlEnumValue("RU-ALT")
    RU_ALT("RU-ALT"),
    @XmlEnumValue("RU-KAM")
    RU_KAM("RU-KAM"),
    @XmlEnumValue("RU-KHA")
    RU_KHA("RU-KHA"),
    @XmlEnumValue("RU-KDA")
    RU_KDA("RU-KDA"),
    @XmlEnumValue("RU-KYA")
    RU_KYA("RU-KYA"),
    @XmlEnumValue("RU-PER")
    RU_PER("RU-PER"),
    @XmlEnumValue("RU-PRI")
    RU_PRI("RU-PRI"),
    @XmlEnumValue("RU-STA")
    RU_STA("RU-STA"),
    @XmlEnumValue("RU-ZAB")
    RU_ZAB("RU-ZAB"),
    @XmlEnumValue("RU-AMU")
    RU_AMU("RU-AMU"),
    @XmlEnumValue("RU-ARK")
    RU_ARK("RU-ARK"),
    @XmlEnumValue("RU-AST")
    RU_AST("RU-AST"),
    @XmlEnumValue("RU-BEL")
    RU_BEL("RU-BEL"),
    @XmlEnumValue("RU-BRY")
    RU_BRY("RU-BRY"),
    @XmlEnumValue("RU-CHE")
    RU_CHE("RU-CHE"),
    @XmlEnumValue("RU-IRK")
    RU_IRK("RU-IRK"),
    @XmlEnumValue("RU-IVA")
    RU_IVA("RU-IVA"),
    @XmlEnumValue("RU-KGD")
    RU_KGD("RU-KGD"),
    @XmlEnumValue("RU-KLU")
    RU_KLU("RU-KLU"),
    @XmlEnumValue("RU-KEM")
    RU_KEM("RU-KEM"),
    @XmlEnumValue("RU-KIR")
    RU_KIR("RU-KIR"),
    @XmlEnumValue("RU-KOS")
    RU_KOS("RU-KOS"),
    @XmlEnumValue("RU-KGN")
    RU_KGN("RU-KGN"),
    @XmlEnumValue("RU-KRS")
    RU_KRS("RU-KRS"),
    @XmlEnumValue("RU-LEN")
    RU_LEN("RU-LEN"),
    @XmlEnumValue("RU-LIP")
    RU_LIP("RU-LIP"),
    @XmlEnumValue("RU-MAG")
    RU_MAG("RU-MAG"),
    @XmlEnumValue("RU-MOS")
    RU_MOS("RU-MOS"),
    @XmlEnumValue("RU-MUR")
    RU_MUR("RU-MUR"),
    @XmlEnumValue("RU-NIZ")
    RU_NIZ("RU-NIZ"),
    @XmlEnumValue("RU-NGR")
    RU_NGR("RU-NGR"),
    @XmlEnumValue("RU-NVS")
    RU_NVS("RU-NVS"),
    @XmlEnumValue("RU-OMS")
    RU_OMS("RU-OMS"),
    @XmlEnumValue("RU-ORE")
    RU_ORE("RU-ORE"),
    @XmlEnumValue("RU-ORL")
    RU_ORL("RU-ORL"),
    @XmlEnumValue("RU-PNZ")
    RU_PNZ("RU-PNZ"),
    @XmlEnumValue("RU-PSK")
    RU_PSK("RU-PSK"),
    @XmlEnumValue("RU-ROS")
    RU_ROS("RU-ROS"),
    @XmlEnumValue("RU-RYA")
    RU_RYA("RU-RYA"),
    @XmlEnumValue("RU-SAK")
    RU_SAK("RU-SAK"),
    @XmlEnumValue("RU-SAM")
    RU_SAM("RU-SAM"),
    @XmlEnumValue("RU-SAR")
    RU_SAR("RU-SAR"),
    @XmlEnumValue("RU-SMO")
    RU_SMO("RU-SMO"),
    @XmlEnumValue("RU-SVE")
    RU_SVE("RU-SVE"),
    @XmlEnumValue("RU-TAM")
    RU_TAM("RU-TAM"),
    @XmlEnumValue("RU-TOM")
    RU_TOM("RU-TOM"),
    @XmlEnumValue("RU-TUL")
    RU_TUL("RU-TUL"),
    @XmlEnumValue("RU-TVE")
    RU_TVE("RU-TVE"),
    @XmlEnumValue("RU-TYU")
    RU_TYU("RU-TYU"),
    @XmlEnumValue("RU-ULY")
    RU_ULY("RU-ULY"),
    @XmlEnumValue("RU-VLA")
    RU_VLA("RU-VLA"),
    @XmlEnumValue("RU-VGG")
    RU_VGG("RU-VGG"),
    @XmlEnumValue("RU-VLG")
    RU_VLG("RU-VLG"),
    @XmlEnumValue("RU-VOR")
    RU_VOR("RU-VOR"),
    @XmlEnumValue("RU-YAR")
    RU_YAR("RU-YAR"),
    @XmlEnumValue("RU-MOW")
    RU_MOW("RU-MOW"),
    @XmlEnumValue("RU-SPE")
    RU_SPE("RU-SPE"),
    @XmlEnumValue("RU-YEV")
    RU_YEV("RU-YEV"),
    @XmlEnumValue("RU-CHU")
    RU_CHU("RU-CHU"),
    @XmlEnumValue("RU-KHM")
    RU_KHM("RU-KHM"),
    @XmlEnumValue("RU-NEN")
    RU_NEN("RU-NEN"),
    @XmlEnumValue("RU-YAN")
    RU_YAN("RU-YAN"),
    @XmlEnumValue("US-AK")
    US_AK("US-AK"),
    @XmlEnumValue("US-AL")
    US_AL("US-AL"),
    @XmlEnumValue("US-AR")
    US_AR("US-AR"),
    @XmlEnumValue("US-AZ")
    US_AZ("US-AZ"),
    @XmlEnumValue("US-CA")
    US_CA("US-CA"),
    @XmlEnumValue("US-CO")
    US_CO("US-CO"),
    @XmlEnumValue("US-CT")
    US_CT("US-CT"),
    @XmlEnumValue("US-DC")
    US_DC("US-DC"),
    @XmlEnumValue("US-DE")
    US_DE("US-DE"),
    @XmlEnumValue("US-FL")
    US_FL("US-FL"),
    @XmlEnumValue("US-GA")
    US_GA("US-GA"),
    @XmlEnumValue("US-HI")
    US_HI("US-HI"),
    @XmlEnumValue("US-IA")
    US_IA("US-IA"),
    @XmlEnumValue("US-ID")
    US_ID("US-ID"),
    @XmlEnumValue("US-IL")
    US_IL("US-IL"),
    @XmlEnumValue("US-IN")
    US_IN("US-IN"),
    @XmlEnumValue("US-KS")
    US_KS("US-KS"),
    @XmlEnumValue("US-KY")
    US_KY("US-KY"),
    @XmlEnumValue("US-LA")
    US_LA("US-LA"),
    @XmlEnumValue("US-MA")
    US_MA("US-MA"),
    @XmlEnumValue("US-MD")
    US_MD("US-MD"),
    @XmlEnumValue("US-ME")
    US_ME("US-ME"),
    @XmlEnumValue("US-MI")
    US_MI("US-MI"),
    @XmlEnumValue("US-MN")
    US_MN("US-MN"),
    @XmlEnumValue("US-MO")
    US_MO("US-MO"),
    @XmlEnumValue("US-MS")
    US_MS("US-MS"),
    @XmlEnumValue("US-MT")
    US_MT("US-MT"),
    @XmlEnumValue("US-NC")
    US_NC("US-NC"),
    @XmlEnumValue("US-ND")
    US_ND("US-ND"),
    @XmlEnumValue("US-NE")
    US_NE("US-NE"),
    @XmlEnumValue("US-NH")
    US_NH("US-NH"),
    @XmlEnumValue("US-NJ")
    US_NJ("US-NJ"),
    @XmlEnumValue("US-NM")
    US_NM("US-NM"),
    @XmlEnumValue("US-NV")
    US_NV("US-NV"),
    @XmlEnumValue("US-NY")
    US_NY("US-NY"),
    @XmlEnumValue("US-OH")
    US_OH("US-OH"),
    @XmlEnumValue("US-OK")
    US_OK("US-OK"),
    @XmlEnumValue("US-OR")
    US_OR("US-OR"),
    @XmlEnumValue("US-PA")
    US_PA("US-PA"),
    @XmlEnumValue("US-RI")
    US_RI("US-RI"),
    @XmlEnumValue("US-SC")
    US_SC("US-SC"),
    @XmlEnumValue("US-SD")
    US_SD("US-SD"),
    @XmlEnumValue("US-TN")
    US_TN("US-TN"),
    @XmlEnumValue("US-TX")
    US_TX("US-TX"),
    @XmlEnumValue("US-UT")
    US_UT("US-UT"),
    @XmlEnumValue("US-VA")
    US_VA("US-VA"),
    @XmlEnumValue("US-VT")
    US_VT("US-VT"),
    @XmlEnumValue("US-WA")
    US_WA("US-WA"),
    @XmlEnumValue("US-WI")
    US_WI("US-WI"),
    @XmlEnumValue("US-WV")
    US_WV("US-WV"),
    @XmlEnumValue("US-WY")
    US_WY("US-WY"),

    /**
     * Countries geographically within continental Europe which use the Euro as their sole currency. At the time of writing, this is a synonym for ‘AT BE CY EE FI FR DE ES GR HR IE IT LT LU LV MT NL PT SI SK’ (the official Eurozone 20), plus ‘AD MC SM VA ME’ and Kosovo (other Euro-using countries in continental Europe). Note some other territories using the Euro, but outside continental Europe are excluded from this list, and may need to be specified separately. ONLY valid in ONIX 3.0, and ONLY within P.26 – and this use is itself Deprecated. Use of an explicit list of countries instead of ECZ is strongly encouraged
     * 
     */
    ECZ("ECZ"),

    /**
     * In ONIX 3.0 and later, may ONLY be used in <RegionsIncluded>
     * 
     */
    WORLD("WORLD");
    private final String value;

    List49(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List49 fromValue(String v) {
        for (List49 c: List49 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
