//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.27 at 10:08:36 AM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List87.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List87"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CCL"/&gt;
 *     &lt;enumeration value="PGE"/&gt;
 *     &lt;enumeration value="SID"/&gt;
 *     &lt;enumeration value="VER"/&gt;
 *     &lt;enumeration value="UNK"/&gt;
 *     &lt;enumeration value="ZZZ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List87")
@XmlEnum
public enum List87 {


    /**
     * References are printed in a narrow column in the center of the page between two columns of text
     * 
     */
    CCL,

    /**
     * References are printed at the foot of the page
     * 
     */
    PGE,

    /**
     * References are printed in a column to the side of the scripture
     * 
     */
    SID,

    /**
     * References are printed at the end of the applicable verse
     * 
     */
    VER,

    /**
     * The person creating the ONIX record does not know where the references are located
     * 
     */
    UNK,

    /**
     * Other locations not otherwise identified
     * 
     */
    ZZZ;

    public String value() {
        return name();
    }

    public static List87 fromValue(String v) {
        return valueOf(v);
    }

}
