//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.27 at 11:32:06 AM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List74.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List74"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="abk"/&gt;
 *     &lt;enumeration value="ace"/&gt;
 *     &lt;enumeration value="ach"/&gt;
 *     &lt;enumeration value="ada"/&gt;
 *     &lt;enumeration value="ady"/&gt;
 *     &lt;enumeration value="aar"/&gt;
 *     &lt;enumeration value="afh"/&gt;
 *     &lt;enumeration value="afr"/&gt;
 *     &lt;enumeration value="afa"/&gt;
 *     &lt;enumeration value="ain"/&gt;
 *     &lt;enumeration value="aka"/&gt;
 *     &lt;enumeration value="akk"/&gt;
 *     &lt;enumeration value="alb"/&gt;
 *     &lt;enumeration value="ale"/&gt;
 *     &lt;enumeration value="alg"/&gt;
 *     &lt;enumeration value="alq"/&gt;
 *     &lt;enumeration value="tut"/&gt;
 *     &lt;enumeration value="amh"/&gt;
 *     &lt;enumeration value="anp"/&gt;
 *     &lt;enumeration value="apa"/&gt;
 *     &lt;enumeration value="ara"/&gt;
 *     &lt;enumeration value="arg"/&gt;
 *     &lt;enumeration value="qar"/&gt;
 *     &lt;enumeration value="arp"/&gt;
 *     &lt;enumeration value="arw"/&gt;
 *     &lt;enumeration value="arm"/&gt;
 *     &lt;enumeration value="rup"/&gt;
 *     &lt;enumeration value="art"/&gt;
 *     &lt;enumeration value="asm"/&gt;
 *     &lt;enumeration value="ast"/&gt;
 *     &lt;enumeration value="ath"/&gt;
 *     &lt;enumeration value="atj"/&gt;
 *     &lt;enumeration value="aus"/&gt;
 *     &lt;enumeration value="aav"/&gt;
 *     &lt;enumeration value="map"/&gt;
 *     &lt;enumeration value="ava"/&gt;
 *     &lt;enumeration value="ave"/&gt;
 *     &lt;enumeration value="awa"/&gt;
 *     &lt;enumeration value="aym"/&gt;
 *     &lt;enumeration value="aze"/&gt;
 *     &lt;enumeration value="ban"/&gt;
 *     &lt;enumeration value="bat"/&gt;
 *     &lt;enumeration value="bal"/&gt;
 *     &lt;enumeration value="bam"/&gt;
 *     &lt;enumeration value="bai"/&gt;
 *     &lt;enumeration value="bad"/&gt;
 *     &lt;enumeration value="bnt"/&gt;
 *     &lt;enumeration value="bas"/&gt;
 *     &lt;enumeration value="bak"/&gt;
 *     &lt;enumeration value="baq"/&gt;
 *     &lt;enumeration value="btk"/&gt;
 *     &lt;enumeration value="bej"/&gt;
 *     &lt;enumeration value="bel"/&gt;
 *     &lt;enumeration value="bem"/&gt;
 *     &lt;enumeration value="ben"/&gt;
 *     &lt;enumeration value="ber"/&gt;
 *     &lt;enumeration value="bho"/&gt;
 *     &lt;enumeration value="bih"/&gt;
 *     &lt;enumeration value="bik"/&gt;
 *     &lt;enumeration value="bin"/&gt;
 *     &lt;enumeration value="bis"/&gt;
 *     &lt;enumeration value="byn"/&gt;
 *     &lt;enumeration value="zbl"/&gt;
 *     &lt;enumeration value="brx"/&gt;
 *     &lt;enumeration value="bos"/&gt;
 *     &lt;enumeration value="bra"/&gt;
 *     &lt;enumeration value="bre"/&gt;
 *     &lt;enumeration value="bug"/&gt;
 *     &lt;enumeration value="bul"/&gt;
 *     &lt;enumeration value="bum"/&gt;
 *     &lt;enumeration value="bua"/&gt;
 *     &lt;enumeration value="bur"/&gt;
 *     &lt;enumeration value="cad"/&gt;
 *     &lt;enumeration value="sro"/&gt;
 *     &lt;enumeration value="yue"/&gt;
 *     &lt;enumeration value="cat"/&gt;
 *     &lt;enumeration value="cau"/&gt;
 *     &lt;enumeration value="cay"/&gt;
 *     &lt;enumeration value="ceb"/&gt;
 *     &lt;enumeration value="cel"/&gt;
 *     &lt;enumeration value="cai"/&gt;
 *     &lt;enumeration value="tzm"/&gt;
 *     &lt;enumeration value="khm"/&gt;
 *     &lt;enumeration value="ckb"/&gt;
 *     &lt;enumeration value="chg"/&gt;
 *     &lt;enumeration value="cmc"/&gt;
 *     &lt;enumeration value="cha"/&gt;
 *     &lt;enumeration value="che"/&gt;
 *     &lt;enumeration value="chr"/&gt;
 *     &lt;enumeration value="chy"/&gt;
 *     &lt;enumeration value="chb"/&gt;
 *     &lt;enumeration value="nya"/&gt;
 *     &lt;enumeration value="cic"/&gt;
 *     &lt;enumeration value="chi"/&gt;
 *     &lt;enumeration value="chn"/&gt;
 *     &lt;enumeration value="chp"/&gt;
 *     &lt;enumeration value="cho"/&gt;
 *     &lt;enumeration value="chu"/&gt;
 *     &lt;enumeration value="chk"/&gt;
 *     &lt;enumeration value="chv"/&gt;
 *     &lt;enumeration value="nwc"/&gt;
 *     &lt;enumeration value="syc"/&gt;
 *     &lt;enumeration value="cop"/&gt;
 *     &lt;enumeration value="cor"/&gt;
 *     &lt;enumeration value="cos"/&gt;
 *     &lt;enumeration value="cre"/&gt;
 *     &lt;enumeration value="mus"/&gt;
 *     &lt;enumeration value="crp"/&gt;
 *     &lt;enumeration value="cpe"/&gt;
 *     &lt;enumeration value="cpf"/&gt;
 *     &lt;enumeration value="cpp"/&gt;
 *     &lt;enumeration value="crh"/&gt;
 *     &lt;enumeration value="hrv"/&gt;
 *     &lt;enumeration value="scr"/&gt;
 *     &lt;enumeration value="cus"/&gt;
 *     &lt;enumeration value="cze"/&gt;
 *     &lt;enumeration value="dak"/&gt;
 *     &lt;enumeration value="dan"/&gt;
 *     &lt;enumeration value="dar"/&gt;
 *     &lt;enumeration value="prs"/&gt;
 *     &lt;enumeration value="del"/&gt;
 *     &lt;enumeration value="din"/&gt;
 *     &lt;enumeration value="div"/&gt;
 *     &lt;enumeration value="doi"/&gt;
 *     &lt;enumeration value="dgr"/&gt;
 *     &lt;enumeration value="dra"/&gt;
 *     &lt;enumeration value="dua"/&gt;
 *     &lt;enumeration value="dum"/&gt;
 *     &lt;enumeration value="dut"/&gt;
 *     &lt;enumeration value="dyu"/&gt;
 *     &lt;enumeration value="dzo"/&gt;
 *     &lt;enumeration value="ike"/&gt;
 *     &lt;enumeration value="frs"/&gt;
 *     &lt;enumeration value="efi"/&gt;
 *     &lt;enumeration value="egy"/&gt;
 *     &lt;enumeration value="eka"/&gt;
 *     &lt;enumeration value="elx"/&gt;
 *     &lt;enumeration value="egl"/&gt;
 *     &lt;enumeration value="eng"/&gt;
 *     &lt;enumeration value="enm"/&gt;
 *     &lt;enumeration value="ang"/&gt;
 *     &lt;enumeration value="myv"/&gt;
 *     &lt;enumeration value="esx"/&gt;
 *     &lt;enumeration value="epo"/&gt;
 *     &lt;enumeration value="est"/&gt;
 *     &lt;enumeration value="gez"/&gt;
 *     &lt;enumeration value="ewe"/&gt;
 *     &lt;enumeration value="ewo"/&gt;
 *     &lt;enumeration value="fan"/&gt;
 *     &lt;enumeration value="fat"/&gt;
 *     &lt;enumeration value="fao"/&gt;
 *     &lt;enumeration value="fij"/&gt;
 *     &lt;enumeration value="fil"/&gt;
 *     &lt;enumeration value="fin"/&gt;
 *     &lt;enumeration value="fiu"/&gt;
 *     &lt;enumeration value="fon"/&gt;
 *     &lt;enumeration value="fre"/&gt;
 *     &lt;enumeration value="frm"/&gt;
 *     &lt;enumeration value="fro"/&gt;
 *     &lt;enumeration value="fur"/&gt;
 *     &lt;enumeration value="ful"/&gt;
 *     &lt;enumeration value="gaa"/&gt;
 *     &lt;enumeration value="car"/&gt;
 *     &lt;enumeration value="glg"/&gt;
 *     &lt;enumeration value="qgl"/&gt;
 *     &lt;enumeration value="sdn"/&gt;
 *     &lt;enumeration value="lug"/&gt;
 *     &lt;enumeration value="grt"/&gt;
 *     &lt;enumeration value="gay"/&gt;
 *     &lt;enumeration value="gba"/&gt;
 *     &lt;enumeration value="geo"/&gt;
 *     &lt;enumeration value="ger"/&gt;
 *     &lt;enumeration value="gmh"/&gt;
 *     &lt;enumeration value="goh"/&gt;
 *     &lt;enumeration value="gem"/&gt;
 *     &lt;enumeration value="gil"/&gt;
 *     &lt;enumeration value="git"/&gt;
 *     &lt;enumeration value="gon"/&gt;
 *     &lt;enumeration value="gor"/&gt;
 *     &lt;enumeration value="got"/&gt;
 *     &lt;enumeration value="grb"/&gt;
 *     &lt;enumeration value="grc"/&gt;
 *     &lt;enumeration value="gre"/&gt;
 *     &lt;enumeration value="grn"/&gt;
 *     &lt;enumeration value="nrf"/&gt;
 *     &lt;enumeration value="guj"/&gt;
 *     &lt;enumeration value="gwi"/&gt;
 *     &lt;enumeration value="hai"/&gt;
 *     &lt;enumeration value="hat"/&gt;
 *     &lt;enumeration value="hau"/&gt;
 *     &lt;enumeration value="haw"/&gt;
 *     &lt;enumeration value="heb"/&gt;
 *     &lt;enumeration value="her"/&gt;
 *     &lt;enumeration value="hil"/&gt;
 *     &lt;enumeration value="him"/&gt;
 *     &lt;enumeration value="hin"/&gt;
 *     &lt;enumeration value="hmo"/&gt;
 *     &lt;enumeration value="hit"/&gt;
 *     &lt;enumeration value="hmx"/&gt;
 *     &lt;enumeration value="hmn"/&gt;
 *     &lt;enumeration value="hop"/&gt;
 *     &lt;enumeration value="hun"/&gt;
 *     &lt;enumeration value="hup"/&gt;
 *     &lt;enumeration value="iba"/&gt;
 *     &lt;enumeration value="ice"/&gt;
 *     &lt;enumeration value="ido"/&gt;
 *     &lt;enumeration value="ibo"/&gt;
 *     &lt;enumeration value="ijo"/&gt;
 *     &lt;enumeration value="ilo"/&gt;
 *     &lt;enumeration value="smn"/&gt;
 *     &lt;enumeration value="inc"/&gt;
 *     &lt;enumeration value="ine"/&gt;
 *     &lt;enumeration value="ind"/&gt;
 *     &lt;enumeration value="inh"/&gt;
 *     &lt;enumeration value="moe"/&gt;
 *     &lt;enumeration value="ina"/&gt;
 *     &lt;enumeration value="ile"/&gt;
 *     &lt;enumeration value="ikt"/&gt;
 *     &lt;enumeration value="iku"/&gt;
 *     &lt;enumeration value="ipk"/&gt;
 *     &lt;enumeration value="qiv"/&gt;
 *     &lt;enumeration value="ira"/&gt;
 *     &lt;enumeration value="pes"/&gt;
 *     &lt;enumeration value="gle"/&gt;
 *     &lt;enumeration value="mga"/&gt;
 *     &lt;enumeration value="sga"/&gt;
 *     &lt;enumeration value="iro"/&gt;
 *     &lt;enumeration value="ita"/&gt;
 *     &lt;enumeration value="jpn"/&gt;
 *     &lt;enumeration value="jpx"/&gt;
 *     &lt;enumeration value="jav"/&gt;
 *     &lt;enumeration value="jow"/&gt;
 *     &lt;enumeration value="jrb"/&gt;
 *     &lt;enumeration value="jpr"/&gt;
 *     &lt;enumeration value="kbd"/&gt;
 *     &lt;enumeration value="kbp"/&gt;
 *     &lt;enumeration value="kab"/&gt;
 *     &lt;enumeration value="kac"/&gt;
 *     &lt;enumeration value="kal"/&gt;
 *     &lt;enumeration value="xal"/&gt;
 *     &lt;enumeration value="kam"/&gt;
 *     &lt;enumeration value="kan"/&gt;
 *     &lt;enumeration value="kau"/&gt;
 *     &lt;enumeration value="kaa"/&gt;
 *     &lt;enumeration value="krc"/&gt;
 *     &lt;enumeration value="kdr"/&gt;
 *     &lt;enumeration value="krl"/&gt;
 *     &lt;enumeration value="kar"/&gt;
 *     &lt;enumeration value="kas"/&gt;
 *     &lt;enumeration value="csb"/&gt;
 *     &lt;enumeration value="kaw"/&gt;
 *     &lt;enumeration value="kaz"/&gt;
 *     &lt;enumeration value="kha"/&gt;
 *     &lt;enumeration value="khi"/&gt;
 *     &lt;enumeration value="kho"/&gt;
 *     &lt;enumeration value="xuu"/&gt;
 *     &lt;enumeration value="kik"/&gt;
 *     &lt;enumeration value="kmb"/&gt;
 *     &lt;enumeration value="kin"/&gt;
 *     &lt;enumeration value="kir"/&gt;
 *     &lt;enumeration value="kqs"/&gt;
 *     &lt;enumeration value="kss"/&gt;
 *     &lt;enumeration value="tlh"/&gt;
 *     &lt;enumeration value="kom"/&gt;
 *     &lt;enumeration value="kon"/&gt;
 *     &lt;enumeration value="kok"/&gt;
 *     &lt;enumeration value="kor"/&gt;
 *     &lt;enumeration value="kpe"/&gt;
 *     &lt;enumeration value="kro"/&gt;
 *     &lt;enumeration value="kua"/&gt;
 *     &lt;enumeration value="kum"/&gt;
 *     &lt;enumeration value="kur"/&gt;
 *     &lt;enumeration value="kru"/&gt;
 *     &lt;enumeration value="kos"/&gt;
 *     &lt;enumeration value="kut"/&gt;
 *     &lt;enumeration value="fkv"/&gt;
 *     &lt;enumeration value="kwk"/&gt;
 *     &lt;enumeration value="lad"/&gt;
 *     &lt;enumeration value="lah"/&gt;
 *     &lt;enumeration value="lkt"/&gt;
 *     &lt;enumeration value="lam"/&gt;
 *     &lt;enumeration value="day"/&gt;
 *     &lt;enumeration value="lao"/&gt;
 *     &lt;enumeration value="lat"/&gt;
 *     &lt;enumeration value="lav"/&gt;
 *     &lt;enumeration value="qlk"/&gt;
 *     &lt;enumeration value="lez"/&gt;
 *     &lt;enumeration value="lij"/&gt;
 *     &lt;enumeration value="lim"/&gt;
 *     &lt;enumeration value="lin"/&gt;
 *     &lt;enumeration value="lit"/&gt;
 *     &lt;enumeration value="jbo"/&gt;
 *     &lt;enumeration value="lom"/&gt;
 *     &lt;enumeration value="lmo"/&gt;
 *     &lt;enumeration value="nds"/&gt;
 *     &lt;enumeration value="dsb"/&gt;
 *     &lt;enumeration value="loz"/&gt;
 *     &lt;enumeration value="lub"/&gt;
 *     &lt;enumeration value="lua"/&gt;
 *     &lt;enumeration value="lui"/&gt;
 *     &lt;enumeration value="smj"/&gt;
 *     &lt;enumeration value="lun"/&gt;
 *     &lt;enumeration value="luo"/&gt;
 *     &lt;enumeration value="lus"/&gt;
 *     &lt;enumeration value="ltz"/&gt;
 *     &lt;enumeration value="mac"/&gt;
 *     &lt;enumeration value="mad"/&gt;
 *     &lt;enumeration value="mag"/&gt;
 *     &lt;enumeration value="mai"/&gt;
 *     &lt;enumeration value="mak"/&gt;
 *     &lt;enumeration value="mlg"/&gt;
 *     &lt;enumeration value="may"/&gt;
 *     &lt;enumeration value="mal"/&gt;
 *     &lt;enumeration value="poz"/&gt;
 *     &lt;enumeration value="mlt"/&gt;
 *     &lt;enumeration value="mnc"/&gt;
 *     &lt;enumeration value="mdr"/&gt;
 *     &lt;enumeration value="cmn"/&gt;
 *     &lt;enumeration value="man"/&gt;
 *     &lt;enumeration value="mni"/&gt;
 *     &lt;enumeration value="mno"/&gt;
 *     &lt;enumeration value="glv"/&gt;
 *     &lt;enumeration value="swb"/&gt;
 *     &lt;enumeration value="mao"/&gt;
 *     &lt;enumeration value="arn"/&gt;
 *     &lt;enumeration value="mar"/&gt;
 *     &lt;enumeration value="chm"/&gt;
 *     &lt;enumeration value="mah"/&gt;
 *     &lt;enumeration value="mwr"/&gt;
 *     &lt;enumeration value="mas"/&gt;
 *     &lt;enumeration value="myn"/&gt;
 *     &lt;enumeration value="fit"/&gt;
 *     &lt;enumeration value="men"/&gt;
 *     &lt;enumeration value="mic"/&gt;
 *     &lt;enumeration value="crg"/&gt;
 *     &lt;enumeration value="gml"/&gt;
 *     &lt;enumeration value="min"/&gt;
 *     &lt;enumeration value="mwl"/&gt;
 *     &lt;enumeration value="moh"/&gt;
 *     &lt;enumeration value="mdf"/&gt;
 *     &lt;enumeration value="mol"/&gt;
 *     &lt;enumeration value="mkh"/&gt;
 *     &lt;enumeration value="lol"/&gt;
 *     &lt;enumeration value="mon"/&gt;
 *     &lt;enumeration value="cnr"/&gt;
 *     &lt;enumeration value="mos"/&gt;
 *     &lt;enumeration value="crm"/&gt;
 *     &lt;enumeration value="mun"/&gt;
 *     &lt;enumeration value="mwf"/&gt;
 *     &lt;enumeration value="nqo"/&gt;
 *     &lt;enumeration value="nah"/&gt;
 *     &lt;enumeration value="nsk"/&gt;
 *     &lt;enumeration value="nau"/&gt;
 *     &lt;enumeration value="nav"/&gt;
 *     &lt;enumeration value="nde"/&gt;
 *     &lt;enumeration value="nbl"/&gt;
 *     &lt;enumeration value="ndo"/&gt;
 *     &lt;enumeration value="nap"/&gt;
 *     &lt;enumeration value="nep"/&gt;
 *     &lt;enumeration value="qls"/&gt;
 *     &lt;enumeration value="new"/&gt;
 *     &lt;enumeration value="nia"/&gt;
 *     &lt;enumeration value="nic"/&gt;
 *     &lt;enumeration value="ssa"/&gt;
 *     &lt;enumeration value="niu"/&gt;
 *     &lt;enumeration value="nog"/&gt;
 *     &lt;enumeration value="qnf"/&gt;
 *     &lt;enumeration value="nai"/&gt;
 *     &lt;enumeration value="crl"/&gt;
 *     &lt;enumeration value="frr"/&gt;
 *     &lt;enumeration value="sme"/&gt;
 *     &lt;enumeration value="nor"/&gt;
 *     &lt;enumeration value="nob"/&gt;
 *     &lt;enumeration value="nno"/&gt;
 *     &lt;enumeration value="nub"/&gt;
 *     &lt;enumeration value="nym"/&gt;
 *     &lt;enumeration value="nyn"/&gt;
 *     &lt;enumeration value="nyo"/&gt;
 *     &lt;enumeration value="nzi"/&gt;
 *     &lt;enumeration value="oci"/&gt;
 *     &lt;enumeration value="arc"/&gt;
 *     &lt;enumeration value="oji"/&gt;
 *     &lt;enumeration value="oka"/&gt;
 *     &lt;enumeration value="odt"/&gt;
 *     &lt;enumeration value="non"/&gt;
 *     &lt;enumeration value="peo"/&gt;
 *     &lt;enumeration value="ori"/&gt;
 *     &lt;enumeration value="orm"/&gt;
 *     &lt;enumeration value="osa"/&gt;
 *     &lt;enumeration value="oss"/&gt;
 *     &lt;enumeration value="omq"/&gt;
 *     &lt;enumeration value="oto"/&gt;
 *     &lt;enumeration value="pal"/&gt;
 *     &lt;enumeration value="pau"/&gt;
 *     &lt;enumeration value="pli"/&gt;
 *     &lt;enumeration value="pam"/&gt;
 *     &lt;enumeration value="pag"/&gt;
 *     &lt;enumeration value="pan"/&gt;
 *     &lt;enumeration value="pap"/&gt;
 *     &lt;enumeration value="paa"/&gt;
 *     &lt;enumeration value="nso"/&gt;
 *     &lt;enumeration value="per"/&gt;
 *     &lt;enumeration value="phi"/&gt;
 *     &lt;enumeration value="phn"/&gt;
 *     &lt;enumeration value="pcd"/&gt;
 *     &lt;enumeration value="qsp"/&gt;
 *     &lt;enumeration value="pms"/&gt;
 *     &lt;enumeration value="crk"/&gt;
 *     &lt;enumeration value="pol"/&gt;
 *     &lt;enumeration value="pon"/&gt;
 *     &lt;enumeration value="por"/&gt;
 *     &lt;enumeration value="pra"/&gt;
 *     &lt;enumeration value="pro"/&gt;
 *     &lt;enumeration value="fuf"/&gt;
 *     &lt;enumeration value="pus"/&gt;
 *     &lt;enumeration value="que"/&gt;
 *     &lt;enumeration value="raj"/&gt;
 *     &lt;enumeration value="rap"/&gt;
 *     &lt;enumeration value="rar"/&gt;
 *     &lt;enumeration value="rcf"/&gt;
 *     &lt;enumeration value="rgn"/&gt;
 *     &lt;enumeration value="roa"/&gt;
 *     &lt;enumeration value="rum"/&gt;
 *     &lt;enumeration value="roh"/&gt;
 *     &lt;enumeration value="rom"/&gt;
 *     &lt;enumeration value="run"/&gt;
 *     &lt;enumeration value="rus"/&gt;
 *     &lt;enumeration value="sal"/&gt;
 *     &lt;enumeration value="sam"/&gt;
 *     &lt;enumeration value="smi"/&gt;
 *     &lt;enumeration value="smo"/&gt;
 *     &lt;enumeration value="sad"/&gt;
 *     &lt;enumeration value="sag"/&gt;
 *     &lt;enumeration value="san"/&gt;
 *     &lt;enumeration value="sat"/&gt;
 *     &lt;enumeration value="srm"/&gt;
 *     &lt;enumeration value="srd"/&gt;
 *     &lt;enumeration value="sas"/&gt;
 *     &lt;enumeration value="sdc"/&gt;
 *     &lt;enumeration value="sco"/&gt;
 *     &lt;enumeration value="gla"/&gt;
 *     &lt;enumeration value="sel"/&gt;
 *     &lt;enumeration value="sem"/&gt;
 *     &lt;enumeration value="scc"/&gt;
 *     &lt;enumeration value="srp"/&gt;
 *     &lt;enumeration value="srr"/&gt;
 *     &lt;enumeration value="ojs"/&gt;
 *     &lt;enumeration value="shn"/&gt;
 *     &lt;enumeration value="sna"/&gt;
 *     &lt;enumeration value="shs"/&gt;
 *     &lt;enumeration value="iii"/&gt;
 *     &lt;enumeration value="scn"/&gt;
 *     &lt;enumeration value="sid"/&gt;
 *     &lt;enumeration value="sgn"/&gt;
 *     &lt;enumeration value="bla"/&gt;
 *     &lt;enumeration value="szl"/&gt;
 *     &lt;enumeration value="snd"/&gt;
 *     &lt;enumeration value="sin"/&gt;
 *     &lt;enumeration value="zhx"/&gt;
 *     &lt;enumeration value="sit"/&gt;
 *     &lt;enumeration value="sio"/&gt;
 *     &lt;enumeration value="sms"/&gt;
 *     &lt;enumeration value="den"/&gt;
 *     &lt;enumeration value="sla"/&gt;
 *     &lt;enumeration value="slo"/&gt;
 *     &lt;enumeration value="slv"/&gt;
 *     &lt;enumeration value="sog"/&gt;
 *     &lt;enumeration value="som"/&gt;
 *     &lt;enumeration value="son"/&gt;
 *     &lt;enumeration value="snk"/&gt;
 *     &lt;enumeration value="wen"/&gt;
 *     &lt;enumeration value="sot"/&gt;
 *     &lt;enumeration value="sai"/&gt;
 *     &lt;enumeration value="alt"/&gt;
 *     &lt;enumeration value="crj"/&gt;
 *     &lt;enumeration value="sma"/&gt;
 *     &lt;enumeration value="spa"/&gt;
 *     &lt;enumeration value="srn"/&gt;
 *     &lt;enumeration value="zgh"/&gt;
 *     &lt;enumeration value="sto"/&gt;
 *     &lt;enumeration value="suk"/&gt;
 *     &lt;enumeration value="sux"/&gt;
 *     &lt;enumeration value="sun"/&gt;
 *     &lt;enumeration value="sus"/&gt;
 *     &lt;enumeration value="swa"/&gt;
 *     &lt;enumeration value="csw"/&gt;
 *     &lt;enumeration value="ssw"/&gt;
 *     &lt;enumeration value="swe"/&gt;
 *     &lt;enumeration value="gsw"/&gt;
 *     &lt;enumeration value="syr"/&gt;
 *     &lt;enumeration value="tgl"/&gt;
 *     &lt;enumeration value="tah"/&gt;
 *     &lt;enumeration value="tai"/&gt;
 *     &lt;enumeration value="tgk"/&gt;
 *     &lt;enumeration value="tmh"/&gt;
 *     &lt;enumeration value="tam"/&gt;
 *     &lt;enumeration value="shi"/&gt;
 *     &lt;enumeration value="tat"/&gt;
 *     &lt;enumeration value="tel"/&gt;
 *     &lt;enumeration value="tem"/&gt;
 *     &lt;enumeration value="ter"/&gt;
 *     &lt;enumeration value="tet"/&gt;
 *     &lt;enumeration value="tha"/&gt;
 *     &lt;enumeration value="thp"/&gt;
 *     &lt;enumeration value="tib"/&gt;
 *     &lt;enumeration value="tig"/&gt;
 *     &lt;enumeration value="tir"/&gt;
 *     &lt;enumeration value="tiv"/&gt;
 *     &lt;enumeration value="tli"/&gt;
 *     &lt;enumeration value="tpi"/&gt;
 *     &lt;enumeration value="tkl"/&gt;
 *     &lt;enumeration value="tod"/&gt;
 *     &lt;enumeration value="tog"/&gt;
 *     &lt;enumeration value="ton"/&gt;
 *     &lt;enumeration value="rmg"/&gt;
 *     &lt;enumeration value="tsd"/&gt;
 *     &lt;enumeration value="tsi"/&gt;
 *     &lt;enumeration value="tso"/&gt;
 *     &lt;enumeration value="tsn"/&gt;
 *     &lt;enumeration value="tum"/&gt;
 *     &lt;enumeration value="tup"/&gt;
 *     &lt;enumeration value="tur"/&gt;
 *     &lt;enumeration value="ota"/&gt;
 *     &lt;enumeration value="tuk"/&gt;
 *     &lt;enumeration value="tvl"/&gt;
 *     &lt;enumeration value="tyv"/&gt;
 *     &lt;enumeration value="twi"/&gt;
 *     &lt;enumeration value="tzo"/&gt;
 *     &lt;enumeration value="udm"/&gt;
 *     &lt;enumeration value="uga"/&gt;
 *     &lt;enumeration value="uig"/&gt;
 *     &lt;enumeration value="ukr"/&gt;
 *     &lt;enumeration value="umb"/&gt;
 *     &lt;enumeration value="hsb"/&gt;
 *     &lt;enumeration value="urj"/&gt;
 *     &lt;enumeration value="urd"/&gt;
 *     &lt;enumeration value="uzb"/&gt;
 *     &lt;enumeration value="vai"/&gt;
 *     &lt;enumeration value="qav"/&gt;
 *     &lt;enumeration value="ven"/&gt;
 *     &lt;enumeration value="vec"/&gt;
 *     &lt;enumeration value="vie"/&gt;
 *     &lt;enumeration value="vol"/&gt;
 *     &lt;enumeration value="vot"/&gt;
 *     &lt;enumeration value="wak"/&gt;
 *     &lt;enumeration value="wls"/&gt;
 *     &lt;enumeration value="wln"/&gt;
 *     &lt;enumeration value="war"/&gt;
 *     &lt;enumeration value="was"/&gt;
 *     &lt;enumeration value="guc"/&gt;
 *     &lt;enumeration value="wel"/&gt;
 *     &lt;enumeration value="fry"/&gt;
 *     &lt;enumeration value="qsw"/&gt;
 *     &lt;enumeration value="wal"/&gt;
 *     &lt;enumeration value="wol"/&gt;
 *     &lt;enumeration value="cwd"/&gt;
 *     &lt;enumeration value="wym"/&gt;
 *     &lt;enumeration value="xho"/&gt;
 *     &lt;enumeration value="sah"/&gt;
 *     &lt;enumeration value="yao"/&gt;
 *     &lt;enumeration value="yap"/&gt;
 *     &lt;enumeration value="yid"/&gt;
 *     &lt;enumeration value="yor"/&gt;
 *     &lt;enumeration value="ypk"/&gt;
 *     &lt;enumeration value="znd"/&gt;
 *     &lt;enumeration value="zap"/&gt;
 *     &lt;enumeration value="zza"/&gt;
 *     &lt;enumeration value="zen"/&gt;
 *     &lt;enumeration value="zha"/&gt;
 *     &lt;enumeration value="zul"/&gt;
 *     &lt;enumeration value="zun"/&gt;
 *     &lt;enumeration value="mis"/&gt;
 *     &lt;enumeration value="und"/&gt;
 *     &lt;enumeration value="mul"/&gt;
 *     &lt;enumeration value="zxx"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List74")
@XmlEnum
public enum List74 {

    @XmlEnumValue("abk")
    ABK("abk"),
    @XmlEnumValue("ace")
    ACE("ace"),
    @XmlEnumValue("ach")
    ACH("ach"),
    @XmlEnumValue("ada")
    ADA("ada"),

    /**
     * (West Circassian)
     * 
     */
    @XmlEnumValue("ady")
    ADY("ady"),
    @XmlEnumValue("aar")
    AAR("aar"),

    /**
     * Artificial language
     * 
     */
    @XmlEnumValue("afh")
    AFH("afh"),
    @XmlEnumValue("afr")
    AFR("afr"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("afa")
    AFA("afa"),
    @XmlEnumValue("ain")
    AIN("ain"),

    /**
     * Macrolanguage. See also fat (Fanti), twi (Twi)
     * 
     */
    @XmlEnumValue("aka")
    AKA("aka"),
    @XmlEnumValue("akk")
    AKK("akk"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("alb")
    ALB("alb"),
    @XmlEnumValue("ale")
    ALE("ale"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("alg")
    ALG("alg"),

    /**
     * Alginkin. ONIX local code, equivalent to alq in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("alq")
    ALQ("alq"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("tut")
    TUT("tut"),
    @XmlEnumValue("amh")
    AMH("amh"),
    @XmlEnumValue("anp")
    ANP("anp"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("apa")
    APA("apa"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("ara")
    ARA("ara"),
    @XmlEnumValue("arg")
    ARG("arg"),

    /**
     * ONIX local code, distinct dialect of Occitan (not distinguished from oci by ISO 639-3)
     * 
     */
    @XmlEnumValue("qar")
    QAR("qar"),
    @XmlEnumValue("arp")
    ARP("arp"),
    @XmlEnumValue("arw")
    ARW("arw"),
    @XmlEnumValue("arm")
    ARM("arm"),
    @XmlEnumValue("rup")
    RUP("rup"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("art")
    ART("art"),
    @XmlEnumValue("asm")
    ASM("asm"),
    @XmlEnumValue("ast")
    AST("ast"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("ath")
    ATH("ath"),

    /**
     * ONIX local code, equivalent to atj in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("atj")
    ATJ("atj"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("aus")
    AUS("aus"),

    /**
     * Collective name. ONIX local code, equivalent of aav in ISO 639-5. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("aav")
    AAV("aav"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("map")
    MAP("map"),
    @XmlEnumValue("ava")
    AVA("ava"),
    @XmlEnumValue("ave")
    AVE("ave"),
    @XmlEnumValue("awa")
    AWA("awa"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("aym")
    AYM("aym"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("aze")
    AZE("aze"),
    @XmlEnumValue("ban")
    BAN("ban"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("bat")
    BAT("bat"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("bal")
    BAL("bal"),
    @XmlEnumValue("bam")
    BAM("bam"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("bai")
    BAI("bai"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("bad")
    BAD("bad"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("bnt")
    BNT("bnt"),
    @XmlEnumValue("bas")
    BAS("bas"),
    @XmlEnumValue("bak")
    BAK("bak"),
    @XmlEnumValue("baq")
    BAQ("baq"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("btk")
    BTK("btk"),
    @XmlEnumValue("bej")
    BEJ("bej"),
    @XmlEnumValue("bel")
    BEL("bel"),
    @XmlEnumValue("bem")
    BEM("bem"),
    @XmlEnumValue("ben")
    BEN("ben"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("ber")
    BER("ber"),
    @XmlEnumValue("bho")
    BHO("bho"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("bih")
    BIH("bih"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("bik")
    BIK("bik"),
    @XmlEnumValue("bin")
    BIN("bin"),
    @XmlEnumValue("bis")
    BIS("bis"),
    @XmlEnumValue("byn")
    BYN("byn"),

    /**
     * Artificial language
     * 
     */
    @XmlEnumValue("zbl")
    ZBL("zbl"),

    /**
     * Boro. ONIX local code, equivalent to brx in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("brx")
    BRX("brx"),
    @XmlEnumValue("bos")
    BOS("bos"),
    @XmlEnumValue("bra")
    BRA("bra"),
    @XmlEnumValue("bre")
    BRE("bre"),
    @XmlEnumValue("bug")
    BUG("bug"),
    @XmlEnumValue("bul")
    BUL("bul"),

    /**
     * ONIX local code, equivalent to bum in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("bum")
    BUM("bum"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("bua")
    BUA("bua"),
    @XmlEnumValue("bur")
    BUR("bur"),
    @XmlEnumValue("cad")
    CAD("cad"),

    /**
     * ONIX local code for Sardinian dialect, equivalent to sro in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("sro")
    SRO("sro"),

    /**
     * ONIX local code, equivalent to yue in ISO 639-3
     * 
     */
    @XmlEnumValue("yue")
    YUE("yue"),

    /**
     * See also qav (Valencian)
     * 
     */
    @XmlEnumValue("cat")
    CAT("cat"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("cau")
    CAU("cau"),

    /**
     * ONIX local code, equivalent to cay in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("cay")
    CAY("cay"),
    @XmlEnumValue("ceb")
    CEB("ceb"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("cel")
    CEL("cel"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("cai")
    CAI("cai"),

    /**
     * ONIX local code, equivalent to tzm in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("tzm")
    TZM("tzm"),
    @XmlEnumValue("khm")
    KHM("khm"),

    /**
     * ONIX local code, equivalent to ckb in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("ckb")
    CKB("ckb"),
    @XmlEnumValue("chg")
    CHG("chg"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("cmc")
    CMC("cmc"),
    @XmlEnumValue("cha")
    CHA("cha"),
    @XmlEnumValue("che")
    CHE("che"),
    @XmlEnumValue("chr")
    CHR("chr"),
    @XmlEnumValue("chy")
    CHY("chy"),
    @XmlEnumValue("chb")
    CHB("chb"),
    @XmlEnumValue("nya")
    NYA("nya"),

    /**
     * ONIX local code, equivalent to cic in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("cic")
    CIC("cic"),

    /**
     * Macrolanguage. See also cmn (Mandarin), yue (Cantonese)
     * 
     */
    @XmlEnumValue("chi")
    CHI("chi"),
    @XmlEnumValue("chn")
    CHN("chn"),
    @XmlEnumValue("chp")
    CHP("chp"),
    @XmlEnumValue("cho")
    CHO("cho"),
    @XmlEnumValue("chu")
    CHU("chu"),
    @XmlEnumValue("chk")
    CHK("chk"),
    @XmlEnumValue("chv")
    CHV("chv"),
    @XmlEnumValue("nwc")
    NWC("nwc"),
    @XmlEnumValue("syc")
    SYC("syc"),
    @XmlEnumValue("cop")
    COP("cop"),
    @XmlEnumValue("cor")
    COR("cor"),
    @XmlEnumValue("cos")
    COS("cos"),

    /**
     * Macrolanguage. See also crj (Southern East Cree), crk (plains Cree), crl (Northern East Cree), crm (Moose Cree), csw (Swampy Cree), cwd (Woods Cree)
     * 
     */
    @XmlEnumValue("cre")
    CRE("cre"),

    /**
     * Seminole
     * 
     */
    @XmlEnumValue("mus")
    MUS("mus"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("crp")
    CRP("crp"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("cpe")
    CPE("cpe"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("cpf")
    CPF("cpf"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("cpp")
    CPP("cpp"),
    @XmlEnumValue("crh")
    CRH("crh"),
    @XmlEnumValue("hrv")
    HRV("hrv"),

    /**
     * Deprecated – use hrv
     * 
     */
    @XmlEnumValue("scr")
    SCR("scr"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("cus")
    CUS("cus"),
    @XmlEnumValue("cze")
    CZE("cze"),
    @XmlEnumValue("dak")
    DAK("dak"),
    @XmlEnumValue("dan")
    DAN("dan"),
    @XmlEnumValue("dar")
    DAR("dar"),

    /**
     * ONIX local code, equivalent to prs in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("prs")
    PRS("prs"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("del")
    DEL("del"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("din")
    DIN("din"),
    @XmlEnumValue("div")
    DIV("div"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("doi")
    DOI("doi"),
    @XmlEnumValue("dgr")
    DGR("dgr"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("dra")
    DRA("dra"),
    @XmlEnumValue("dua")
    DUA("dua"),
    @XmlEnumValue("dum")
    DUM("dum"),
    @XmlEnumValue("dut")
    DUT("dut"),
    @XmlEnumValue("dyu")
    DYU("dyu"),
    @XmlEnumValue("dzo")
    DZO("dzo"),

    /**
     * ONIX local code, equivalent to ike in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("ike")
    IKE("ike"),
    @XmlEnumValue("frs")
    FRS("frs"),
    @XmlEnumValue("efi")
    EFI("efi"),
    @XmlEnumValue("egy")
    EGY("egy"),
    @XmlEnumValue("eka")
    EKA("eka"),
    @XmlEnumValue("elx")
    ELX("elx"),

    /**
     * ONIX local code for Italian dialect, equivalent to egl in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("egl")
    EGL("egl"),
    @XmlEnumValue("eng")
    ENG("eng"),
    @XmlEnumValue("enm")
    ENM("enm"),
    @XmlEnumValue("ang")
    ANG("ang"),
    @XmlEnumValue("myv")
    MYV("myv"),

    /**
     * Inuit-Yupik-Unangan languages. Collective name. ONIX local code, equivalent of esx in ISO 639-5. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("esx")
    ESX("esx"),

    /**
     * Artificial language
     * 
     */
    @XmlEnumValue("epo")
    EPO("epo"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("est")
    EST("est"),
    @XmlEnumValue("gez")
    GEZ("gez"),
    @XmlEnumValue("ewe")
    EWE("ewe"),
    @XmlEnumValue("ewo")
    EWO("ewo"),
    @XmlEnumValue("fan")
    FAN("fan"),
    @XmlEnumValue("fat")
    FAT("fat"),
    @XmlEnumValue("fao")
    FAO("fao"),
    @XmlEnumValue("fij")
    FIJ("fij"),
    @XmlEnumValue("fil")
    FIL("fil"),
    @XmlEnumValue("fin")
    FIN("fin"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("fiu")
    FIU("fiu"),
    @XmlEnumValue("fon")
    FON("fon"),
    @XmlEnumValue("fre")
    FRE("fre"),
    @XmlEnumValue("frm")
    FRM("frm"),

    /**
     * See also qgl (Gallo)
     * 
     */
    @XmlEnumValue("fro")
    FRO("fro"),
    @XmlEnumValue("fur")
    FUR("fur"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("ful")
    FUL("ful"),
    @XmlEnumValue("gaa")
    GAA("gaa"),
    @XmlEnumValue("car")
    CAR("car"),
    @XmlEnumValue("glg")
    GLG("glg"),

    /**
     * ONIX local code, distinct variant of langue d’oïl (old northern French), not distinguished from fro, or from frm, fre, nrf by ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("qgl")
    QGL("qgl"),

    /**
     * ONIX local code for Sardinian dialect, equivalent to sdn in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("sdn")
    SDN("sdn"),
    @XmlEnumValue("lug")
    LUG("lug"),

    /**
     * ONIX local code, equivalent to grt in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("grt")
    GRT("grt"),
    @XmlEnumValue("gay")
    GAY("gay"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("gba")
    GBA("gba"),
    @XmlEnumValue("geo")
    GEO("geo"),
    @XmlEnumValue("ger")
    GER("ger"),
    @XmlEnumValue("gmh")
    GMH("gmh"),
    @XmlEnumValue("goh")
    GOH("goh"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("gem")
    GEM("gem"),
    @XmlEnumValue("gil")
    GIL("gil"),

    /**
     * ONIX local code, equivalent to git in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("git")
    GIT("git"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("gon")
    GON("gon"),
    @XmlEnumValue("gor")
    GOR("gor"),
    @XmlEnumValue("got")
    GOT("got"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("grb")
    GRB("grb"),
    @XmlEnumValue("grc")
    GRC("grc"),
    @XmlEnumValue("gre")
    GRE("gre"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("grn")
    GRN("grn"),

    /**
     * ONIX local code, equivalent to nrf in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("nrf")
    NRF("nrf"),
    @XmlEnumValue("guj")
    GUJ("guj"),
    @XmlEnumValue("gwi")
    GWI("gwi"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("hai")
    HAI("hai"),
    @XmlEnumValue("hat")
    HAT("hat"),
    @XmlEnumValue("hau")
    HAU("hau"),
    @XmlEnumValue("haw")
    HAW("haw"),
    @XmlEnumValue("heb")
    HEB("heb"),
    @XmlEnumValue("her")
    HER("her"),
    @XmlEnumValue("hil")
    HIL("hil"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("him")
    HIM("him"),
    @XmlEnumValue("hin")
    HIN("hin"),
    @XmlEnumValue("hmo")
    HMO("hmo"),
    @XmlEnumValue("hit")
    HIT("hit"),

    /**
     * Collective name. ONIX local code, equivalent of hmx in ISO 639-5. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("hmx")
    HMX("hmx"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("hmn")
    HMN("hmn"),

    /**
     * ONIX local code, equivalent to hop in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("hop")
    HOP("hop"),
    @XmlEnumValue("hun")
    HUN("hun"),
    @XmlEnumValue("hup")
    HUP("hup"),
    @XmlEnumValue("iba")
    IBA("iba"),
    @XmlEnumValue("ice")
    ICE("ice"),

    /**
     * Artificial language
     * 
     */
    @XmlEnumValue("ido")
    IDO("ido"),
    @XmlEnumValue("ibo")
    IBO("ibo"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("ijo")
    IJO("ijo"),
    @XmlEnumValue("ilo")
    ILO("ilo"),
    @XmlEnumValue("smn")
    SMN("smn"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("inc")
    INC("inc"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("ine")
    INE("ine"),
    @XmlEnumValue("ind")
    IND("ind"),
    @XmlEnumValue("inh")
    INH("inh"),

    /**
     * ONIX local code, equivalent to moe in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("moe")
    MOE("moe"),

    /**
     * Artificial language
     * 
     */
    @XmlEnumValue("ina")
    INA("ina"),

    /**
     * Artificial language
     * 
     */
    @XmlEnumValue("ile")
    ILE("ile"),

    /**
     * Western Canadian Inuktitut. ONIX local code, equivalent to ikt in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("ikt")
    IKT("ikt"),

    /**
     * Macrolanguage. See also ike (Eastern Canadian Inuktitut), ikt (Inuinnaqtun)
     * 
     */
    @XmlEnumValue("iku")
    IKU("iku"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("ipk")
    IPK("ipk"),

    /**
     * ONIX local code, distinct dialect of Inuktitut (not distinguished from iku, ike, ikt by ISO 639-3). Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("qiv")
    QIV("qiv"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("ira")
    IRA("ira"),

    /**
     * ONIX local code, equivalent to pes in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("pes")
    PES("pes"),
    @XmlEnumValue("gle")
    GLE("gle"),
    @XmlEnumValue("mga")
    MGA("mga"),
    @XmlEnumValue("sga")
    SGA("sga"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("iro")
    IRO("iro"),
    @XmlEnumValue("ita")
    ITA("ita"),
    @XmlEnumValue("jpn")
    JPN("jpn"),

    /**
     * Japonic. Collective name. ONIX local code, equivalent of jpx in ISO 639-5. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("jpx")
    JPX("jpx"),
    @XmlEnumValue("jav")
    JAV("jav"),

    /**
     * ONIX local code, equivalent to jow in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("jow")
    JOW("jow"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("jrb")
    JRB("jrb"),
    @XmlEnumValue("jpr")
    JPR("jpr"),

    /**
     * (East Circassian)
     * 
     */
    @XmlEnumValue("kbd")
    KBD("kbd"),

    /**
     * ONIX local code, equivalent to kbp in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("kbp")
    KBP("kbp"),
    @XmlEnumValue("kab")
    KAB("kab"),
    @XmlEnumValue("kac")
    KAC("kac"),
    @XmlEnumValue("kal")
    KAL("kal"),
    @XmlEnumValue("xal")
    XAL("xal"),
    @XmlEnumValue("kam")
    KAM("kam"),
    @XmlEnumValue("kan")
    KAN("kan"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("kau")
    KAU("kau"),
    @XmlEnumValue("kaa")
    KAA("kaa"),
    @XmlEnumValue("krc")
    KRC("krc"),

    /**
     * ONIX local code, equivalent to kdr in ISO 639-3
     * 
     */
    @XmlEnumValue("kdr")
    KDR("kdr"),
    @XmlEnumValue("krl")
    KRL("krl"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("kar")
    KAR("kar"),
    @XmlEnumValue("kas")
    KAS("kas"),
    @XmlEnumValue("csb")
    CSB("csb"),
    @XmlEnumValue("kaw")
    KAW("kaw"),
    @XmlEnumValue("kaz")
    KAZ("kaz"),
    @XmlEnumValue("kha")
    KHA("kha"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("khi")
    KHI("khi"),
    @XmlEnumValue("kho")
    KHO("kho"),

    /**
     * ONIX local code, equivalent to xuu in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("xuu")
    XUU("xuu"),
    @XmlEnumValue("kik")
    KIK("kik"),
    @XmlEnumValue("kmb")
    KMB("kmb"),
    @XmlEnumValue("kin")
    KIN("kin"),
    @XmlEnumValue("kir")
    KIR("kir"),

    /**
     * Kisi (Guinean language). ONIX local code, equivalent to kqs in ISO 639-3. Only for use in ONIX 3.0 or later. Do not confuse with Kisi (Tanzanian language)
     * 
     */
    @XmlEnumValue("kqs")
    KQS("kqs"),

    /**
     * Kisi (Liberian language). ONIX local code, equivalent to kss in ISO 639-3. Only for use in ONIX 3.0 or later. Do not confuse with Kisi (Tanzanian language)
     * 
     */
    @XmlEnumValue("kss")
    KSS("kss"),

    /**
     * Artificial language
     * 
     */
    @XmlEnumValue("tlh")
    TLH("tlh"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("kom")
    KOM("kom"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("kon")
    KON("kon"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("kok")
    KOK("kok"),
    @XmlEnumValue("kor")
    KOR("kor"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("kpe")
    KPE("kpe"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("kro")
    KRO("kro"),
    @XmlEnumValue("kua")
    KUA("kua"),
    @XmlEnumValue("kum")
    KUM("kum"),

    /**
     * Macrolanguage. See also ckb (Central Kurdish)
     * 
     */
    @XmlEnumValue("kur")
    KUR("kur"),
    @XmlEnumValue("kru")
    KRU("kru"),
    @XmlEnumValue("kos")
    KOS("kos"),
    @XmlEnumValue("kut")
    KUT("kut"),

    /**
     * ONIX local code, equivalent to fkv in ISO 639-3
     * 
     */
    @XmlEnumValue("fkv")
    FKV("fkv"),

    /**
     * ONIX local code, equivalent to kwk in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("kwk")
    KWK("kwk"),
    @XmlEnumValue("lad")
    LAD("lad"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("lah")
    LAH("lah"),

    /**
     * Teton, Teton Sioux. ONIX local code, equivalent to lkt in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("lkt")
    LKT("lkt"),
    @XmlEnumValue("lam")
    LAM("lam"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("day")
    DAY("day"),
    @XmlEnumValue("lao")
    LAO("lao"),
    @XmlEnumValue("lat")
    LAT("lat"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("lav")
    LAV("lav"),

    /**
     * ONIX local code, distinct dialect of of Rusyn (not distinguished from rue by ISO 639-3). Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("qlk")
    QLK("qlk"),
    @XmlEnumValue("lez")
    LEZ("lez"),

    /**
     * ONIX local code for Italian dialect, equivalent to lij in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("lij")
    LIJ("lij"),
    @XmlEnumValue("lim")
    LIM("lim"),
    @XmlEnumValue("lin")
    LIN("lin"),
    @XmlEnumValue("lit")
    LIT("lit"),
    @XmlEnumValue("jbo")
    JBO("jbo"),

    /**
     * ONIX local code for Liberian language, equivalent to lom in ISO 639-3. See also Toma for the closely-related Guinean variant. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("lom")
    LOM("lom"),

    /**
     * ONIX local code for Italian dialect, equivalent to lmo in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("lmo")
    LMO("lmo"),
    @XmlEnumValue("nds")
    NDS("nds"),
    @XmlEnumValue("dsb")
    DSB("dsb"),
    @XmlEnumValue("loz")
    LOZ("loz"),
    @XmlEnumValue("lub")
    LUB("lub"),
    @XmlEnumValue("lua")
    LUA("lua"),
    @XmlEnumValue("lui")
    LUI("lui"),
    @XmlEnumValue("smj")
    SMJ("smj"),
    @XmlEnumValue("lun")
    LUN("lun"),
    @XmlEnumValue("luo")
    LUO("luo"),
    @XmlEnumValue("lus")
    LUS("lus"),
    @XmlEnumValue("ltz")
    LTZ("ltz"),
    @XmlEnumValue("mac")
    MAC("mac"),
    @XmlEnumValue("mad")
    MAD("mad"),
    @XmlEnumValue("mag")
    MAG("mag"),
    @XmlEnumValue("mai")
    MAI("mai"),
    @XmlEnumValue("mak")
    MAK("mak"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("mlg")
    MLG("mlg"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("may")
    MAY("may"),
    @XmlEnumValue("mal")
    MAL("mal"),

    /**
     * Collective name. ONIX local code, equivalent of poz in ISO 639-5. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("poz")
    POZ("poz"),
    @XmlEnumValue("mlt")
    MLT("mlt"),
    @XmlEnumValue("mnc")
    MNC("mnc"),
    @XmlEnumValue("mdr")
    MDR("mdr"),

    /**
     * ONIX local code, equivalent to cmn in ISO 639-3
     * 
     */
    @XmlEnumValue("cmn")
    CMN("cmn"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("man")
    MAN("man"),
    @XmlEnumValue("mni")
    MNI("mni"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("mno")
    MNO("mno"),
    @XmlEnumValue("glv")
    GLV("glv"),

    /**
     * Shimaore. ONIX local code, equivalent to swb in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("swb")
    SWB("swb"),
    @XmlEnumValue("mao")
    MAO("mao"),
    @XmlEnumValue("arn")
    ARN("arn"),
    @XmlEnumValue("mar")
    MAR("mar"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("chm")
    CHM("chm"),
    @XmlEnumValue("mah")
    MAH("mah"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("mwr")
    MWR("mwr"),
    @XmlEnumValue("mas")
    MAS("mas"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("myn")
    MYN("myn"),

    /**
     * ONIX local code, equivalent to fit in ISO 639-3
     * 
     */
    @XmlEnumValue("fit")
    FIT("fit"),
    @XmlEnumValue("men")
    MEN("men"),
    @XmlEnumValue("mic")
    MIC("mic"),

    /**
     * ONIX local code, equivalent to crg in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("crg")
    CRG("crg"),

    /**
     * ONIX local code, equivalent to gml in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("gml")
    GML("gml"),
    @XmlEnumValue("min")
    MIN("min"),
    @XmlEnumValue("mwl")
    MWL("mwl"),
    @XmlEnumValue("moh")
    MOH("moh"),
    @XmlEnumValue("mdf")
    MDF("mdf"),

    /**
     * Deprecated – use rum
     * 
     */
    @XmlEnumValue("mol")
    MOL("mol"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("mkh")
    MKH("mkh"),
    @XmlEnumValue("lol")
    LOL("lol"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("mon")
    MON("mon"),

    /**
     * Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("cnr")
    CNR("cnr"),
    @XmlEnumValue("mos")
    MOS("mos"),

    /**
     * ONIX local code, equivalent to crm in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("crm")
    CRM("crm"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("mun")
    MUN("mun"),

    /**
     * ONIX local code, equivalent to mwf in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("mwf")
    MWF("mwf"),
    @XmlEnumValue("nqo")
    NQO("nqo"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("nah")
    NAH("nah"),

    /**
     * ONIX local code, equivalent to nsk in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("nsk")
    NSK("nsk"),
    @XmlEnumValue("nau")
    NAU("nau"),
    @XmlEnumValue("nav")
    NAV("nav"),
    @XmlEnumValue("nde")
    NDE("nde"),
    @XmlEnumValue("nbl")
    NBL("nbl"),
    @XmlEnumValue("ndo")
    NDO("ndo"),
    @XmlEnumValue("nap")
    NAP("nap"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("nep")
    NEP("nep"),

    /**
     * ONIX local code, distinct and exclusively spoken variation of Spanish, not distinguished from spa (Spanish, Castilian) by ISO 639-3. Neutral Latin American Spanish should be considered a ‘shorthand’ for spa plus a ‘country code’ for Latin America – but prefer spa plus the relevant country code for specifically Mexican Spanish, Argentine (Rioplatense) Spanish, Puerto Rican Spanish etc. Neutral Latin American Spanish must only be used with audio material (including the audio tracks of TV, video and film) to indicate use of accent, vocabulary and construction suitable for broad use across Latin America. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("qls")
    QLS("qls"),
    @XmlEnumValue("new")
    NEW("new"),
    @XmlEnumValue("nia")
    NIA("nia"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("nic")
    NIC("nic"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("ssa")
    SSA("ssa"),
    @XmlEnumValue("niu")
    NIU("niu"),
    @XmlEnumValue("nog")
    NOG("nog"),

    /**
     * Normand, of which Guernésiais, Jèrriais are distinct dialects. ONIX local code (not distinguished from nrf in ISO 639-3). Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("qnf")
    QNF("qnf"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("nai")
    NAI("nai"),

    /**
     * ONIX local code, equivalent to crl in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("crl")
    CRL("crl"),
    @XmlEnumValue("frr")
    FRR("frr"),
    @XmlEnumValue("sme")
    SME("sme"),

    /**
     * Macrolanguage. See also nob (Bokmål), nno (Nynorsk)
     * 
     */
    @XmlEnumValue("nor")
    NOR("nor"),
    @XmlEnumValue("nob")
    NOB("nob"),
    @XmlEnumValue("nno")
    NNO("nno"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("nub")
    NUB("nub"),
    @XmlEnumValue("nym")
    NYM("nym"),
    @XmlEnumValue("nyn")
    NYN("nyn"),
    @XmlEnumValue("nyo")
    NYO("nyo"),
    @XmlEnumValue("nzi")
    NZI("nzi"),

    /**
     * See also qar (Aranés)
     * 
     */
    @XmlEnumValue("oci")
    OCI("oci"),
    @XmlEnumValue("arc")
    ARC("arc"),

    /**
     * Macrolanguage. See also ojs (Severn Ojibwa)
     * 
     */
    @XmlEnumValue("oji")
    OJI("oji"),

    /**
     * Colville-Okanagan. ONIX local code, equivalent to oka in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("oka")
    OKA("oka"),

    /**
     * ONIX local code, equivalent to odt in ISO 639-3
     * 
     */
    @XmlEnumValue("odt")
    ODT("odt"),
    @XmlEnumValue("non")
    NON("non"),
    @XmlEnumValue("peo")
    PEO("peo"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("ori")
    ORI("ori"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("orm")
    ORM("orm"),
    @XmlEnumValue("osa")
    OSA("osa"),
    @XmlEnumValue("oss")
    OSS("oss"),

    /**
     * ONIX local code, equivalent to omq in ISO 639-5. Collective name
     * 
     */
    @XmlEnumValue("omq")
    OMQ("omq"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("oto")
    OTO("oto"),
    @XmlEnumValue("pal")
    PAL("pal"),
    @XmlEnumValue("pau")
    PAU("pau"),
    @XmlEnumValue("pli")
    PLI("pli"),
    @XmlEnumValue("pam")
    PAM("pam"),
    @XmlEnumValue("pag")
    PAG("pag"),
    @XmlEnumValue("pan")
    PAN("pan"),
    @XmlEnumValue("pap")
    PAP("pap"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("paa")
    PAA("paa"),
    @XmlEnumValue("nso")
    NSO("nso"),

    /**
     * Macrolanguage. See also pes (Iranian Persian, Farsi), prs (Dari)
     * 
     */
    @XmlEnumValue("per")
    PER("per"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("phi")
    PHI("phi"),
    @XmlEnumValue("phn")
    PHN("phn"),

    /**
     * ONIX local code, distinct variant of langue d’oïl (old northern French), equivalent to pcd in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("pcd")
    PCD("pcd"),

    /**
     * ONIX local code for graphical symbols used in augmentative and alternative communication and education, not listed in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("qsp")
    QSP("qsp"),

    /**
     * ONIX local code for Italian dialect, equivalent to pms in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("pms")
    PMS("pms"),

    /**
     * ONIX local code, equivalent to crk in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("crk")
    CRK("crk"),
    @XmlEnumValue("pol")
    POL("pol"),
    @XmlEnumValue("pon")
    PON("pon"),
    @XmlEnumValue("por")
    POR("por"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("pra")
    PRA("pra"),
    @XmlEnumValue("pro")
    PRO("pro"),

    /**
     * ONIX local code, equivalent to fuf in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("fuf")
    FUF("fuf"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("pus")
    PUS("pus"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("que")
    QUE("que"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("raj")
    RAJ("raj"),
    @XmlEnumValue("rap")
    RAP("rap"),
    @XmlEnumValue("rar")
    RAR("rar"),

    /**
     * ONIX local code, equivalent to rcf in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("rcf")
    RCF("rcf"),

    /**
     * ONIX local code for Italian dialect, equivalent to rgl in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("rgn")
    RGN("rgn"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("roa")
    ROA("roa"),
    @XmlEnumValue("rum")
    RUM("rum"),
    @XmlEnumValue("roh")
    ROH("roh"),

    /**
     * Romani. Macrolanguage
     * 
     */
    @XmlEnumValue("rom")
    ROM("rom"),
    @XmlEnumValue("run")
    RUN("run"),
    @XmlEnumValue("rus")
    RUS("rus"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("sal")
    SAL("sal"),
    @XmlEnumValue("sam")
    SAM("sam"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("smi")
    SMI("smi"),
    @XmlEnumValue("smo")
    SMO("smo"),
    @XmlEnumValue("sad")
    SAD("sad"),
    @XmlEnumValue("sag")
    SAG("sag"),
    @XmlEnumValue("san")
    SAN("san"),
    @XmlEnumValue("sat")
    SAT("sat"),

    /**
     * ONIX local code for Saramaccan language, equivalent to srm in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("srm")
    SRM("srm"),

    /**
     * Macrolanguage. See also sdc (Sassarese), sdn (Gallurese), sro (Campidanese)
     * 
     */
    @XmlEnumValue("srd")
    SRD("srd"),
    @XmlEnumValue("sas")
    SAS("sas"),

    /**
     * ONIX local code for Sardinian dialect, equivalent to sdc in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("sdc")
    SDC("sdc"),
    @XmlEnumValue("sco")
    SCO("sco"),
    @XmlEnumValue("gla")
    GLA("gla"),
    @XmlEnumValue("sel")
    SEL("sel"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("sem")
    SEM("sem"),

    /**
     * Deprecated – use srp
     * 
     */
    @XmlEnumValue("scc")
    SCC("scc"),
    @XmlEnumValue("srp")
    SRP("srp"),
    @XmlEnumValue("srr")
    SRR("srr"),

    /**
     * ONIX local code, equivalent to ojs in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("ojs")
    OJS("ojs"),
    @XmlEnumValue("shn")
    SHN("shn"),
    @XmlEnumValue("sna")
    SNA("sna"),

    /**
     * ONIX local code, equivalent to shs in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("shs")
    SHS("shs"),
    @XmlEnumValue("iii")
    III("iii"),
    @XmlEnumValue("scn")
    SCN("scn"),
    @XmlEnumValue("sid")
    SID("sid"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("sgn")
    SGN("sgn"),
    @XmlEnumValue("bla")
    BLA("bla"),

    /**
     * ONIX local code, equivalent to szl in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("szl")
    SZL("szl"),
    @XmlEnumValue("snd")
    SND("snd"),
    @XmlEnumValue("sin")
    SIN("sin"),

    /**
     * Chinese (family) languages. Collective name. ONIX local code, equivalent of zhx in ISO 639-5. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("zhx")
    ZHX("zhx"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("sit")
    SIT("sit"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("sio")
    SIO("sio"),
    @XmlEnumValue("sms")
    SMS("sms"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("den")
    DEN("den"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("sla")
    SLA("sla"),
    @XmlEnumValue("slo")
    SLO("slo"),
    @XmlEnumValue("slv")
    SLV("slv"),
    @XmlEnumValue("sog")
    SOG("sog"),
    @XmlEnumValue("som")
    SOM("som"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("son")
    SON("son"),
    @XmlEnumValue("snk")
    SNK("snk"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("wen")
    WEN("wen"),
    @XmlEnumValue("sot")
    SOT("sot"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("sai")
    SAI("sai"),
    @XmlEnumValue("alt")
    ALT("alt"),

    /**
     * ONIX local code, equivalent to crj in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("crj")
    CRJ("crj"),
    @XmlEnumValue("sma")
    SMA("sma"),
    @XmlEnumValue("spa")
    SPA("spa"),
    @XmlEnumValue("srn")
    SRN("srn"),
    @XmlEnumValue("zgh")
    ZGH("zgh"),

    /**
     * ONIX local code, equivalent to sto in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("sto")
    STO("sto"),
    @XmlEnumValue("suk")
    SUK("suk"),
    @XmlEnumValue("sux")
    SUX("sux"),
    @XmlEnumValue("sun")
    SUN("sun"),
    @XmlEnumValue("sus")
    SUS("sus"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("swa")
    SWA("swa"),

    /**
     * ONIX local code, equivalent to csw in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("csw")
    CSW("csw"),
    @XmlEnumValue("ssw")
    SSW("ssw"),
    @XmlEnumValue("swe")
    SWE("swe"),
    @XmlEnumValue("gsw")
    GSW("gsw"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("syr")
    SYR("syr"),
    @XmlEnumValue("tgl")
    TGL("tgl"),
    @XmlEnumValue("tah")
    TAH("tah"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("tai")
    TAI("tai"),
    @XmlEnumValue("tgk")
    TGK("tgk"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("tmh")
    TMH("tmh"),
    @XmlEnumValue("tam")
    TAM("tam"),

    /**
     * ONIX local code, equivalent to shi in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("shi")
    SHI("shi"),
    @XmlEnumValue("tat")
    TAT("tat"),
    @XmlEnumValue("tel")
    TEL("tel"),
    @XmlEnumValue("tem")
    TEM("tem"),
    @XmlEnumValue("ter")
    TER("ter"),
    @XmlEnumValue("tet")
    TET("tet"),
    @XmlEnumValue("tha")
    THA("tha"),

    /**
     * Nla’kapamux. ONIX local code, equivalent to thp in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("thp")
    THP("thp"),
    @XmlEnumValue("tib")
    TIB("tib"),
    @XmlEnumValue("tig")
    TIG("tig"),
    @XmlEnumValue("tir")
    TIR("tir"),
    @XmlEnumValue("tiv")
    TIV("tiv"),
    @XmlEnumValue("tli")
    TLI("tli"),
    @XmlEnumValue("tpi")
    TPI("tpi"),
    @XmlEnumValue("tkl")
    TKL("tkl"),

    /**
     * ONIX local code for Guinean language, equivalent to tod in ISO 639-3. See also Loma for the closely-related Liberian variant. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("tod")
    TOD("tod"),
    @XmlEnumValue("tog")
    TOG("tog"),
    @XmlEnumValue("ton")
    TON("ton"),

    /**
     * ONIX local code for Norwegian Scandoromani variant, equivalent to rmg in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("rmg")
    RMG("rmg"),

    /**
     * ONIX local code, equivalent to tsd in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("tsd")
    TSD("tsd"),
    @XmlEnumValue("tsi")
    TSI("tsi"),
    @XmlEnumValue("tso")
    TSO("tso"),

    /**
     * AKA Setswana
     * 
     */
    @XmlEnumValue("tsn")
    TSN("tsn"),
    @XmlEnumValue("tum")
    TUM("tum"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("tup")
    TUP("tup"),
    @XmlEnumValue("tur")
    TUR("tur"),
    @XmlEnumValue("ota")
    OTA("ota"),
    @XmlEnumValue("tuk")
    TUK("tuk"),
    @XmlEnumValue("tvl")
    TVL("tvl"),
    @XmlEnumValue("tyv")
    TYV("tyv"),
    @XmlEnumValue("twi")
    TWI("twi"),

    /**
     * ONIX local code, equivalent to tzo in ISO 639-3
     * 
     */
    @XmlEnumValue("tzo")
    TZO("tzo"),
    @XmlEnumValue("udm")
    UDM("udm"),
    @XmlEnumValue("uga")
    UGA("uga"),
    @XmlEnumValue("uig")
    UIG("uig"),
    @XmlEnumValue("ukr")
    UKR("ukr"),
    @XmlEnumValue("umb")
    UMB("umb"),
    @XmlEnumValue("hsb")
    HSB("hsb"),

    /**
     * Collective name. ONIX local code, equivalent of urj in ISO 639-5. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("urj")
    URJ("urj"),
    @XmlEnumValue("urd")
    URD("urd"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("uzb")
    UZB("uzb"),
    @XmlEnumValue("vai")
    VAI("vai"),

    /**
     * ONIX local code, distinct dialect of Catalan (not distinguished from cat by ISO 639-3)
     * 
     */
    @XmlEnumValue("qav")
    QAV("qav"),
    @XmlEnumValue("ven")
    VEN("ven"),

    /**
     * ONIX local code for Italian dialect, equivalent to vec in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("vec")
    VEC("vec"),
    @XmlEnumValue("vie")
    VIE("vie"),

    /**
     * Artificial language
     * 
     */
    @XmlEnumValue("vol")
    VOL("vol"),
    @XmlEnumValue("vot")
    VOT("vot"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("wak")
    WAK("wak"),

    /**
     * East Uvean. ONIX local code, equivalent to wls in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("wls")
    WLS("wls"),
    @XmlEnumValue("wln")
    WLN("wln"),
    @XmlEnumValue("war")
    WAR("war"),
    @XmlEnumValue("was")
    WAS("was"),

    /**
     * Guajiro. ONIX local code, equivalent of guc in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("guc")
    GUC("guc"),
    @XmlEnumValue("wel")
    WEL("wel"),
    @XmlEnumValue("fry")
    FRY("fry"),

    /**
     * ONIX local code for graphical symbols used in augmentative and alternative communication and education, not listed in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("qsw")
    QSW("qsw"),
    @XmlEnumValue("wal")
    WAL("wal"),
    @XmlEnumValue("wol")
    WOL("wol"),

    /**
     * ONIX local code, equivalent to cwd in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("cwd")
    CWD("cwd"),

    /**
     * Vilamovian. ONIX local code, equivalent to wym in ISO 639-3. Only for use in ONIX 3.0 or later
     * 
     */
    @XmlEnumValue("wym")
    WYM("wym"),
    @XmlEnumValue("xho")
    XHO("xho"),
    @XmlEnumValue("sah")
    SAH("sah"),
    @XmlEnumValue("yao")
    YAO("yao"),
    @XmlEnumValue("yap")
    YAP("yap"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("yid")
    YID("yid"),
    @XmlEnumValue("yor")
    YOR("yor"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("ypk")
    YPK("ypk"),

    /**
     * Collective name
     * 
     */
    @XmlEnumValue("znd")
    ZND("znd"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("zap")
    ZAP("zap"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("zza")
    ZZA("zza"),
    @XmlEnumValue("zen")
    ZEN("zen"),

    /**
     * Macrolanguage
     * 
     */
    @XmlEnumValue("zha")
    ZHA("zha"),
    @XmlEnumValue("zul")
    ZUL("zul"),
    @XmlEnumValue("zun")
    ZUN("zun"),

    /**
     * Use where no suitable code is available
     * 
     */
    @XmlEnumValue("mis")
    MIS("mis"),
    @XmlEnumValue("und")
    UND("und"),
    @XmlEnumValue("mul")
    MUL("mul"),
    @XmlEnumValue("zxx")
    ZXX("zxx");
    private final String value;

    List74(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List74 fromValue(String v) {
        for (List74 c: List74 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
