//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.27 at 10:08:36 AM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List66.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List66"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="N"/&gt;
 *     &lt;enumeration value="Y"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *     &lt;enumeration value="C"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List66")
@XmlEnum
public enum List66 {

    N,
    Y,

    /**
     * Note the product barcode should be repeated (with triangular ‘strippable’ indicator) on cover 2 (inside front cover) to facilitate scanning of returned stripped covers
     * 
     */
    S,

    /**
     * Contact publisher for requirements and/or authorization
     * 
     */
    C;

    public String value() {
        return name();
    }

    public static List66 fromValue(String v) {
        return valueOf(v);
    }

}
