//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.27 at 10:08:36 AM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List175.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List175"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A101"/&gt;
 *     &lt;enumeration value="A102"/&gt;
 *     &lt;enumeration value="A103"/&gt;
 *     &lt;enumeration value="A104"/&gt;
 *     &lt;enumeration value="A105"/&gt;
 *     &lt;enumeration value="A106"/&gt;
 *     &lt;enumeration value="A107"/&gt;
 *     &lt;enumeration value="A108"/&gt;
 *     &lt;enumeration value="A109"/&gt;
 *     &lt;enumeration value="A110"/&gt;
 *     &lt;enumeration value="A111"/&gt;
 *     &lt;enumeration value="A112"/&gt;
 *     &lt;enumeration value="A113"/&gt;
 *     &lt;enumeration value="A201"/&gt;
 *     &lt;enumeration value="A202"/&gt;
 *     &lt;enumeration value="A203"/&gt;
 *     &lt;enumeration value="A204"/&gt;
 *     &lt;enumeration value="A205"/&gt;
 *     &lt;enumeration value="A206"/&gt;
 *     &lt;enumeration value="A207"/&gt;
 *     &lt;enumeration value="A208"/&gt;
 *     &lt;enumeration value="A209"/&gt;
 *     &lt;enumeration value="A210"/&gt;
 *     &lt;enumeration value="A211"/&gt;
 *     &lt;enumeration value="A212"/&gt;
 *     &lt;enumeration value="A301"/&gt;
 *     &lt;enumeration value="A302"/&gt;
 *     &lt;enumeration value="A303"/&gt;
 *     &lt;enumeration value="A304"/&gt;
 *     &lt;enumeration value="A305"/&gt;
 *     &lt;enumeration value="A310"/&gt;
 *     &lt;enumeration value="A311"/&gt;
 *     &lt;enumeration value="A312"/&gt;
 *     &lt;enumeration value="A400"/&gt;
 *     &lt;enumeration value="A401"/&gt;
 *     &lt;enumeration value="A402"/&gt;
 *     &lt;enumeration value="A403"/&gt;
 *     &lt;enumeration value="A404"/&gt;
 *     &lt;enumeration value="A410"/&gt;
 *     &lt;enumeration value="A420"/&gt;
 *     &lt;enumeration value="A421"/&gt;
 *     &lt;enumeration value="A441"/&gt;
 *     &lt;enumeration value="A451"/&gt;
 *     &lt;enumeration value="A471"/&gt;
 *     &lt;enumeration value="B101"/&gt;
 *     &lt;enumeration value="B102"/&gt;
 *     &lt;enumeration value="B103"/&gt;
 *     &lt;enumeration value="B104"/&gt;
 *     &lt;enumeration value="B105"/&gt;
 *     &lt;enumeration value="B106"/&gt;
 *     &lt;enumeration value="B107"/&gt;
 *     &lt;enumeration value="B108"/&gt;
 *     &lt;enumeration value="B109"/&gt;
 *     &lt;enumeration value="B110"/&gt;
 *     &lt;enumeration value="B111"/&gt;
 *     &lt;enumeration value="B112"/&gt;
 *     &lt;enumeration value="B113"/&gt;
 *     &lt;enumeration value="B114"/&gt;
 *     &lt;enumeration value="B115"/&gt;
 *     &lt;enumeration value="B116"/&gt;
 *     &lt;enumeration value="B117"/&gt;
 *     &lt;enumeration value="B118"/&gt;
 *     &lt;enumeration value="B119"/&gt;
 *     &lt;enumeration value="B120"/&gt;
 *     &lt;enumeration value="B121"/&gt;
 *     &lt;enumeration value="B122"/&gt;
 *     &lt;enumeration value="B123"/&gt;
 *     &lt;enumeration value="B124"/&gt;
 *     &lt;enumeration value="B125"/&gt;
 *     &lt;enumeration value="B126"/&gt;
 *     &lt;enumeration value="B127"/&gt;
 *     &lt;enumeration value="B128"/&gt;
 *     &lt;enumeration value="B129"/&gt;
 *     &lt;enumeration value="B130"/&gt;
 *     &lt;enumeration value="B131"/&gt;
 *     &lt;enumeration value="B132"/&gt;
 *     &lt;enumeration value="B133"/&gt;
 *     &lt;enumeration value="B134"/&gt;
 *     &lt;enumeration value="B135"/&gt;
 *     &lt;enumeration value="B139"/&gt;
 *     &lt;enumeration value="B140"/&gt;
 *     &lt;enumeration value="B141"/&gt;
 *     &lt;enumeration value="B201"/&gt;
 *     &lt;enumeration value="B202"/&gt;
 *     &lt;enumeration value="B204"/&gt;
 *     &lt;enumeration value="B205"/&gt;
 *     &lt;enumeration value="B206"/&gt;
 *     &lt;enumeration value="B207"/&gt;
 *     &lt;enumeration value="B208"/&gt;
 *     &lt;enumeration value="B209"/&gt;
 *     &lt;enumeration value="B210"/&gt;
 *     &lt;enumeration value="B212"/&gt;
 *     &lt;enumeration value="B213"/&gt;
 *     &lt;enumeration value="B214"/&gt;
 *     &lt;enumeration value="B215"/&gt;
 *     &lt;enumeration value="B216"/&gt;
 *     &lt;enumeration value="B221"/&gt;
 *     &lt;enumeration value="B222"/&gt;
 *     &lt;enumeration value="B223"/&gt;
 *     &lt;enumeration value="B224"/&gt;
 *     &lt;enumeration value="B225"/&gt;
 *     &lt;enumeration value="B301"/&gt;
 *     &lt;enumeration value="B302"/&gt;
 *     &lt;enumeration value="B303"/&gt;
 *     &lt;enumeration value="B304"/&gt;
 *     &lt;enumeration value="B305"/&gt;
 *     &lt;enumeration value="B306"/&gt;
 *     &lt;enumeration value="B307"/&gt;
 *     &lt;enumeration value="B308"/&gt;
 *     &lt;enumeration value="B309"/&gt;
 *     &lt;enumeration value="B310"/&gt;
 *     &lt;enumeration value="B311"/&gt;
 *     &lt;enumeration value="B312"/&gt;
 *     &lt;enumeration value="B313"/&gt;
 *     &lt;enumeration value="B314"/&gt;
 *     &lt;enumeration value="B315"/&gt;
 *     &lt;enumeration value="B316"/&gt;
 *     &lt;enumeration value="B317"/&gt;
 *     &lt;enumeration value="B318"/&gt;
 *     &lt;enumeration value="B319"/&gt;
 *     &lt;enumeration value="B320"/&gt;
 *     &lt;enumeration value="B321"/&gt;
 *     &lt;enumeration value="B400"/&gt;
 *     &lt;enumeration value="B401"/&gt;
 *     &lt;enumeration value="B402"/&gt;
 *     &lt;enumeration value="B403"/&gt;
 *     &lt;enumeration value="B404"/&gt;
 *     &lt;enumeration value="B405"/&gt;
 *     &lt;enumeration value="B406"/&gt;
 *     &lt;enumeration value="B407"/&gt;
 *     &lt;enumeration value="B419"/&gt;
 *     &lt;enumeration value="B408"/&gt;
 *     &lt;enumeration value="B409"/&gt;
 *     &lt;enumeration value="B410"/&gt;
 *     &lt;enumeration value="B411"/&gt;
 *     &lt;enumeration value="B412"/&gt;
 *     &lt;enumeration value="B413"/&gt;
 *     &lt;enumeration value="B414"/&gt;
 *     &lt;enumeration value="B415"/&gt;
 *     &lt;enumeration value="B416"/&gt;
 *     &lt;enumeration value="B417"/&gt;
 *     &lt;enumeration value="B418"/&gt;
 *     &lt;enumeration value="B420"/&gt;
 *     &lt;enumeration value="B421"/&gt;
 *     &lt;enumeration value="B501"/&gt;
 *     &lt;enumeration value="B502"/&gt;
 *     &lt;enumeration value="B503"/&gt;
 *     &lt;enumeration value="B504"/&gt;
 *     &lt;enumeration value="B505"/&gt;
 *     &lt;enumeration value="B506"/&gt;
 *     &lt;enumeration value="B507"/&gt;
 *     &lt;enumeration value="B508"/&gt;
 *     &lt;enumeration value="B509"/&gt;
 *     &lt;enumeration value="B510"/&gt;
 *     &lt;enumeration value="B511"/&gt;
 *     &lt;enumeration value="B512"/&gt;
 *     &lt;enumeration value="B513"/&gt;
 *     &lt;enumeration value="B514"/&gt;
 *     &lt;enumeration value="B515"/&gt;
 *     &lt;enumeration value="B516"/&gt;
 *     &lt;enumeration value="B517"/&gt;
 *     &lt;enumeration value="B518"/&gt;
 *     &lt;enumeration value="B519"/&gt;
 *     &lt;enumeration value="B520"/&gt;
 *     &lt;enumeration value="B521"/&gt;
 *     &lt;enumeration value="B522"/&gt;
 *     &lt;enumeration value="B523"/&gt;
 *     &lt;enumeration value="B601"/&gt;
 *     &lt;enumeration value="B602"/&gt;
 *     &lt;enumeration value="B603"/&gt;
 *     &lt;enumeration value="B604"/&gt;
 *     &lt;enumeration value="B605"/&gt;
 *     &lt;enumeration value="B606"/&gt;
 *     &lt;enumeration value="B607"/&gt;
 *     &lt;enumeration value="B608"/&gt;
 *     &lt;enumeration value="B609"/&gt;
 *     &lt;enumeration value="B610"/&gt;
 *     &lt;enumeration value="B611"/&gt;
 *     &lt;enumeration value="B701"/&gt;
 *     &lt;enumeration value="B702"/&gt;
 *     &lt;enumeration value="B703"/&gt;
 *     &lt;enumeration value="B704"/&gt;
 *     &lt;enumeration value="B705"/&gt;
 *     &lt;enumeration value="B706"/&gt;
 *     &lt;enumeration value="B707"/&gt;
 *     &lt;enumeration value="B708"/&gt;
 *     &lt;enumeration value="B709"/&gt;
 *     &lt;enumeration value="B750"/&gt;
 *     &lt;enumeration value="B751"/&gt;
 *     &lt;enumeration value="B752"/&gt;
 *     &lt;enumeration value="C750"/&gt;
 *     &lt;enumeration value="D101"/&gt;
 *     &lt;enumeration value="D102"/&gt;
 *     &lt;enumeration value="D103"/&gt;
 *     &lt;enumeration value="D104"/&gt;
 *     &lt;enumeration value="D105"/&gt;
 *     &lt;enumeration value="D201"/&gt;
 *     &lt;enumeration value="D202"/&gt;
 *     &lt;enumeration value="D203"/&gt;
 *     &lt;enumeration value="D204"/&gt;
 *     &lt;enumeration value="D205"/&gt;
 *     &lt;enumeration value="D206"/&gt;
 *     &lt;enumeration value="D207"/&gt;
 *     &lt;enumeration value="D301"/&gt;
 *     &lt;enumeration value="D302"/&gt;
 *     &lt;enumeration value="D303"/&gt;
 *     &lt;enumeration value="D304"/&gt;
 *     &lt;enumeration value="D305"/&gt;
 *     &lt;enumeration value="D306"/&gt;
 *     &lt;enumeration value="D307"/&gt;
 *     &lt;enumeration value="D308"/&gt;
 *     &lt;enumeration value="D309"/&gt;
 *     &lt;enumeration value="D310"/&gt;
 *     &lt;enumeration value="D311"/&gt;
 *     &lt;enumeration value="D312"/&gt;
 *     &lt;enumeration value="D313"/&gt;
 *     &lt;enumeration value="D314"/&gt;
 *     &lt;enumeration value="D315"/&gt;
 *     &lt;enumeration value="D316"/&gt;
 *     &lt;enumeration value="D317"/&gt;
 *     &lt;enumeration value="D318"/&gt;
 *     &lt;enumeration value="D319"/&gt;
 *     &lt;enumeration value="D320"/&gt;
 *     &lt;enumeration value="D321"/&gt;
 *     &lt;enumeration value="D322"/&gt;
 *     &lt;enumeration value="D323"/&gt;
 *     &lt;enumeration value="D324"/&gt;
 *     &lt;enumeration value="E100"/&gt;
 *     &lt;enumeration value="E101"/&gt;
 *     &lt;enumeration value="E102"/&gt;
 *     &lt;enumeration value="E103"/&gt;
 *     &lt;enumeration value="E104"/&gt;
 *     &lt;enumeration value="E105"/&gt;
 *     &lt;enumeration value="E106"/&gt;
 *     &lt;enumeration value="E107"/&gt;
 *     &lt;enumeration value="E108"/&gt;
 *     &lt;enumeration value="E109"/&gt;
 *     &lt;enumeration value="E110"/&gt;
 *     &lt;enumeration value="E111"/&gt;
 *     &lt;enumeration value="E112"/&gt;
 *     &lt;enumeration value="E113"/&gt;
 *     &lt;enumeration value="E114"/&gt;
 *     &lt;enumeration value="E115"/&gt;
 *     &lt;enumeration value="E116"/&gt;
 *     &lt;enumeration value="E117"/&gt;
 *     &lt;enumeration value="E118"/&gt;
 *     &lt;enumeration value="E119"/&gt;
 *     &lt;enumeration value="E120"/&gt;
 *     &lt;enumeration value="E121"/&gt;
 *     &lt;enumeration value="E122"/&gt;
 *     &lt;enumeration value="E123"/&gt;
 *     &lt;enumeration value="E124"/&gt;
 *     &lt;enumeration value="E125"/&gt;
 *     &lt;enumeration value="E126"/&gt;
 *     &lt;enumeration value="E127"/&gt;
 *     &lt;enumeration value="E128"/&gt;
 *     &lt;enumeration value="E129"/&gt;
 *     &lt;enumeration value="E130"/&gt;
 *     &lt;enumeration value="E131"/&gt;
 *     &lt;enumeration value="E132"/&gt;
 *     &lt;enumeration value="E133"/&gt;
 *     &lt;enumeration value="E134"/&gt;
 *     &lt;enumeration value="E135"/&gt;
 *     &lt;enumeration value="E136"/&gt;
 *     &lt;enumeration value="E139"/&gt;
 *     &lt;enumeration value="E140"/&gt;
 *     &lt;enumeration value="E141"/&gt;
 *     &lt;enumeration value="E142"/&gt;
 *     &lt;enumeration value="E143"/&gt;
 *     &lt;enumeration value="E144"/&gt;
 *     &lt;enumeration value="E145"/&gt;
 *     &lt;enumeration value="E146"/&gt;
 *     &lt;enumeration value="E147"/&gt;
 *     &lt;enumeration value="E148"/&gt;
 *     &lt;enumeration value="E149"/&gt;
 *     &lt;enumeration value="E150"/&gt;
 *     &lt;enumeration value="E200"/&gt;
 *     &lt;enumeration value="E201"/&gt;
 *     &lt;enumeration value="E202"/&gt;
 *     &lt;enumeration value="E203"/&gt;
 *     &lt;enumeration value="E204"/&gt;
 *     &lt;enumeration value="E205"/&gt;
 *     &lt;enumeration value="E206"/&gt;
 *     &lt;enumeration value="E210"/&gt;
 *     &lt;enumeration value="E211"/&gt;
 *     &lt;enumeration value="E212"/&gt;
 *     &lt;enumeration value="E213"/&gt;
 *     &lt;enumeration value="E221"/&gt;
 *     &lt;enumeration value="E222"/&gt;
 *     &lt;enumeration value="E223"/&gt;
 *     &lt;enumeration value="E224"/&gt;
 *     &lt;enumeration value="E225"/&gt;
 *     &lt;enumeration value="E226"/&gt;
 *     &lt;enumeration value="E227"/&gt;
 *     &lt;enumeration value="L101"/&gt;
 *     &lt;enumeration value="P091"/&gt;
 *     &lt;enumeration value="P092"/&gt;
 *     &lt;enumeration value="P096"/&gt;
 *     &lt;enumeration value="P097"/&gt;
 *     &lt;enumeration value="P098"/&gt;
 *     &lt;enumeration value="P099"/&gt;
 *     &lt;enumeration value="P101"/&gt;
 *     &lt;enumeration value="P102"/&gt;
 *     &lt;enumeration value="P103"/&gt;
 *     &lt;enumeration value="P104"/&gt;
 *     &lt;enumeration value="P105"/&gt;
 *     &lt;enumeration value="P106"/&gt;
 *     &lt;enumeration value="P107"/&gt;
 *     &lt;enumeration value="P108"/&gt;
 *     &lt;enumeration value="P109"/&gt;
 *     &lt;enumeration value="P110"/&gt;
 *     &lt;enumeration value="P111"/&gt;
 *     &lt;enumeration value="P112"/&gt;
 *     &lt;enumeration value="P113"/&gt;
 *     &lt;enumeration value="P114"/&gt;
 *     &lt;enumeration value="P115"/&gt;
 *     &lt;enumeration value="P116"/&gt;
 *     &lt;enumeration value="P131"/&gt;
 *     &lt;enumeration value="P132"/&gt;
 *     &lt;enumeration value="P133"/&gt;
 *     &lt;enumeration value="P134"/&gt;
 *     &lt;enumeration value="P120"/&gt;
 *     &lt;enumeration value="P121"/&gt;
 *     &lt;enumeration value="P122"/&gt;
 *     &lt;enumeration value="P123"/&gt;
 *     &lt;enumeration value="P124"/&gt;
 *     &lt;enumeration value="P125"/&gt;
 *     &lt;enumeration value="P126"/&gt;
 *     &lt;enumeration value="P127"/&gt;
 *     &lt;enumeration value="P201"/&gt;
 *     &lt;enumeration value="P202"/&gt;
 *     &lt;enumeration value="P203"/&gt;
 *     &lt;enumeration value="P204"/&gt;
 *     &lt;enumeration value="P301"/&gt;
 *     &lt;enumeration value="P305"/&gt;
 *     &lt;enumeration value="P306"/&gt;
 *     &lt;enumeration value="V201"/&gt;
 *     &lt;enumeration value="V202"/&gt;
 *     &lt;enumeration value="V203"/&gt;
 *     &lt;enumeration value="V205"/&gt;
 *     &lt;enumeration value="V206"/&gt;
 *     &lt;enumeration value="V207"/&gt;
 *     &lt;enumeration value="V210"/&gt;
 *     &lt;enumeration value="V211"/&gt;
 *     &lt;enumeration value="V212"/&gt;
 *     &lt;enumeration value="V213"/&gt;
 *     &lt;enumeration value="V214"/&gt;
 *     &lt;enumeration value="V215"/&gt;
 *     &lt;enumeration value="V220"/&gt;
 *     &lt;enumeration value="V221"/&gt;
 *     &lt;enumeration value="Z101"/&gt;
 *     &lt;enumeration value="Z102"/&gt;
 *     &lt;enumeration value="Z103"/&gt;
 *     &lt;enumeration value="Z111"/&gt;
 *     &lt;enumeration value="Z112"/&gt;
 *     &lt;enumeration value="Z113"/&gt;
 *     &lt;enumeration value="Z121"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List175")
@XmlEnum
public enum List175 {


    /**
     * CD ‘red book’ format
     * 
     */
    @XmlEnumValue("A101")
    A_101("A101"),
    @XmlEnumValue("A102")
    A_102("A102"),

    /**
     * MPEG-1/2 Audio Layer III file
     * 
     */
    @XmlEnumValue("A103")
    A_103("A103"),
    @XmlEnumValue("A104")
    A_104("A104"),
    @XmlEnumValue("A105")
    A_105("A105"),

    /**
     * Windows Media Audio format
     * 
     */
    @XmlEnumValue("A106")
    A_106("A106"),

    /**
     * Advanced Audio Coding format
     * 
     */
    @XmlEnumValue("A107")
    A_107("A107"),

    /**
     * Vorbis audio format in the Ogg container
     * 
     */
    @XmlEnumValue("A108")
    A_108("A108"),

    /**
     * Audio format proprietary to Audible.com
     * 
     */
    @XmlEnumValue("A109")
    A_109("A109"),

    /**
     * Free lossless audio codec
     * 
     */
    @XmlEnumValue("A110")
    A_110("A110"),

    /**
     * Audio Interchangeable File Format
     * 
     */
    @XmlEnumValue("A111")
    A_111("A111"),

    /**
     * Apple Lossless Audio Codec
     * 
     */
    @XmlEnumValue("A112")
    A_112("A112"),

    /**
     * Audiobook package format
     * 
     */
    @XmlEnumValue("A113")
    A_113("A113"),

    /**
     * Deprecated, as does not meet DAISY 2 standard. Use conventional audiobook codes instead
     * 
     */
    @XmlEnumValue("A201")
    A_201("A201"),
    @XmlEnumValue("A202")
    A_202("A202"),
    @XmlEnumValue("A203")
    A_203("A203"),
    @XmlEnumValue("A204")
    A_204("A204"),

    /**
     * Reading systems may provide full audio via text-to-speech
     * 
     */
    @XmlEnumValue("A205")
    A_205("A205"),

    /**
     * Reading systems may provide full audio via text-to-speech
     * 
     */
    @XmlEnumValue("A206")
    A_206("A206"),

    /**
     * Deprecated, as does not meet DAISY 3 standard. Use conventional audiobook codes instead
     * 
     */
    @XmlEnumValue("A207")
    A_207("A207"),
    @XmlEnumValue("A208")
    A_208("A208"),
    @XmlEnumValue("A209")
    A_209("A209"),
    @XmlEnumValue("A210")
    A_210("A210"),

    /**
     * Reading systems may provide full audio via text-to-speech
     * 
     */
    @XmlEnumValue("A211")
    A_211("A211"),

    /**
     * Reading systems may provide full audio via text-to-speech
     * 
     */
    @XmlEnumValue("A212")
    A_212("A212"),
    @XmlEnumValue("A301")
    A_301("A301"),

    /**
     * Audio intended exclusively for use alongside a printed copy of the book. Most often a children’s product. Normally contains instructions such as ‘turn the page now’ and other references to the printed item, and is usually sold packaged together with a printed copy
     * 
     */
    @XmlEnumValue("A302")
    A_302("A302"),

    /**
     * Audio intended for musical accompaniment, eg ‘Music minus one’, etc, often used for music learning. Includes singalong backing audio for musical learning or for Karaoke-style entertainment
     * 
     */
    @XmlEnumValue("A303")
    A_303("A303"),

    /**
     * Audio intended for language learning, which includes speech plus gaps intended to be filled by the listener
     * 
     */
    @XmlEnumValue("A304")
    A_304("A304"),

    /**
     * Audio synchronised to text within an e-publication, for example an EPUB3 with audio overlay. Synchronisation at least at paragraph level, and covering the full content
     * 
     */
    @XmlEnumValue("A305")
    A_305("A305"),

    /**
     * Incidental sounds added to the audiobook narration (eg background environmental sounds)
     * 
     */
    @XmlEnumValue("A310")
    A_310("A310"),

    /**
     * Incidental music added to the audiobook narration (eg to heighten atmosphere). Do not use where the music is a primary part of the audio
     * 
     */
    @XmlEnumValue("A311")
    A_311("A311"),

    /**
     * Pre-recorded audiobook narration does not contain any background sounds, including music, sound effects, etc, though music and effects may be present if isolated from the speech (ie the sounds do not overlap)
     * 
     */
    @XmlEnumValue("A312")
    A_312("A312"),

    /**
     * Constant or average bit rate (eg of an mp3 or AAC audio file) 64kbits/second or more. Note the bit rate is the total across all channels, not a per channel rate
     * 
     */
    @XmlEnumValue("A400")
    A_400("A400"),

    /**
     * Constant or average bit rate 128bbits/second or more
     * 
     */
    @XmlEnumValue("A401")
    A_401("A401"),
    @XmlEnumValue("A402")
    A_402("A402"),
    @XmlEnumValue("A403")
    A_403("A403"),
    @XmlEnumValue("A404")
    A_404("A404"),

    /**
     * Includes ‘stereo’ where channels are identical
     * 
     */
    @XmlEnumValue("A410")
    A_410("A410"),

    /**
     * Includes ‘joint stereo’
     * 
     */
    @XmlEnumValue("A420")
    A_420("A420"),

    /**
     * Stereo plus low-frequency channel
     * 
     */
    @XmlEnumValue("A421")
    A_421("A421"),

    /**
     * Five-channel audio (including low-frequency channel)
     * 
     */
    @XmlEnumValue("A441")
    A_441("A441"),

    /**
     * Six-channel audio (including low-frequency channel)
     * 
     */
    @XmlEnumValue("A451")
    A_451("A451"),

    /**
     * Multi-channel ‘spatial’ audio (eg for 7.1.4 speaker arrangements or processed for headphone delivery)
     * 
     */
    @XmlEnumValue("A471")
    A_471("A471"),

    /**
     * In North America, a category of paperback characterized partly by page size (typically from 6¾ up to 7⅛ x 4¼ inches) and partly by target market and terms of trade. Use with Product Form code BC
     * 
     */
    @XmlEnumValue("B101")
    B_101("B101"),

    /**
     * In North America, a category of paperback characterized partly by page size (larger than rack-sized) and partly by target market and terms of trade. AKA ‘quality paperback’, and including textbooks. Most paperback books sold in North America except ‘mass-market’ (B101) and ‘tall rack’ (B107) are correctly described with this code. Use with Product Form code BC
     * 
     */
    @XmlEnumValue("B102")
    B_102("B102"),

    /**
     * In North America, a category of paperback characterized by page size (typically 7 x 5 inches) and generally used for children’s books; use with Product Form code BC. Note: was wrongly shown as B102 (duplicate entry) in Issue 3
     * 
     */
    @XmlEnumValue("B103")
    B_103("B103"),

    /**
     * In UK and IE, a category of paperback characterized by page size (normally 178 x 111 mm approx); use with Product Form code BC
     * 
     */
    @XmlEnumValue("B104")
    B_104("B104"),

    /**
     * In UK and IE, a category of paperback characterized by page size (normally 198 x 129 mm approx); use with Product Form code BC
     * 
     */
    @XmlEnumValue("B105")
    B_105("B105"),

    /**
     * In UK and IE, a category of paperback characterized largely by size (usually in traditional hardback dimensions), and often used for paperback originals or retailer/travel/export-exclusives; use with Product Form code BC
     * 
     */
    @XmlEnumValue("B106")
    B_106("B106"),

    /**
     * In North America, a category of paperback characterised partly by page size (typically 7½ x 4¼ inches) and partly by target market and terms of trade; use with Product Form code BC
     * 
     */
    @XmlEnumValue("B107")
    B_107("B107"),

    /**
     * Japanese A-series size, 210 x 148mm. A tankobon is a complete collected story originally published in serialised form (eg in a magazine)
     * 
     */
    @XmlEnumValue("B108")
    B_108("B108"),

    /**
     * Japanese B-series size, 257 x 182mm
     * 
     */
    @XmlEnumValue("B109")
    B_109("B109"),

    /**
     * Japanese B-series size, 182 x 128mm
     * 
     */
    @XmlEnumValue("B110")
    B_110("B110"),

    /**
     * Japanese A-series size, 148 x 105mm
     * 
     */
    @XmlEnumValue("B111")
    B_111("B111"),

    /**
     * Japanese format, 182x103mm or 173x105mm
     * 
     */
    @XmlEnumValue("B112")
    B_112("B112"),

    /**
     * A Swedish, Norwegian, French paperback format, of no particular fixed size. Use with Product Form Code BC
     * 
     */
    @XmlEnumValue("B113")
    B_113("B113"),

    /**
     * A Swedish paperback format, use with Product Form Code BC. In Finnish, Jättipokkari
     * 
     */
    @XmlEnumValue("B114")
    B_114("B114"),

    /**
     * A Swedish hardback format, use with Product Form Code BB
     * 
     */
    @XmlEnumValue("B115")
    B_115("B115"),

    /**
     * A Swedish softback format, use with Product Form Code BC
     * 
     */
    @XmlEnumValue("B116")
    B_116("B116"),

    /**
     * A softback book in the format of a magazine, usually sold like a book. Use with Product Form code BC
     * 
     */
    @XmlEnumValue("B117")
    B_117("B117"),

    /**
     * Also called ‘Flipback’. A softback book in a specially compact proprietary format with pages printed in landscape on very thin paper and bound along the long (top) edge (ie parallel with the lines of text). Use with Product Form code BC – see www.dwarsligger.com
     * 
     */
    @XmlEnumValue("B118")
    B_118("B118"),

    /**
     * Japanese format, 188 x 127mm
     * 
     */
    @XmlEnumValue("B119")
    B_119("B119"),

    /**
     * Japanese format, approximately 188 x 127mm
     * 
     */
    @XmlEnumValue("B120")
    B_120("B120"),

    /**
     *  297 x 210mm
     * 
     */
    @XmlEnumValue("B121")
    B_121("B121"),

    /**
     * Japanese format, approximately 297 x 210mm
     * 
     */
    @XmlEnumValue("B122")
    B_122("B122"),

    /**
     * Japanese format, approximately 210 x 146mm
     * 
     */
    @XmlEnumValue("B123")
    B_123("B123"),

    /**
     * Japanese format, approximately 257 x 182mm
     * 
     */
    @XmlEnumValue("B124")
    B_124("B124"),

    /**
     * Japanese format, approximately 182 x 128mm
     * 
     */
    @XmlEnumValue("B125")
    B_125("B125"),

    /**
     *  257 x 210mm
     * 
     */
    @XmlEnumValue("B126")
    B_126("B126"),

    /**
     * Japanese B-series size, 128 x 91mm
     * 
     */
    @XmlEnumValue("B127")
    B_127("B127"),

    /**
     * Japanese format, 218 x 152mm or 227 x 152mm
     * 
     */
    @XmlEnumValue("B128")
    B_128("B128"),

    /**
     * Japanese format
     * 
     */
    @XmlEnumValue("B129")
    B_129("B129"),

    /**
     * Japanese B-series size, 364 x 257 mm
     * 
     */
    @XmlEnumValue("B130")
    B_130("B130"),

    /**
     * German large paperback format, greater than about 205mm high, with flaps. Use with Product form code BC
     * 
     */
    @XmlEnumValue("B131")
    B_131("B131"),

    /**
     * Spanish pocket paperback. Use with Product form code BC
     * 
     */
    @XmlEnumValue("B132")
    B_132("B132"),

    /**
     * Pocket-sized format, usually less than about 205mm high, without necessarily implying a particular trade category (de: ,Taschenbuch‘; it: «Tascabile / Supertascabile»; es: «libro de bolsillo»; fr: « livre de poche » etc). Use with Product form code BB or BC. See also List 12 code 04
     * 
     */
    @XmlEnumValue("B133")
    B_133("B133"),

    /**
     *  210 x 148mm
     * 
     */
    @XmlEnumValue("B134")
    B_134("B134"),

    /**
     * In North America, a category of paperback characterized partly by page size (typically 7⅛ x 4¾ inches) and partly by target market and terms of trade. Use with Product Form code BC
     * 
     */
    @XmlEnumValue("B135")
    B_135("B135"),

    /**
     * Standard 10.25 x 6.625in size approx (260 x 170mm)
     * 
     */
    @XmlEnumValue("B139")
    B_139("B139"),

    /**
     * Standard 240 x 320mm size approx
     * 
     */
    @XmlEnumValue("B140")
    B_140("B140"),

    /**
     * Japanese format, approximately 364 x 257 mm
     * 
     */
    @XmlEnumValue("B141")
    B_141("B141"),
    @XmlEnumValue("B201")
    B_201("B201"),
    @XmlEnumValue("B202")
    B_202("B202"),
    @XmlEnumValue("B204")
    B_204("B204"),
    @XmlEnumValue("B205")
    B_205("B205"),
    @XmlEnumValue("B206")
    B_206("B206"),
    @XmlEnumValue("B207")
    B_207("B207"),
    @XmlEnumValue("B208")
    B_208("B208"),
    @XmlEnumValue("B209")
    B_209("B209"),

    /**
     * A book whose pages have a variety of textured inserts designed to stimulate tactile exploration: see also B214 and B215
     * 
     */
    @XmlEnumValue("B210")
    B_210("B210"),

    /**
     * A book which is cut into a distinctive non-rectilinear shape and/or in which holes or shapes have been cut internally. (‘Die-cut’ is used here as a convenient shorthand, and does not imply strict limitation to a particular production process)
     * 
     */
    @XmlEnumValue("B212")
    B_212("B212"),

    /**
     * A book which is also a toy, or which incorporates a toy as an integral part. (Do not, however, use B213 for a multiple-item product which includes a book and a toy as separate items)
     * 
     */
    @XmlEnumValue("B213")
    B_213("B213"),

    /**
     * A book whose cover has a soft textured finish, typically over board
     * 
     */
    @XmlEnumValue("B214")
    B_214("B214"),

    /**
     * A book with detachable felt pieces and textured pages on which they can be arranged
     * 
     */
    @XmlEnumValue("B215")
    B_215("B215"),

    /**
     * A book containing pages with die-cut or press-out pieces that can be used as a jigsaw, as puzzle or game pieces, play pieces (eg paper dolls) etc
     * 
     */
    @XmlEnumValue("B216")
    B_216("B216"),

    /**
     * Picture book, generally for children, with few words per illustration: use with applicable Product Form code
     * 
     */
    @XmlEnumValue("B221")
    B_221("B221"),

    /**
     * (aka ‘Star’ book). Tax treatment of products may differ from that of products with similar codes such as Book as toy or Pop-up book)
     * 
     */
    @XmlEnumValue("B222")
    B_222("B222"),

    /**
     * A book with movable card ‘tabs’ within the pages. Pull a tab to reveal or animate part of a picture (distinct from a ‘lift-the-flap’ book, where flaps simply reveal hidden pictures, and not a ‘pop-up’ book with 3D paper engineering)
     * 
     */
    @XmlEnumValue("B223")
    B_223("B223"),

    /**
     * Picture book, generally for children though also used in augmentative and alternative education, without text in the body of the book. Also ‘silent books’, wordless graphic novels and comic books: use with applicable Product Form code
     * 
     */
    @XmlEnumValue("B224")
    B_224("B224"),

    /**
     * A book containing pages with pieces intended to be cut out (not pre-cut or press-out – see B216) that can be used as puzzle or game pieces, play pieces etc, but which may not be suitable for young children
     * 
     */
    @XmlEnumValue("B225")
    B_225("B225"),

    /**
     * Use with Product Form code BD, BN or PM
     * 
     */
    @XmlEnumValue("B301")
    B_301("B301"),

    /**
     * Use with Product Form code BD, BN or PM
     * 
     */
    @XmlEnumValue("B302")
    B_302("B302"),

    /**
     * Use with Product Form code BD, BN or PM
     * 
     */
    @XmlEnumValue("B303")
    B_303("B303"),

    /**
     * AKA stitched; for ‘saddle-sewn’, see code B310
     * 
     */
    @XmlEnumValue("B304")
    B_304("B304"),

    /**
     * Including ‘perfect bound’, ‘glued’
     * 
     */
    @XmlEnumValue("B305")
    B_305("B305"),

    /**
     * Strengthened cloth-over-boards binding intended for libraries: use with Product form code BB
     * 
     */
    @XmlEnumValue("B306")
    B_306("B306"),

    /**
     * Strengthened binding, not specifically intended for libraries: use with Product form code BB or BC
     * 
     */
    @XmlEnumValue("B307")
    B_307("B307"),

    /**
     * Highest qualiy material used on spine and corners only. Must be accompanied by a code specifiying a material, eg ‘half-bound real leather’
     * 
     */
    @XmlEnumValue("B308")
    B_308("B308"),

    /**
     * Highest qualiy material used on spine only. Must be accompanied by a code specifiying a material, eg ‘quarter bound real leather’
     * 
     */
    @XmlEnumValue("B309")
    B_309("B309"),

    /**
     * AKA ‘saddle-stitched’ or ‘wire-stitched’
     * 
     */
    @XmlEnumValue("B310")
    B_310("B310"),

    /**
     * Round or oval plastic forms in a clamp-like configuration: use with Product Form code BE
     * 
     */
    @XmlEnumValue("B311")
    B_311("B311"),

    /**
     * Twin loop metal wire spine: use with Product Form code BE
     * 
     */
    @XmlEnumValue("B312")
    B_312("B312"),

    /**
     * Cased over Coiled or Wire-O binding: use with Product Form code BE and Product Form Detail code B312 or B314
     * 
     */
    @XmlEnumValue("B313")
    B_313("B313"),

    /**
     * Spiral wire bound. Use with product form code BE. The default if a spiral binding type is not stated. Cf. Comb and Wire-O binding
     * 
     */
    @XmlEnumValue("B314")
    B_314("B314"),

    /**
     * Hardcover binding intended for general consumers rather than libraries, use with Product form code BB. The default if a hardcover binding detail is not stated. cf. Library binding
     * 
     */
    @XmlEnumValue("B315")
    B_315("B315"),

    /**
     * Cover is attached to the book block along only one edge of the spine, allowing the cover to lay flat
     * 
     */
    @XmlEnumValue("B316")
    B_316("B316"),

    /**
     * Refinement of perfect binding, with notches cut in the spine of the book block prior to glueing, to improve adhesion and durability
     * 
     */
    @XmlEnumValue("B317")
    B_317("B317"),

    /**
     * Hardcover or softcover where interior spreads lay flat across the spine
     * 
     */
    @XmlEnumValue("B318")
    B_318("B318"),

    /**
     * Hardcover where the cover boards are trimmed flush with the trimmed book block
     * 
     */
    @XmlEnumValue("B319")
    B_319("B319"),

    /**
     * Hardcover where the spine is rounded during binding
     * 
     */
    @XmlEnumValue("B320")
    B_320("B320"),

    /**
     * Hardcover where the spine is straight
     * 
     */
    @XmlEnumValue("B321")
    B_321("B321"),

    /**
     * Covers do not use a distinctive stock, but are the same as the body pages. Use for example with Product form BF, to indicate a pamphlet does not use a card or distinct paper cover. See also B416 (for card covers) and B418 (for distinct paper covers)
     * 
     */
    @XmlEnumValue("B400")
    B_400("B400"),

    /**
     * Cotton, linen or other woven fabric over boards. Use with <ProductForm> BB
     * 
     */
    @XmlEnumValue("B401")
    B_401("B401"),

    /**
     * Cellulose-based or similar non-woven material, which may be printed and may be embossed with an artificial cloth or leather-like texture, over boards. Use with <ProductForm> BB
     * 
     */
    @XmlEnumValue("B402")
    B_402("B402"),

    /**
     * Covered with leather created by tanning animal hide. May be ‘full-grain’ using the entire thickness of the hide, ‘top grain’ using the outer layer of the hide, or ‘split’ using the inner layers of the hide. Split leather may be embossed with an artificial grain or texture. Use with <ProductForm> BG, and if appropriate with codes B308 or B309 (otherwise ‘full-bound’ is implied)
     * 
     */
    @XmlEnumValue("B403")
    B_403("B403"),

    /**
     * Covered with synthetic leather-like material – polymer or non-animal fibre over a textile backing, usually coated and embossed with an artificial grain or texture. Leatherette, pleather etc. Use with <ProductForm> BB (or BG if particularly high-quality), and if appropriate with codes B308 or B309 (otherwise ‘full-bound’ is implied)
     * 
     */
    @XmlEnumValue("B404")
    B_404("B404"),

    /**
     * Covered with leather reconstituted from a pulp made from shredded animal hide, layered on a fibre or textile backing, coated and usually embossed with an artificial grain or texture. Use with <ProductForm> BG, and if appropriate with codes B308 or B309 (otherwise ‘full-bound’ is implied)
     * 
     */
    @XmlEnumValue("B405")
    B_405("B405"),

    /**
     * Pages made with prepared but untanned animal skin (usually calf, occasionally goat or sheep). Includes parchment, a thicker and less refined form of animal skin, but not ‘paper vellum’ or vegetable parchment made from synthetic or plant fibres
     * 
     */
    @XmlEnumValue("B406")
    B_406("B406"),

    /**
     * Decorative or functional
     * 
     */
    @XmlEnumValue("B407")
    B_407("B407"),

    /**
     * Colored, stained, gilded, patterned, abstract or illustrated sprayed edges. Use <ProductFormFeature> to specify the color, and optionally, use <SupportingResource> to provide an image of the decoration
     * 
     */
    @XmlEnumValue("B419")
    B_419("B419"),

    /**
     * Colored, patterned, printed, abstract or illustrated endpapers or of inside front and back covers. Use <ProductFormFeature> to specify the color, and optionally, use <SupportingResource> to provide an image of the decoration
     * 
     */
    @XmlEnumValue("B408")
    B_408("B408"),

    /**
     * Cloth, not necessarily over boards – cf B401
     * 
     */
    @XmlEnumValue("B409")
    B_409("B409"),

    /**
     * Spanish ‘simil-tela’
     * 
     */
    @XmlEnumValue("B410")
    B_410("B410"),
    @XmlEnumValue("B411")
    B_411("B411"),

    /**
     * AKA ‘flexibound’: use with Product Form code BC
     * 
     */
    @XmlEnumValue("B412")
    B_412("B412"),

    /**
     * Separate outer plastic cover, often transparent and allowing the cover to show through. Typically has pockets into which the cover tucks. See also B412, where the cover itself is plastic or vinyl
     * 
     */
    @XmlEnumValue("B413")
    B_413("B413"),

    /**
     * Separate outer vinyl cover. See also B412, where the cover itself is plastic or vinyl
     * 
     */
    @XmlEnumValue("B414")
    B_414("B414"),

    /**
     * Book, laminating material unspecified, often termed PLC or PPC (printed laminated case, printed paper case) when used with Product form BB. Use L101 for ‘whole product laminated’, eg a laminated sheet map or wallchart
     * 
     */
    @XmlEnumValue("B415")
    B_415("B415"),

    /**
     * With card cover (like a typical paperback). As distinct from a self-cover or more elaborate binding. Use for example with Product form BF, to indicate a pamphlet is bound within a card cover. See also B400 (for self-covers) and B418 (for distinct paper covers)
     * 
     */
    @XmlEnumValue("B416")
    B_416("B416"),

    /**
     * Printed both inside and outside the front and/or back cover
     * 
     */
    @XmlEnumValue("B417")
    B_417("B417"),

    /**
     * Cover uses a distinct, usually heavier (thicker) paper than the interior pages. Use for example with Product form BF, to indicate a pamphlet is bound within a paper cover. See also B400 (for self-covers) and B416 (for card covers)
     * 
     */
    @XmlEnumValue("B418")
    B_418("B418"),

    /**
     * Cover or jacket finish may merit special handling or packaging during distribution and fulfilment, for example because of gloss varnish which may hold fingerprints or matt laminate liable to scuffing
     * 
     */
    @XmlEnumValue("B420")
    B_420("B420"),

    /**
     * Embossing (or debossing) used on cover or jacket
     * 
     */
    @XmlEnumValue("B421")
    B_421("B421"),

    /**
     * Type unspecified
     * 
     */
    @XmlEnumValue("B501")
    B_501("B501"),

    /**
     * Used to distinguish from B503
     * 
     */
    @XmlEnumValue("B502")
    B_502("B502"),

    /**
     * With translucent paper or plastic protective cover
     * 
     */
    @XmlEnumValue("B503")
    B_503("B503"),

    /**
     * For paperback with flaps
     * 
     */
    @XmlEnumValue("B504")
    B_504("B504"),
    @XmlEnumValue("B505")
    B_505("B505"),

    /**
     * If the number of markers is significant, it can be stated as free text in <ProductFormDescription>
     * 
     */
    @XmlEnumValue("B506")
    B_506("B506"),
    @XmlEnumValue("B507")
    B_507("B507"),
    @XmlEnumValue("B508")
    B_508("B508"),

    /**
     * AKA yapp edge?
     * 
     */
    @XmlEnumValue("B509")
    B_509("B509"),

    /**
     * With edge trimming such that the front edge is ragged, not neatly and squarely trimmed: AKA deckle edge, feather edge, uncut edge, rough cut
     * 
     */
    @XmlEnumValue("B510")
    B_510("B510"),

    /**
     * With one or more gatefold or foldout sections bound in
     * 
     */
    @XmlEnumValue("B511")
    B_511("B511"),

    /**
     * Pages include extra-wide margin specifically intended for hand-written annotations
     * 
     */
    @XmlEnumValue("B512")
    B_512("B512"),

    /**
     * Book with attached loop for fixing to baby stroller, cot, chair etc
     * 
     */
    @XmlEnumValue("B513")
    B_513("B513"),

    /**
     * With one or more pages perforated and intended to be torn out for use
     * 
     */
    @XmlEnumValue("B514")
    B_514("B514"),

    /**
     * Printed on acid-free or alkaline buffered paper conforming with ISO 9706
     * 
     */
    @XmlEnumValue("B515")
    B_515("B515"),

    /**
     * Printed on acid-free or alkaline buffered paper with a high cotton content, conforming with ISO 11108
     * 
     */
    @XmlEnumValue("B516")
    B_516("B516"),

    /**
     * Strap acts as closure or as page marker
     * 
     */
    @XmlEnumValue("B517")
    B_517("B517"),

    /**
     * For example, holographic sticker such as the banderol used in the Turkish book trade
     * 
     */
    @XmlEnumValue("B518")
    B_518("B518"),

    /**
     * Jacket in the form of a pamphlet or poster, specifically intended to be removed and read or used separately from the book
     * 
     */
    @XmlEnumValue("B519")
    B_519("B519"),

    /**
     * Usually die-cut rounding to foredge corners of cover (and/or to foredge page corners). See B212 for elaborate die-cutting
     * 
     */
    @XmlEnumValue("B520")
    B_520("B520"),

    /**
     * Water-resistant or ‘waterproof’ cover and pages
     * 
     */
    @XmlEnumValue("B521")
    B_521("B521"),

    /**
     * Pages composed of ‘mineral paper’ comprised of HDPE plastic and ground calcium carbonate, eg Stonepaper
     * 
     */
    @XmlEnumValue("B522")
    B_522("B522"),

    /**
     * For example, cut-out claim form such as the ‘text data request ticket’ used in the Japanese book trade
     * 
     */
    @XmlEnumValue("B523")
    B_523("B523"),

    /**
     * A book in which half the content is printed upside-down, to be read the other way round. Also known as a ‘flip-book’ or ‘tête-bêche’ (Fr) binding, it has two front covers and a single spine. Usually an omnibus of two works
     * 
     */
    @XmlEnumValue("B601")
    B_601("B601"),

    /**
     * Manga with pages and panels in the sequence of (right-to-left flowing) Japanese-style design
     * 
     */
    @XmlEnumValue("B602")
    B_602("B602"),

    /**
     * A book in which half the content is printed so as to be read from the other cover. All content is printed the same way up. Also known as ‘dos-à-dos’ (Fr) binding, it has two front covers and two spines. Usually an omnibus of two works
     * 
     */
    @XmlEnumValue("B603")
    B_603("B603"),

    /**
     * Manga with pages and panels in the sequence mirrored from Japanese-style design (thus flowing left-to-right)
     * 
     */
    @XmlEnumValue("B604")
    B_604("B604"),

    /**
     * A book in which half the content is read the other way round from ‘back’ to ‘front’. A variant on ‘flip-book’ or ‘tête-bêche’ (fr) binding where the text is in two languages with different page progression (eg English and Arabic) and neither needs to be upside down, it has two front covers and a single spine. Usually an omnibus of a work and a derived translated work
     * 
     */
    @XmlEnumValue("B605")
    B_605("B605"),

    /**
     * Pages are ordered left to right (the left page in a spread is read before the right). Note this does not specifically mean text on the page is also read left to right
     * 
     */
    @XmlEnumValue("B606")
    B_606("B606"),

    /**
     * Pages are ordered right to left
     * 
     */
    @XmlEnumValue("B607")
    B_607("B607"),

    /**
     * Pages are ordered top to bottom, with the spine oriented horizontally. See also Dwarsligger (code B118), a proprietary variation of this format
     * 
     */
    @XmlEnumValue("B608")
    B_608("B608"),

    /**
     * Pages are ordered bottom to top, with the spine oriented horizontally, or in a way for which there is no other code
     * 
     */
    @XmlEnumValue("B609")
    B_609("B609"),

    /**
     * Text shows syllable breaks
     * 
     */
    @XmlEnumValue("B610")
    B_610("B610"),

    /**
     * For bicameral scripts, body text is upper case only
     * 
     */
    @XmlEnumValue("B611")
    B_611("B611"),

    /**
     * Single letters only. Was formerly identified as UK Braille Grade 1
     * 
     */
    @XmlEnumValue("B701")
    B_701("B701"),

    /**
     * With some letter combinations. Was formerly identified as UK Braille Grade 2
     * 
     */
    @XmlEnumValue("B702")
    B_702("B702"),

    /**
     * For US Braille, prefer codes B704 and B705 as appropriate
     * 
     */
    @XmlEnumValue("B703")
    B_703("B703"),
    @XmlEnumValue("B704")
    B_704("B704"),
    @XmlEnumValue("B705")
    B_705("B705"),

    /**
     * For UEB, prefer codes B708 and B709 as appropriate
     * 
     */
    @XmlEnumValue("B706")
    B_706("B706"),

    /**
     * Moon embossed alphabet, used by some print-impaired readers who have difficulties with Braille
     * 
     */
    @XmlEnumValue("B707")
    B_707("B707"),
    @XmlEnumValue("B708")
    B_708("B708"),
    @XmlEnumValue("B709")
    B_709("B709"),

    /**
     * Eg charts, diagrams, maps, or other tactile graphics or illustrations that are embossed or textured for accessibility purposes
     * 
     */
    @XmlEnumValue("B750")
    B_750("B750"),

    /**
     * Image-changing effect, ‘3D’ images, ‘tilt cards’, printed with tiny lenses
     * 
     */
    @XmlEnumValue("B751")
    B_751("B751"),

    /**
     * Stereoscopic 3D effect (eg of images) as viewed through red/green filters
     * 
     */
    @XmlEnumValue("B752")
    B_752("B752"),

    /**
     * Physical 3D relief (eg of a map, globe) reflects height of terrain etc
     * 
     */
    @XmlEnumValue("C750")
    C_750("C750"),

    /**
     * Proprietary RealNetworks format. Includes Real Video packaged within a .rm RealMedia container
     * 
     */
    @XmlEnumValue("D101")
    D_101("D101"),
    @XmlEnumValue("D102")
    D_102("D102"),
    @XmlEnumValue("D103")
    D_103("D103"),
    @XmlEnumValue("D104")
    D_104("D104"),
    @XmlEnumValue("D105")
    D_105("D105"),

    /**
     * Use with an applicable Product Form code D*; note that more detail of operating system requirements can be given in a Product Form Feature composite
     * 
     */
    @XmlEnumValue("D201")
    D_201("D201"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D202")
    D_202("D202"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D203")
    D_203("D203"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D204")
    D_204("D204"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D205")
    D_205("D205"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D206")
    D_206("D206"),

    /**
     * Use with an applicable Product Form code D*; see note on D201
     * 
     */
    @XmlEnumValue("D207")
    D_207("D207"),

    /**
     * Use with Product Form code DB or DI as applicable
     * 
     */
    @XmlEnumValue("D301")
    D_301("D301"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D302")
    D_302("D302"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D303")
    D_303("D303"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D304")
    D_304("D304"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D305")
    D_305("D305"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D306")
    D_306("D306"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D307")
    D_307("D307"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D308")
    D_308("D308"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D309")
    D_309("D309"),

    /**
     * Use with Product Form code DB as applicable
     * 
     */
    @XmlEnumValue("D310")
    D_310("D310"),

    /**
     * Use with Product Form code DB or DI as applicable
     * 
     */
    @XmlEnumValue("D311")
    D_311("D311"),

    /**
     * Use with Product Form code DE as applicable
     * 
     */
    @XmlEnumValue("D312")
    D_312("D312"),

    /**
     * Use with Product Form code DB, DI, DO or E* as applicable
     * 
     */
    @XmlEnumValue("D313")
    D_313("D313"),

    /**
     * Use with Product Form code DB, DI or VN as applicable
     * 
     */
    @XmlEnumValue("D314")
    D_314("D314"),

    /**
     * Use with Product Form code DA or E* as applicable
     * 
     */
    @XmlEnumValue("D315")
    D_315("D315"),

    /**
     * Use with Product Form code DL or VL as applicable
     * 
     */
    @XmlEnumValue("D316")
    D_316("D316"),

    /**
     * Use with Product Form code DB, DI, DO or E* as applicable. Deprecated – use D313
     * 
     */
    @XmlEnumValue("D317")
    D_317("D317"),

    /**
     * Use with Product Form code DB, DI, DO or E* as applicable
     * 
     */
    @XmlEnumValue("D318")
    D_318("D318"),

    /**
     * Use with Product Form code DA or E* as applicable
     * 
     */
    @XmlEnumValue("D319")
    D_319("D319"),

    /**
     * Use with Product Form code DB, DI, DO or E* as applicable
     * 
     */
    @XmlEnumValue("D320")
    D_320("D320"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D321")
    D_321("D321"),

    /**
     * Use with Product Form code DE or DB as applicable
     * 
     */
    @XmlEnumValue("D322")
    D_322("D322"),

    /**
     * Use with Product Form code DB, DI, DO or E* as applicable
     * 
     */
    @XmlEnumValue("D323")
    D_323("D323"),

    /**
     * Use with Product Form code DB, DI, DO or E* as applicable
     * 
     */
    @XmlEnumValue("D324")
    D_324("D324"),

    /**
     * No code allocated for this e-publication format yet
     * 
     */
    @XmlEnumValue("E100")
    E_100("E100"),

    /**
     * The Open Publication Structure / OPS Container Format standard of the International Digital Publishing Forum (IDPF) [File extension .epub]
     * 
     */
    @XmlEnumValue("E101")
    E_101("E101"),

    /**
     * The Open EBook format of the IDPF, a predecessor of the full EPUB format, still (2008) supported as part of the latter [File extension .opf]. Includes EPUB format up to and including version 2 – but prefer code E101 for EPUB 2, and always use code E101 for EPUB 3
     * 
     */
    @XmlEnumValue("E102")
    E_102("E102"),

    /**
     * Microsoft Word binary document format [File extension .doc]
     * 
     */
    @XmlEnumValue("E103")
    E_103("E103"),

    /**
     * Office Open XML / Microsoft Word XML document format (ISO/IEC 29500:2008) [File extension .docx]
     * 
     */
    @XmlEnumValue("E104")
    E_104("E104"),

    /**
     * HyperText Mark-up Language [File extension .html, .htm]
     * 
     */
    @XmlEnumValue("E105")
    E_105("E105"),

    /**
     * Open Document Format [File extension .odt]
     * 
     */
    @XmlEnumValue("E106")
    E_106("E106"),

    /**
     * Portable Document Format (ISO 32000-1:2008) [File extension .pdf]
     * 
     */
    @XmlEnumValue("E107")
    E_107("E107"),

    /**
     * PDF archiving format defined by ISO 19005-1:2005 [File extension .pdf]
     * 
     */
    @XmlEnumValue("E108")
    E_108("E108"),

    /**
     * Rich Text Format [File extension .rtf]
     * 
     */
    @XmlEnumValue("E109")
    E_109("E109"),

    /**
     * Standard Generalized Mark-up Language
     * 
     */
    @XmlEnumValue("E110")
    E_110("E110"),

    /**
     * A compressed text format mainly used on Psion handheld devices [File extension .tcr]
     * 
     */
    @XmlEnumValue("E111")
    E_111("E111"),

    /**
     * Text file format [File extension .txt]. Typically ASCII or Unicode UTF-8/16
     * 
     */
    @XmlEnumValue("E112")
    E_112("E112"),

    /**
     * Extensible Hypertext Markup Language [File extension .xhtml, .xht, .xml, .html, .htm]
     * 
     */
    @XmlEnumValue("E113")
    E_113("E113"),

    /**
     * A compressed text format mainly used on Palm handheld devices [File extension .pdb – see also E121, E125, E130]
     * 
     */
    @XmlEnumValue("E114")
    E_114("E114"),

    /**
     * XML Paper Specification format [File extension .xps]
     * 
     */
    @XmlEnumValue("E115")
    E_115("E115"),

    /**
     * A format proprietary to Amazon for use with its Kindle reading devices or software readers [File extensions .azw, .mobi, .prc etc]. Prefer code E148 for Print Replica files
     * 
     */
    @XmlEnumValue("E116")
    E_116("E116"),

    /**
     * A Sony proprietary format for use with the Sony Reader and LIBRIé reading devices [File extension .lrf]
     * 
     */
    @XmlEnumValue("E117")
    E_117("E117"),

    /**
     * A proprietary format for use with DXReader software
     * 
     */
    @XmlEnumValue("E118")
    E_118("E118"),

    /**
     * A format proprietary to the Ebook Library service
     * 
     */
    @XmlEnumValue("E119")
    E_119("E119"),

    /**
     * A format proprietary to the Ebrary service
     * 
     */
    @XmlEnumValue("E120")
    E_120("E120"),

    /**
     * A proprietary format for use with eReader (AKA ‘Palm Reader’) software on various hardware platforms [File extension .pdb – see also E114, E125, E130]
     * 
     */
    @XmlEnumValue("E121")
    E_121("E121"),

    /**
     * A proprietary format with its own reading system for Windows platforms [File extension .exe]
     * 
     */
    @XmlEnumValue("E122")
    E_122("E122"),

    /**
     * A proprietary format for use with the Franklin eBookman reader
     * 
     */
    @XmlEnumValue("E123")
    E_123("E123"),

    /**
     * A proprietary format for use with the Gemstar Rocketbook reader [File extension .rb]
     * 
     */
    @XmlEnumValue("E124")
    E_124("E124"),

    /**
     * A proprietary format for use with iSilo software on various hardware platforms [File extension .pdb – see also E114, E121, E130]
     * 
     */
    @XmlEnumValue("E125")
    E_125("E125"),

    /**
     * A proprietary format for use with Microsoft Reader software on Windows and Pocket PC platforms [File extension .lit]
     * 
     */
    @XmlEnumValue("E126")
    E_126("E126"),

    /**
     * A proprietary format for use with Mobipocket software on various hardware platforms [File extensions .mobi, .prc]. Includes Amazon Kindle formats up to and including version 7 – but prefer code E116 for version 7, and always use E116 for KF8
     * 
     */
    @XmlEnumValue("E127")
    E_127("E127"),

    /**
     * A format proprietary to the MyiLibrary service
     * 
     */
    @XmlEnumValue("E128")
    E_128("E128"),

    /**
     * A format proprietary to the NetLibrary service
     * 
     */
    @XmlEnumValue("E129")
    E_129("E129"),

    /**
     * A proprietary format for use with Plucker reader software on Palm and other handheld devices [File extension .pdb – see also E114, E121, E125]
     * 
     */
    @XmlEnumValue("E130")
    E_130("E130"),

    /**
     * A format proprietary to the VitalSource service
     * 
     */
    @XmlEnumValue("E131")
    E_131("E131"),

    /**
     * A proprietary digital product combining text and video content and available to be used online or as a downloadable application for a mobile device – see www.vook.com
     * 
     */
    @XmlEnumValue("E132")
    E_132("E132"),

    /**
     * An epublication made available by Google in association with a publisher; readable online on a browser-enabled device and offline on designated ebook readers
     * 
     */
    @XmlEnumValue("E133")
    E_133("E133"),

    /**
     * Epublication packaged as application for iOS (eg Apple iPhone, iPad etc), containing both executable code and content. Use <ProductContentType> to describe content, and <ProductFormFeatureType> to list detailed technical requirements
     * 
     */
    @XmlEnumValue("E134")
    E_134("E134"),

    /**
     * Epublication packaged as application for Android (eg Android phone or tablet), containing both executable code and content. Use <ProductContentType> to describe content, and <ProductFormFeatureType> to list detailed technical requirements
     * 
     */
    @XmlEnumValue("E135")
    E_135("E135"),

    /**
     * Epublication packaged as application, containing both executable code and content. Use where other ‘app’ codes are not applicable. Technical requirements such as target operating system and/or device should be provided eg in <ProductFormFeatureType>. Content type (text or text plus various ‘enhancements’) may be described with <ProductContentType>
     * 
     */
    @XmlEnumValue("E136")
    E_136("E136"),

    /**
     * Founder Apabi’s proprietary basic e-book format
     * 
     */
    @XmlEnumValue("E139")
    E_139("E139"),

    /**
     * Founder Apabi’s proprietary XML e-book format
     * 
     */
    @XmlEnumValue("E140")
    E_140("E140"),

    /**
     * Apple’s iBook format (a proprietary extension of EPUB), can only be read on Apple iOS devices
     * 
     */
    @XmlEnumValue("E141")
    E_141("E141"),

    /**
     * Proprietary format based on EPUB used by Barnes and Noble for fixed-format e-books, readable on NOOK devices and Nook reader software
     * 
     */
    @XmlEnumValue("E142")
    E_142("E142"),

    /**
     * Sharable Content Object Reference Model, standard content and packaging format for e-learning objects
     * 
     */
    @XmlEnumValue("E143")
    E_143("E143"),

    /**
     * E-book Plus (proprietary Norwegian e-book format)
     * 
     */
    @XmlEnumValue("E144")
    E_144("E144"),

    /**
     * Proprietary format based on PDF used by Barnes and Noble for fixed-format e-books, readable on some NOOK devices and Nook reader software
     * 
     */
    @XmlEnumValue("E145")
    E_145("E145"),

    /**
     * (Braille-ready file) Electronic Braille file
     * 
     */
    @XmlEnumValue("E146")
    E_146("E146"),

    /**
     * Proprietary XML format for articles, see for example https://www.cairn.info/services-aux-editeurs.php
     * 
     */
    @XmlEnumValue("E147")
    E_147("E147"),

    /**
     * A format proprietary to Amazon for use with its Kindle reading devices or software readers. Essentially a PDF embedded within a KF8 format file
     * 
     */
    @XmlEnumValue("E148")
    E_148("E148"),

    /**
     * Format for comic books, consisting primarily of sequentially-named PNG or JPEG images in a zip container
     * 
     */
    @XmlEnumValue("E149")
    E_149("E149"),
    @XmlEnumValue("E150")
    E_150("E150"),

    /**
     * Use this and/or code E201 when a particular e-publication type (specified using codes E100 and upwards) is reflowable or has both fixed layout and reflowable sections or variants, to indicate which option is included in this product
     * 
     */
    @XmlEnumValue("E200")
    E_200("E200"),

    /**
     * Use this and possibly code E200 when a particular e-publication type (specified using codes E100 and upwards) is fixed layout or has both fixed layout and reflowable sections or variants, to indicate which option is included in this product
     * 
     */
    @XmlEnumValue("E201")
    E_201("E201"),

    /**
     * All e-publication resources are included within the e-publication package
     * 
     */
    @XmlEnumValue("E202")
    E_202("E202"),

    /**
     * E-publication requires a network connection to access some resources (eg an enhanced e-book where video clips are not stored within the e-publication package itself, but are delivered via an internet connection)
     * 
     */
    @XmlEnumValue("E203")
    E_203("E203"),

    /**
     * Resources (eg images) present in other editions have been removed from this product, eg due to rights issues
     * 
     */
    @XmlEnumValue("E204")
    E_204("E204"),

    /**
     * (Mostly fixed-format) e-publication contains visible page numbers. Use with List 196 code 19 if numbering has a print-equivalent
     * 
     */
    @XmlEnumValue("E205")
    E_205("E205"),

    /**
     * For e-publications only, pages may be rendered LTR or RTL (see B606 to B609)
     * 
     */
    @XmlEnumValue("E206")
    E_206("E206"),

    /**
     * Use for fixed-format e-books optimised for landscape display. Also include an indication of the optimal screen aspect ratio
     * 
     */
    @XmlEnumValue("E210")
    E_210("E210"),

    /**
     * Use for fixed-format e-books optimised for portrait display. Also include an indication of the optimal screen aspect ratio
     * 
     */
    @XmlEnumValue("E211")
    E_211("E211"),

    /**
     * Use for fixed-format e-books optimised for a square display.
     * 
     */
    @XmlEnumValue("E212")
    E_212("E212"),

    /**
     * Use for fixed-format e-publications optimised for vertical scrolling display (‘webtoon format’)
     * 
     */
    @XmlEnumValue("E213")
    E_213("E213"),

    /**
     * (1.25:1) Use for fixed-format e-books optimised for displays with a 5:4 aspect ratio (eg 1280x1024 pixels etc, assuming square pixels). Note that aspect ratio codes are NOT specific to actual screen dimensions or pixel counts, but to the ratios between two dimensions or two pixel counts
     * 
     */
    @XmlEnumValue("E221")
    E_221("E221"),

    /**
     * (1.33:1) Use for fixed-format e-books optimised for displays with a 4:3 aspect ratio (eg 800x600, 1024x768, 2048x1536 pixels etc)
     * 
     */
    @XmlEnumValue("E222")
    E_222("E222"),

    /**
     * (1.5:1) Use for fixed-format e-books optimised for displays with a 3:2 aspect ratio (eg 960x640, 3072x2048 pixels etc)
     * 
     */
    @XmlEnumValue("E223")
    E_223("E223"),

    /**
     * (1.6:1) Use for fixed-format e-books optimised for displays with a 16:10 aspect ratio (eg 1440x900, 2560x1600 pixels etc)
     * 
     */
    @XmlEnumValue("E224")
    E_224("E224"),

    /**
     * (1.77:1) Use for fixed-format e-books optimised for displays with a 16:9 aspect ratio (eg 1024x576, 1920x1080, 2048x1152 pixels etc)
     * 
     */
    @XmlEnumValue("E225")
    E_225("E225"),

    /**
     * (2:1) Use for fixed-format e-books optimised for displays with an 18:9 aspect ratio (eg 2160x1080, 2880x1440 pixels etc)
     * 
     */
    @XmlEnumValue("E226")
    E_226("E226"),

    /**
     * (2.37:1) Use for fixed-format e-books optimised for displays with an 21:9 (or 64:27) aspect ratio (eg 3840x1644 pixels etc)
     * 
     */
    @XmlEnumValue("E227")
    E_227("E227"),

    /**
     * Whole product laminated (eg laminated map, fold-out chart, wallchart, etc): use B415 for book with laminated cover
     * 
     */
    @XmlEnumValue("L101")
    L_101("L101"),

    /**
     * (de: Nutzkalendarium) Calendar or diary has spaces intended for entering birthdays, appointments, notes etc. Use with other calendar / diary type codes
     * 
     */
    @XmlEnumValue("P091")
    P_091("P091"),

    /**
     * (de: Schmuckkalendarium) Calendar or diary has no spaces intended for entering birthdays, appointments, notes etc. Use with other calendar / diary type codes
     * 
     */
    @XmlEnumValue("P092")
    P_092("P092"),

    /**
     * (de: Mehrmonatskalender) Calendar has multiple months (but not whole year) per page or view. Use with other calendar / diary type codes when the time period per sheet, page or view is not the expected arrangement
     * 
     */
    @XmlEnumValue("P096")
    P_096("P096"),

    /**
     * (de: Monatskalender) Calendar has one month per page or view
     * 
     */
    @XmlEnumValue("P097")
    P_097("P097"),

    /**
     * (de: Wochenkalender) Calendar has one week per page or view
     * 
     */
    @XmlEnumValue("P098")
    P_098("P098"),

    /**
     * (de: Tageskalender) Calendar has one day per page or view
     * 
     */
    @XmlEnumValue("P099")
    P_099("P099"),

    /**
     * Large format, usually one week per page or view. Use with Product Form code PC or PF
     * 
     */
    @XmlEnumValue("P101")
    P_101("P101"),

    /**
     * Small format, usually one week per page or view. Use with Product Form code PC or PF
     * 
     */
    @XmlEnumValue("P102")
    P_102("P102"),

    /**
     * Day planner. Usually one day per page or view, with time-of-day subdivisions (rather than just days) or adequate space to add them. Use with Product Form code PC or PF
     * 
     */
    @XmlEnumValue("P103")
    P_103("P103"),

    /**
     * Eg tear-off calendars (one day per sheet). Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P104")
    P_104("P104"),

    /**
     * Large single-sheet calendar intended for hanging. Use with Product Form code PC or PK
     * 
     */
    @XmlEnumValue("P105")
    P_105("P105"),

    /**
     * Large calendar usually intended for hanging from the spine, typically one page per view and one month per view, with illustrations. See also P134. Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P106")
    P_106("P106"),

    /**
     * Usually undated. Use with Product Form code PC or PF, and can be combined with other calendar/diary type codes
     * 
     */
    @XmlEnumValue("P107")
    P_107("P107"),

    /**
     * Use with Product Form code PC, and can be combined with other calendar/diary type codes
     * 
     */
    @XmlEnumValue("P108")
    P_108("P108"),

    /**
     * Use with Product Form code PC or PT
     * 
     */
    @XmlEnumValue("P109")
    P_109("P109"),

    /**
     * Mid-year diary, start and end aligned with the academic year. Use with Product Form code PC or PF, and can be combined with other calendar/diary type codes
     * 
     */
    @XmlEnumValue("P110")
    P_110("P110"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P111")
    P_111("P111"),

    /**
     * Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P112")
    P_112("P112"),

    /**
     * A calendar, diary or organiser that is not one of the types specified elsewhere: use with Product Form code PC, PF or PS
     * 
     */
    @XmlEnumValue("P113")
    P_113("P113"),

    /**
     * A product that is associated with or ancillary to a calendar or organiser, eg a deskstand for a calendar, or an insert for an organiser: use with Product Form code PC or PS
     * 
     */
    @XmlEnumValue("P114")
    P_114("P114"),

    /**
     * Wall or poster calendar with entries for each family member. Use with Product Form code PC or PK
     * 
     */
    @XmlEnumValue("P115")
    P_115("P115"),

    /**
     * Calendar sheets detachable (usually perforated) and intended for mailing as postcards. Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P116")
    P_116("P116"),

    /**
     * Wall calendar without illustrations, usually one page per month, intended to be used by adding your own images (de: Bastelkalender). Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P131")
    P_131("P131"),

    /**
     * Very large wall calendar intended for hanging, usually one page per month, wide landscape orientation, with illustrations. Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P132")
    P_132("P132"),

    /**
     * Very large wall calendar intended for hanging, usually one page per month, narrow portrait orientation, with illustrations. Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P133")
    P_133("P133"),

    /**
     * (de: Broschurkalender) Wall calendar, usually intended for hanging from a page edge, typically two pages per view and one month per view, with illustrations. See also P106. Use with Product Form code PC
     * 
     */
    @XmlEnumValue("P134")
    P_134("P134"),

    /**
     * Kamishibai / Cantastoria cards
     * 
     */
    @XmlEnumValue("P120")
    P_120("P120"),

    /**
     * For use to specify letter, word, image (etc) recognition cards for teaching reading or other classroom use. Use with Product form code PD
     * 
     */
    @XmlEnumValue("P121")
    P_121("P121"),

    /**
     * Quick reference cards, revision cards, recipe cards etc. Use with Product form code PD
     * 
     */
    @XmlEnumValue("P122")
    P_122("P122"),

    /**
     * For use to specify cards and card decks for gaming, collecting and trading etc. Use also for divination cards. Use with Product form codes PD
     * 
     */
    @XmlEnumValue("P123")
    P_123("P123"),

    /**
     * And postcard packs / books. Use with Product form code PJ
     * 
     */
    @XmlEnumValue("P124")
    P_124("P124"),

    /**
     * And greeting card packs. Use with Product form code PJ
     * 
     */
    @XmlEnumValue("P125")
    P_125("P125"),

    /**
     * Physical cards which carry an intrinsic value, or which are intended to have value added to them, that may be redeemed later. For example book token cards, gift cards. Note value additions and redemption may be in a physical store or online
     * 
     */
    @XmlEnumValue("P126")
    P_126("P126"),

    /**
     * Blank certificate, award or achivement cards, Use with Product form code PD
     * 
     */
    @XmlEnumValue("P127")
    P_127("P127"),

    /**
     * Stationery item in hardback book format
     * 
     */
    @XmlEnumValue("P201")
    P_201("P201"),

    /**
     * Stationery item in paperback/softback book format
     * 
     */
    @XmlEnumValue("P202")
    P_202("P202"),

    /**
     * Stationery item in spiral-bound book format
     * 
     */
    @XmlEnumValue("P203")
    P_203("P203"),

    /**
     * Stationery item in leather-bound book format, or other fine binding
     * 
     */
    @XmlEnumValue("P204")
    P_204("P204"),

    /**
     * For wall map, poster, wallchart etc
     * 
     */
    @XmlEnumValue("P301")
    P_301("P301"),

    /**
     * Content is printed single-sided (for wallcharts and hanging maps, calendars, etc)
     * 
     */
    @XmlEnumValue("P305")
    P_305("P305"),

    /**
     * Content is printed double-sided (for wallcharts and hanging maps, calendars, etc, where double-sided may not always be expected)
     * 
     */
    @XmlEnumValue("P306")
    P_306("P306"),

    /**
     * SD TV standard for video or DVD
     * 
     */
    @XmlEnumValue("V201")
    V_201("V201"),

    /**
     * SD TV standard for video or DVD
     * 
     */
    @XmlEnumValue("V202")
    V_202("V202"),

    /**
     * SD TV standard for video or DVD
     * 
     */
    @XmlEnumValue("V203")
    V_203("V203"),

    /**
     * Up to 2K resolution (1920 or 2048 pixels wide) eg for Blu-Ray
     * 
     */
    @XmlEnumValue("V205")
    V_205("V205"),

    /**
     * Up to 4K resolution (3840 or 4096 pixels wide) eg for Ultra HD Blu-Ray
     * 
     */
    @XmlEnumValue("V206")
    V_206("V206"),

    /**
     * Eg for Blu-ray 3D
     * 
     */
    @XmlEnumValue("V207")
    V_207("V207"),

    /**
     * Or subtitles, where visibility may be controlled by the viewer. Use <Language> for the language of the captions/subtitles
     * 
     */
    @XmlEnumValue("V210")
    V_210("V210"),

    /**
     * ‘Burnt-in’ or hard captions or subtitles. Use <Language> for the language of the captions/subtitles
     * 
     */
    @XmlEnumValue("V211")
    V_211("V211"),

    /**
     * Full transcript of audio and audiovisual content included within the product supplied. See also List 158, where a transcript is a separate resource
     * 
     */
    @XmlEnumValue("V212")
    V_212("V212"),

    /**
     * Full signing of audio and audiovisual content of the included within the product supplied
     * 
     */
    @XmlEnumValue("V213")
    V_213("V213"),

    /**
     * Closed or open captions/subtitles include descriptions of non-dialogue audio (eg background sounds, music, speaker identification) in addition to dialogue. Use in combination with V210 or V211. Use V210, V211 alone for captions/subtitles that include only dialogue. In some markets, described audio is termed ‘subtitles for the deaf and hard of hearing’
     * 
     */
    @XmlEnumValue("V214")
    V_214("V214"),

    /**
     * Also termed ‘described video’ – audio track describes the video content
     * 
     */
    @XmlEnumValue("V215")
    V_215("V215"),

    /**
     * Licensed for use in domestic contexts only
     * 
     */
    @XmlEnumValue("V220")
    V_220("V220"),

    /**
     * Licensed for use in education
     * 
     */
    @XmlEnumValue("V221")
    V_221("V221"),

    /**
     * Primary material composition (eg of kit or puzzle pieces, of gameplay tokens or tiles) is wood or has wooden pieces/parts
     * 
     */
    @XmlEnumValue("Z101")
    Z_101("Z101"),

    /**
     * Plastic or plastic pieces/parts
     * 
     */
    @XmlEnumValue("Z102")
    Z_102("Z102"),

    /**
     * Card or board pieces/parts
     * 
     */
    @XmlEnumValue("Z103")
    Z_103("Z103"),

    /**
     * Puzzle assembles into a 3D object
     * 
     */
    @XmlEnumValue("Z111")
    Z_111("Z111"),

    /**
     * Toy makes a noise. See B208 for noisy books
     * 
     */
    @XmlEnumValue("Z112")
    Z_112("Z112"),

    /**
     * Including finger / hand puppets, marionettes
     * 
     */
    @XmlEnumValue("Z113")
    Z_113("Z113"),

    /**
     * Designed and sized for the very young, or those with visual impairments, limited motor skills, dementia etc
     * 
     */
    @XmlEnumValue("Z121")
    Z_121("Z121");
    private final String value;

    List175(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List175 fromValue(String v) {
        for (List175 c: List175 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
