//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.28 at 12:19:02 PM CEST 
//


package org.editeur.ns.onix._3_0.reference;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for List259.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="List259"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="u"/&gt;
 *     &lt;enumeration value="i"/&gt;
 *     &lt;enumeration value="r"/&gt;
 *     &lt;enumeration value="e"/&gt;
 *     &lt;enumeration value="a"/&gt;
 *     &lt;enumeration value="b"/&gt;
 *     &lt;enumeration value="t"/&gt;
 *     &lt;enumeration value="q"/&gt;
 *     &lt;enumeration value="s"/&gt;
 *     &lt;enumeration value="m"/&gt;
 *     &lt;enumeration value="f"/&gt;
 *     &lt;enumeration value="w"/&gt;
 *     &lt;enumeration value="d"/&gt;
 *     &lt;enumeration value="x"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "List259")
@XmlEnum
public enum List259 {

    @XmlEnumValue("u")
    U("u"),

    /**
     * No fixed publication schedule
     * 
     */
    @XmlEnumValue("i")
    I("i"),

    /**
     * New products in the collection are regularly scheduled, but less frequently than once every two years
     * 
     */
    @XmlEnumValue("r")
    R("r"),

    /**
     * Once every two years
     * 
     */
    @XmlEnumValue("e")
    E("e"),

    /**
     * Yearly
     * 
     */
    @XmlEnumValue("a")
    A("a"),

    /**
     * Twice a year, or once per academic semester
     * 
     */
    @XmlEnumValue("b")
    B("b"),

    /**
     * Three times a year, or once per academic term
     * 
     */
    @XmlEnumValue("t")
    T("t"),

    /**
     * Four times a year
     * 
     */
    @XmlEnumValue("q")
    Q("q"),

    /**
     * Six times per year
     * 
     */
    @XmlEnumValue("s")
    S("s"),

    /**
     * Once every month, or approximately twelve times per year
     * 
     */
    @XmlEnumValue("m")
    M("m"),

    /**
     * Once every two weeks, or approximately twenty five times per year
     * 
     */
    @XmlEnumValue("f")
    F("f"),

    /**
     * Or approximately fifty times per year
     * 
     */
    @XmlEnumValue("w")
    W("w"),

    /**
     * At least twice a week
     * 
     */
    @XmlEnumValue("d")
    D("d"),

    /**
     * Positive indication that the product is the last to be published in the collection, or that no further publications are planned
     * 
     */
    @XmlEnumValue("x")
    X("x");
    private final String value;

    List259(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static List259 fromValue(String v) {
        for (List259 c: List259 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
