//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.27 at 11:32:06 AM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ns.editeur.org/onix/3.0/reference", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.editeur.ns.onix._3_0.reference;
